-- 無料版＝基本100語。既存語をいったん premium に倒し、基本100語を free として upsert（冪等）。
UPDATE words SET tier = 'premium' WHERE tier = 'free';

INSERT INTO words (word, reading, meaning, example_en, example_ja, grade, level, tier, is_idiom, answers_en) VALUES
-- 動物
('apple','アップル','リンゴ','I eat an apple every day.','私は毎日リンゴを食べます。','中1','基礎','free',false,ARRAY['apple']),
('dog','ドッグ','犬','My dog is very cute.','私の犬はとてもかわいいです。','中1','基礎','free',false,ARRAY['dog']),
('cat','キャット','猫','The cat is sleeping.','猫が眠っています。','中1','基礎','free',false,ARRAY['cat']),
('bird','バード','鳥','A bird is singing.','鳥が歌っています。','中1','基礎','free',false,ARRAY['bird']),
('fish','フィッシュ','魚','I like to eat fish.','私は魚を食べるのが好きです。','中1','基礎','free',false,ARRAY['fish']),
('lion','ライオン','ライオン','The lion is the king of animals.','ライオンは動物の王です。','中1','基礎','free',false,ARRAY['lion']),
('horse','ホース','馬','He can ride a horse.','彼は馬に乗れます。','中1','基礎','free',false,ARRAY['horse']),
('rabbit','ラビット','うさぎ','The rabbit runs fast.','うさぎは速く走ります。','中1','基礎','free',false,ARRAY['rabbit']),
-- 食べ物・飲み物
('bread','ブレッド','パン','I eat bread for breakfast.','朝食にパンを食べます。','中1','基礎','free',false,ARRAY['bread']),
('rice','ライス','米、ごはん','We eat rice every day.','私たちは毎日ごはんを食べます。','中1','基礎','free',false,ARRAY['rice']),
('egg','エッグ','卵','She bought ten eggs.','彼女は卵を10個買いました。','中1','基礎','free',false,ARRAY['egg']),
('milk','ミルク','牛乳','Drink your milk.','牛乳を飲みなさい。','中1','基礎','free',false,ARRAY['milk']),
('water','ウォーター','水','Please drink more water.','もっと水を飲んでください。','中1','基礎','free',false,ARRAY['water']),
('tea','ティー','お茶','Would you like some tea?','お茶はいかがですか。','中1','基礎','free',false,ARRAY['tea']),
('lunch','ランチ','昼食','Let''s have lunch together.','一緒に昼食を食べましょう。','中1','基礎','free',false,ARRAY['lunch']),
('dinner','ディナー','夕食','We had dinner at seven.','私たちは7時に夕食を食べました。','中1','基礎','free',false,ARRAY['dinner']),
-- 家族・人
('family','ファミリー','家族','My family is important to me.','家族は私にとって大切です。','中1','基礎','free',false,ARRAY['family']),
('friend','フレンド','友達','She is my best friend.','彼女は私の親友です。','中1','基礎','free',false,ARRAY['friend']),
('father','ファーザー','父','My father is a teacher.','私の父は教師です。','中1','基礎','free',false,ARRAY['father']),
('mother','マザー','母','My mother cooks well.','私の母は料理が上手です。','中1','基礎','free',false,ARRAY['mother']),
('brother','ブラザー','兄、弟','I have one brother.','私には兄弟が一人います。','中1','基礎','free',false,ARRAY['brother']),
('sister','シスター','姉、妹','Her sister is kind.','彼女の姉は親切です。','中1','基礎','free',false,ARRAY['sister']),
('boy','ボーイ','男の子','The boy is running.','その男の子は走っています。','中1','基礎','free',false,ARRAY['boy']),
('girl','ガール','女の子','The girl likes flowers.','その女の子は花が好きです。','中1','基礎','free',false,ARRAY['girl']),
('teacher','ティーチャー','先生','Our teacher is funny.','私たちの先生は面白いです。','中1','基礎','free',false,ARRAY['teacher']),
('student','ステューデント','生徒','He is a good student.','彼は良い生徒です。','中1','基礎','free',false,ARRAY['student']),
-- 学校・もの
('book','ブック','本','This book is interesting.','この本は面白いです。','中1','基礎','free',false,ARRAY['book']),
('pen','ペン','ペン','May I use your pen?','ペンを借りてもいいですか。','中1','基礎','free',false,ARRAY['pen']),
('desk','デスク','机','Put it on the desk.','それを机の上に置いて。','中1','基礎','free',false,ARRAY['desk']),
('chair','チェア','いす','Sit on the chair.','いすに座って。','中1','基礎','free',false,ARRAY['chair']),
('bag','バッグ','かばん','My bag is heavy.','私のかばんは重いです。','中1','基礎','free',false,ARRAY['bag']),
('school','スクール','学校','I go to school every day.','毎日学校に行きます。','中1','基礎','free',false,ARRAY['school']),
('class','クラス','授業、クラス','We have math class now.','今は数学の授業です。','中1','基礎','free',false,ARRAY['class']),
('pencil','ペンシル','えんぴつ','I need a pencil.','えんぴつが必要です。','中1','基礎','free',false,ARRAY['pencil']),
('notebook','ノートブック','ノート','Write it in your notebook.','ノートに書いて。','中1','基礎','free',false,ARRAY['notebook']),
('computer','コンピューター','コンピューター','I use a computer at work.','仕事でコンピューターを使います。','中1','基礎','free',false,ARRAY['computer']),
-- 体
('hand','ハンド','手','Raise your hand.','手を挙げて。','中1','基礎','free',false,ARRAY['hand']),
('eye','アイ','目','Close your eyes.','目を閉じて。','中1','基礎','free',false,ARRAY['eye']),
('head','ヘッド','頭','My head hurts.','頭が痛いです。','中1','基礎','free',false,ARRAY['head']),
('face','フェイス','顔','Wash your face.','顔を洗って。','中1','基礎','free',false,ARRAY['face']),
('foot','フット','足','My foot is cold.','足が冷たいです。','中1','基礎','free',false,ARRAY['foot']),
-- 自然・時間
('sun','サン','太陽','The sun is bright.','太陽が明るいです。','中1','基礎','free',false,ARRAY['sun']),
('moon','ムーン','月','The moon is beautiful tonight.','今夜は月がきれいです。','中1','基礎','free',false,ARRAY['moon']),
('sky','スカイ','空','The sky is blue.','空が青いです。','中1','基礎','free',false,ARRAY['sky']),
('sea','シー','海','We swam in the sea.','私たちは海で泳ぎました。','中1','基礎','free',false,ARRAY['sea']),
('rain','レイン','雨','It will rain tomorrow.','明日は雨が降るでしょう。','中1','基礎','free',false,ARRAY['rain']),
('snow','スノー','雪','Children love snow.','子どもたちは雪が大好きです。','中1','基礎','free',false,ARRAY['snow']),
('tree','ツリー','木','There is a big tree.','大きな木があります。','中1','基礎','free',false,ARRAY['tree']),
('flower','フラワー','花','The flowers are pretty.','花がきれいです。','中1','基礎','free',false,ARRAY['flower']),
('time','タイム','時間','What time is it?','今何時ですか。','中1','基礎','free',false,ARRAY['time']),
('day','デイ','日、昼','Have a nice day.','よい一日を。','中1','基礎','free',false,ARRAY['day']),
('year','イヤー','年','See you next year.','また来年。','中1','基礎','free',false,ARRAY['year']),
('morning','モーニング','朝','Good morning!','おはよう！','中1','基礎','free',false,ARRAY['morning']),
('night','ナイト','夜','Good night.','おやすみなさい。','中1','基礎','free',false,ARRAY['night']),
-- 場所
('house','ハウス','家','This is my house.','これは私の家です。','中1','基礎','free',false,ARRAY['house']),
('home','ホーム','家、家庭','I want to go home.','家に帰りたいです。','中1','基礎','free',false,ARRAY['home']),
('park','パーク','公園','Let''s meet at the park.','公園で会いましょう。','中1','基礎','free',false,ARRAY['park']),
('station','ステーション','駅','The station is near here.','駅はこの近くです。','中1','基礎','free',false,ARRAY['station']),
('city','シティ','都市、市','Tokyo is a big city.','東京は大きな都市です。','中1','基礎','free',false,ARRAY['city']),
('country','カントリー','国、田舎','Japan is a beautiful country.','日本は美しい国です。','中1','基礎','free',false,ARRAY['country']),
('room','ルーム','部屋','Clean your room.','部屋を掃除して。','中1','基礎','free',false,ARRAY['room']),
('shop','ショップ','店','The shop is closed.','その店は閉まっています。','中1','基礎','free',false,ARRAY['shop','store']),
-- 基本動詞
('eat','イート','食べる','We eat dinner together.','私たちは一緒に夕食を食べます。','中1','基礎','free',false,ARRAY['eat']),
('drink','ドリンク','飲む','I drink coffee in the morning.','朝にコーヒーを飲みます。','中1','基礎','free',false,ARRAY['drink']),
('go','ゴー','行く','Let''s go to the park.','公園に行きましょう。','中1','基礎','free',false,ARRAY['go']),
('come','カム','来る','Come here, please.','こちらに来てください。','中1','基礎','free',false,ARRAY['come']),
('see','シー','見る、会う','I see a bird.','鳥が見えます。','中1','基礎','free',false,ARRAY['see']),
('look','ルック','見る','Look at the sky.','空を見て。','中1','基礎','free',false,ARRAY['look']),
('run','ラン','走る','I run every morning.','毎朝走ります。','中1','基礎','free',false,ARRAY['run']),
('walk','ウォーク','歩く','Let''s walk to school.','歩いて学校に行こう。','中1','基礎','free',false,ARRAY['walk']),
('play','プレイ','遊ぶ、(楽器を)演奏する','Children play in the park.','子どもたちが公園で遊んでいます。','中1','基礎','free',false,ARRAY['play']),
('read','リード','読む','I read a book at night.','夜に本を読みます。','中1','基礎','free',false,ARRAY['read']),
('write','ライト','書く','Write your name here.','ここに名前を書いて。','中1','基礎','free',false,ARRAY['write']),
('study','スタディ','勉強する','I study English every night.','毎晩英語を勉強します。','中1','基礎','free',false,ARRAY['study']),
('speak','スピーク','話す','She can speak English.','彼女は英語を話せます。','中1','基礎','free',false,ARRAY['speak']),
('listen','リッスン','聞く','Listen to me.','私の話を聞いて。','中1','基礎','free',false,ARRAY['listen']),
('make','メイク','作る','I make lunch every day.','毎日昼食を作ります。','中1','基礎','free',false,ARRAY['make']),
('like','ライク','好む','I like music.','私は音楽が好きです。','中1','基礎','free',false,ARRAY['like']),
('want','ウォント','ほしい','I want a new bike.','新しい自転車がほしいです。','中1','基礎','free',false,ARRAY['want']),
('know','ノウ','知っている','I know him well.','彼をよく知っています。','中1','基礎','free',false,ARRAY['know']),
('think','シンク','考える、思う','I think you are right.','あなたは正しいと思います。','中1','基礎','free',false,ARRAY['think']),
('have','ハブ','持っている','I have two dogs.','私は犬を2匹飼っています。','中1','基礎','free',false,ARRAY['have']),
('help','ヘルプ','助ける、手伝う','Can you help me?','手伝ってくれますか。','中1','基礎','free',false,ARRAY['help']),
('open','オープン','開ける','Open the window.','窓を開けて。','中1','基礎','free',false,ARRAY['open']),
('buy','バイ','買う','I want to buy a book.','本を買いたいです。','中1','基礎','free',false,ARRAY['buy']),
-- 形容詞・その他
('happy','ハッピー','幸せな、うれしい','I am very happy today.','今日はとても幸せです。','中1','基礎','free',false,ARRAY['happy']),
('sad','サッド','悲しい','Why are you sad?','どうして悲しいの。','中1','基礎','free',false,ARRAY['sad']),
('big','ビッグ','大きい','That is a big dog.','あれは大きな犬です。','中1','基礎','free',false,ARRAY['big']),
('small','スモール','小さい','I have a small bag.','私は小さなかばんを持っています。','中1','基礎','free',false,ARRAY['small']),
('new','ニュー','新しい','I bought a new phone.','新しい電話を買いました。','中1','基礎','free',false,ARRAY['new']),
('old','オールド','古い、年をとった','This is an old house.','これは古い家です。','中1','基礎','free',false,ARRAY['old']),
('good','グッド','良い','That''s a good idea.','それは良い考えです。','中1','基礎','free',false,ARRAY['good']),
('hot','ホット','暑い、熱い','It is hot today.','今日は暑いです。','中1','基礎','free',false,ARRAY['hot']),
('cold','コールド','寒い、冷たい','The water is cold.','水が冷たいです。','中1','基礎','free',false,ARRAY['cold']),
('long','ロング','長い','She has long hair.','彼女は髪が長いです。','中1','基礎','free',false,ARRAY['long']),
('fast','ファスト','速い、速く','He is a fast runner.','彼は走るのが速いです。','中1','基礎','free',false,ARRAY['fast']),
('easy','イージー','簡単な','This question is easy.','この問題は簡単です。','中1','基礎','free',false,ARRAY['easy']),
('beautiful','ビューティフル','美しい','What a beautiful flower!','なんて美しい花でしょう！','中1','基礎','free',false,ARRAY['beautiful']),
('music','ミュージック','音楽','Music makes me happy.','音楽は私を幸せにします。','中1','基礎','free',false,ARRAY['music']),
('name','ネーム','名前','What is your name?','あなたの名前は何ですか。','中1','基礎','free',false,ARRAY['name']),
('color','カラー','色','What color do you like?','何色が好きですか。','中1','基礎','free',false,ARRAY['color','colour']),
('game','ゲーム','ゲーム、試合','Let''s play a game.','ゲームをしましょう。','中1','基礎','free',false,ARRAY['game'])
ON CONFLICT (word) DO UPDATE SET
  reading = EXCLUDED.reading,
  meaning = EXCLUDED.meaning,
  example_en = EXCLUDED.example_en,
  example_ja = EXCLUDED.example_ja,
  grade = EXCLUDED.grade,
  level = EXCLUDED.level,
  tier = 'free',
  is_idiom = EXCLUDED.is_idiom,
  answers_en = EXCLUDED.answers_en;
