-- 高校受験語彙（自動生成・冪等・既存は保護）part 3
INSERT INTO words (word, reading, meaning, example_en, example_ja, grade, level, tier, is_idiom, tags, answers_en) VALUES
('preserve','プリザーヴ','保存する、保護する','Preserve nature.','自然を保護しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['preserve']),
('president','プレジデント','大統領、社長','He is the president.','彼が社長だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['president']),
('press','プレス','押す、報道','Press the red button.','赤いボタンを押しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['press']),
('pressure','プレッシャー','圧力、プレッシャー','I feel pressure.','プレッシャーを感じる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pressure']),
('pretend','プリテンド','〜のふりをする','Don''t pretend to be asleep.','眠っているふりをするな。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['pretend']),
('pretty','プリティ','かわいらしい、かなり','She is a pretty girl.','彼女はかわいい少女だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['pretty']),
('prevent','プリヴェント','防ぐ、妨げる','Prevent accidents.','事故を防ぎなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['prevent']),
('previous','プリヴィアス','前の、以前の','The previous day was busy.','前日は忙しかった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['previous']),
('price','プライス','価格、値段','The price is too high.','値段が高すぎる。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['price']),
('pride','プライド','誇り、自尊心','He takes pride in his work.','彼は仕事に誇りを持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['pride']),
('priest','プリースト','聖職者、牧師','Talk to the priest.','牧師に話しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['priest']),
('primary','プライマリー','主要な、初期の','It is my primary goal.','それが私の主要な目標だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['primary']),
('prime','プライム','最も重要な、第一の','That is the prime example.','それが第一の例だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['prime']),
('prince','プリンス','王子','He is a prince.','彼は王子だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['prince']),
('princess','プリンセス','王女、姫','She is a princess.','彼女は王女だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['princess']),
('principal','プリンシパル','校長、主要な','The principal is kind.','校長先生は親切だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['principal']),
('principle','プリンシプル','原則、原理','It is a basic principle.','それは基本的な原則だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['principle']),
('print','プリント','印刷する、文字','Print this document.','この文書を印刷しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['print']),
('prison','プリズン','刑務所','He was sent to prison.','彼は刑務所に入れられた。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['prison','jail']),
('private','プライヴェート','私的な、個人の','This is a private matter.','これは個人的な問題だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['private']),
('prize','プライズ','賞、賞品','He won the first prize.','彼は一等賞を勝ち取った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['prize']),
('probably','プロバブリー','たぶん','He will probably come.','たぶん彼は来るだろう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['probably']),
('problem','プロブレム','問題','I have a problem.','問題があります。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['problem']),
('process','プロセス','過程、処理する','It is a long process.','それは長い過程だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['process']),
('produce','プロデュース','生産する','They produce cars.','彼らは車を生産している。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['produce']),
('product','プロダクト','製品','This is a new product.','これは新製品だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['product']),
('production','プロダクション','生産、制作','Production is increasing.','生産が増えている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['production']),
('profession','プロフェッション','職業、専門職','What is your profession?','あなたの職業は何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['profession']),
('professional','プロフェッショナル','プロの、専門的な','He is a professional player.','彼はプロの選手だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['professional']),
('professor','プロフェッサー','教授','He is a university professor.','彼は大学教授だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['professor']),
('program','プログラム','計画、番組','I like this TV program.','このテレビ番組が好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['program']),
('progress','プログレス','前進、進歩','Make progress in English.','英語が進歩する。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['progress']),
('project','プロジェクト','計画、事業','We have a new project.','新しいプロジェクトがある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['project']),
('promise','プロミス','約束、約束する','Keep your promise.','約束を守りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['promise']),
('promote','プロモート','促進する、昇進させる','Promote healthy living.','健康な生活を促進しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['promote']),
('pronounce','プロナウンス','発音する','How do you pronounce it?','それをどう発音しますか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pronounce']),
('proof','プルーフ','証拠','Do you have any proof?','何か証拠はありますか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['proof']),
('proper','プロパー','適切な','Use proper English.','適切な英語を使いなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['proper']),
('property','プロパティ','財産、所有地','Respect private property.','私有財産を尊重しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['property']),
('protect','プロテクト','守る','Protect the environment.','環境を守りなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['protect']),
('proud','プラウド','誇りに思って','I am proud of you.','あなたのことを誇りに思う。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['proud']),
('prove','プルーヴ','証明する','Prove your ability.','自分の能力を証明しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['prove']),
('provide','プロヴァイド','提供する、供給する','They provide free food.','彼らは無料の食事を提供している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['provide']),
('public','パブリック','公共の、公の','It is a public library.','それは公共図書館だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['public']),
('publish','パブリッシュ','出版する','He published a new book.','彼は新刊を出版した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['publish']),
('pull','プル','引く','Pull the door.','ドアを引きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pull']),
('punish','パニッシュ','罰する','Don''t punish him.','彼を罰してはいけない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['punish']),
('pupil','ピューピル','生徒','He is a good pupil.','彼は良い生徒だ。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['pupil','student']),
('purchase','パーチェス','購入する、購入','I purchased it online.','それをオンラインで購入した。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['purchase','buy']),
('pure','ピュア','純粋な','It is pure water.','それは純粋な水だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pure']),
('purple','パープル','紫色','She wears a purple dress.','彼女は紫のドレスを着ている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['purple']),
('purpose','パーパス','目的','What is the purpose?','目的は何ですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['purpose']),
('push','プッシュ','押す','Push the button.','ボタンを押しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['push']),
('put','プット','置く','Put it on the desk.','それを机の上に置きなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['put']),
('puzzle','パズル','パズル、謎','I love this puzzle.','このパズルが大好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['puzzle']),
('in part','インパート','部分的に','It is true in part.','それは部分的には真実だ。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['in part']),
('on the other hand','オンザアザーハンド','他方では','On the other hand, it is expensive.','他方では、それは高い。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['on the other hand']),
('out of','アウトオブ','〜から外へ','Get out of here.','ここから出ていけ。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['out of']),
('over and over','オーバーアンドオーバー','何度も繰り返して','Read it over and over.','何度も読み返しなさい。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['over and over']),
('pass away','パスアウェイ','亡くなる','He passed away yesterday.','彼は昨日亡くなった。','中3','難関','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['pass away','die']),
('pick up','ピックアップ','拾い上げる、車で迎えに行く','Pick up the pen.','ペンを拾い上げなさい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['pick up']),
('point out','ポイントアウト','指摘する','He pointed out the mistake.','彼はミスを指摘した。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['point out']),
('put away','プットアウェイ','片付ける','Put your toys away.','おもちゃを片付けなさい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['put away']),
('put off','プットオフ','延期する','Don''t put it off.','それを延期してはいけない。','中3','難関','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['put off','postpone']),
('quality','クオリティ','質','This has high quality.','これは質が高い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['quality']),
('quantity','クオンティティ','量','Quality is better than quantity.','量は質に勝る（質が量より大事だ）。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['quantity']),
('queen','クイーン','女王','She is the queen.','彼女が女王だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['queen']),
('question','クエスチョン','質問、問題','I have a question.','質問があります。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['question']),
('quick','クイック','速い、迅速な','Give me a quick answer.','すぐに答えをちょうだい。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['quick','fast']),
('quickly','クイックリー','素早く','Run quickly.','素早く走りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['quickly']),
('quiet','クワイエット','静かな','Please be quiet.','静かにしてください。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['quiet']),
('quite','クワイト','かなり、完全に','It is quite cold today.','今日はかなり寒い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['quite']),
('race','レース','競争、人種','I won the race.','私はレースに勝った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['race']),
('radio','ラジオ','ラジオ','I listen to the radio.','ラジオを聴く。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['radio']),
('railway','レイルウェイ','鉄道','I work for the railway.','鉄道会社で働いている。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['railway','railroad']),
('rain','レイン','雨','I don''t like rain.','雨は好きではない。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['rain']),
('rainy','レイニー','雨の多い','It is a rainy day.','今日は雨の日だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['rainy']),
('raise','レイズ','上げる、育てる','Raise your hand.','手を挙げなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['raise']),
('range','レンジ','範囲、列','The range is wide.','範囲が広い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['range']),
('rank','ランク','階級、順位','He holds a high rank.','彼は高い地位にある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rank']),
('rapid','ラピッド','急速な','There was a rapid change.','急速な変化があった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rapid']),
('rare','レア','まれな、珍しい','It is a rare book.','それは珍しい本だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rare']),
('rate','レート','割合、速度','The rate is increasing.','その割合が増加している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rate']),
('rather','ラザー','むしろ、かなり','It is rather cold.','むしろ寒い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rather']),
('raw','ロー','生の、未加工の','I don''t eat raw fish.','生の魚は食べない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['raw']),
('reach','リーチ','到着する、手を伸ばす','We reached the top.','頂上に到着した。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['reach','arrive at']),
('read','リード','読む','I like to read books.','本を読むのが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['read']),
('ready','レディ','準備ができた','Are you ready?','準備はいいですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ready']),
('real','リアル','現実の、本物の','It is a real story.','それは実話だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['real']),
('realize','リアライズ','気づく、実現する','I realized my mistake.','間違いに気づいた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['realize']),
('really','リアリー','本当に','It is really good.','それは本当に良い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['really']),
('reason','リーズン','理由','What is the reason?','理由は何ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['reason']),
('reasonable','リーズナブル','妥当な、手頃な','The price is reasonable.','価格が手頃だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['reasonable']),
('recall','リコール','思い出す','I cannot recall his name.','彼の名前を思い出せない。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['recall','remember']),
('receipt','リシート','領収書','Please give me a receipt.','領収書をください。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['receipt']),
('receive','レシーヴ','受け取る','I received your letter.','手紙を受け取った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['receive']),
('recent','リーセント','最近の','These are recent events.','これらは最近の出来事だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['recent']),
('recently','リーセントリー','最近','I have been busy recently.','最近忙しい。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['recently','lately']),
('recipe','レシピ','調理法、秘訣','I need a cake recipe.','ケーキのレシピが必要だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['recipe']),
('recognize','レコグナイズ','認める、見分ける','I recognized him.','彼だとわかった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['recognize']),
('recommend','レコメンド','勧める','I recommend this book.','この本を勧める。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['recommend']),
('record','レコード','記録、記録する','He set a new record.','彼は新しい記録を作った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['record']),
('recover','リカヴァー','回復する','He recovered from the illness.','彼は病気から回復した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['recover']),
('recycle','リサイクル','再生利用する','Recycle your paper.','紙をリサイクルしなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['recycle']),
('reduce','リデュース','減らす','Reduce the use of plastic.','プラスチックの使用を減らしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['reduce']),
('refer','リファー','言及する、参照する','Refer to the page.','そのページを参照しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['refer']),
('reference','レファレンス','参照、言及','Look at the reference.','参照先を見なさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['reference']),
('reflect','リフレクト','反射する、反映する','The mirror reflects light.','鏡が光を反射する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['reflect']),
('refuse','リフューズ','断る','He refused the offer.','彼は申し出を断った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['refuse']),
('regard','リガード','みなす、敬意','I regard him as a friend.','彼を友達とみなしている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['regard']),
('region','リージョン','地域','This is a cold region.','ここは寒い地域だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['region']),
('register','レジスター','登録する','Register for the class.','そのクラスに登録しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['register']),
('regret','リグレット','後悔する','I regret my decision.','決断を後悔している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['regret']),
('regular','レギュラー','定期的な、規則正しい','I have regular habits.','規則正しい習慣がある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['regular']),
('reject','リジェクト','拒絶する','They rejected the plan.','彼らはその計画を拒絶した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['reject']),
('relate','リレイト','関係づける','Are these events related?','これらの出来事は関係していますか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['relate']),
('relation','リレーション','関係','What is the relation?','どんな関係ですか。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['relation','relationship']),
('relationship','リレーションシップ','関係','They have a good relationship.','彼らは良い関係にある。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['relationship','relation']),
('relative','レラティヴ','親戚、相対的な','He is my relative.','彼は私の親戚だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['relative']),
('relax','リラックス','くつろぐ、休む','Please relax here.','ここでくつろいでください。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['relax']),
('release','リリース','解放する、発表する','Release the bird.','その鳥を逃がしてやりなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['release']),
('relevant','レレヴァント','関連のある','That is not relevant.','それは関連がない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['relevant']),
('reliable','リライアブル','信頼できる','He is a reliable person.','彼は信頼できる人だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['reliable']),
('relief','リリーフ','安心、安らぎ','It was a great relief.','それは大きな安心感だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['relief']),
('relieve','リリーヴ','軽減する、安心させる','It relieved my pain.','痛みが和らいだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['relieve']),
('religion','リリジョン','宗教','They have a religion.','彼らには宗教がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['religion']),
('rely','リライ','頼る','I rely on you.','あなたを頼りにしている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rely']),
('remain','リメイン','残る、〜のままである','He remained silent.','彼は黙ったままだった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['remain']),
('remark','リマーク','述べる、意見','He remarked on the weather.','彼は天気について述べた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['remark']),
('remember','リメンバー','覚えている、思い出す','I remember you.','あなたを覚えています。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['remember']),
('remind','リマインド','思い出させる','Remind me later.','後で思い出させて。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['remind']),
('remote','リモート','遠い、離れた','It is a remote village.','それは人里離れた村だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['remote']),
('remove','リムーブ','取り除く','Remove the hat.','帽子を取り除きなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['remove']),
('renew','リニュー','更新する','Renew your passport.','パスポートを更新しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['renew']),
('rent','レント','賃貸料、借りる','I rent this room.','この部屋を借りている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['rent']),
('repair','リペア','修理する','Can you repair this?','これを修理できますか。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['repair','fix']),
('repeat','リピート','繰り返す','Please repeat it.','繰り返してください。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['repeat']),
('replace','リプレイス','置き換える','Replace the old one.','古いものを置き換えなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['replace']),
('reply','リプライ','返事をする','He replied quickly.','彼はすぐに返事をした。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['reply','answer']),
('report','レポート','報告する、報告書','Write a report.','報告書を書きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['report']),
('represent','リプレゼント','代表する','He represents our school.','彼は私たちの学校を代表している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['represent']),
('representative','リプレゼンタティヴ','代表者','He is our representative.','彼が私たちの代表者だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['representative']),
('reputation','レピュテーション','評判','He has a good reputation.','彼は評判が良い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['reputation']),
('request','リクエスト','要請、頼む','It is a special request.','特別な要請だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['request']),
('require','リクワイア','必要とする','It requires care.','それには注意が必要だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['require']),
('requirement','リクワイアメント','必要な条件、要求','Meet the requirements.','要求を満たしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['requirement']),
('rescue','レスキュー','救助する','They rescued the boy.','彼らはその少年を救助した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['rescue']),
('research','リサーチ','研究、調査','Do some research.','少し調査をしなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['research']),
('resemble','リゼンブル','似ている','He resembles his father.','彼は父親に似ている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['resemble']),
('reserve','リザーヴ','予約する、蓄える','I reserved a table.','テーブルを予約した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['reserve']),
('resident','レジデント','居住者','He is a local resident.','彼は地元の居住者だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['resident']),
('resist','レジスト','抵抗する','Do not resist.','抵抗してはいけない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['resist']),
('respect','リスペクト','尊敬する、敬意','I respect my teacher.','先生を尊敬している。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['respect']),
('respond','レスポンド','反応する、応じる','He did not respond.','彼は反応しなかった。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['respond','reply']),
('response','レスポンス','応答、反応','I got no response.','返答がなかった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['response']),
('responsibility','レスポンシビリティ','責任','It is your responsibility.','それはあなたの責任だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['responsibility']),
('responsible','レスポンシブル','責任がある','Who is responsible?','誰が責任者ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['responsible']),
('rest','レスト','休息、残り','Take a rest.','休息をとりなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['rest']),
('restaurant','レストラン','レストラン','Let''s go to a restaurant.','レストランへ行こう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['restaurant']),
('result','リザルト','結果','What is the result?','結果は何ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['result']),
('retire','リタイア','引退する','He will retire soon.','彼はもうすぐ引退する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['retire']),
('reveal','リヴィール','明らかにする','She revealed the truth.','彼女は真実を明らかにした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['reveal']),
('review','レビュー','復習、批評','Review your notes.','ノートを復習しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['review']),
('revise','リヴァイズ','修正する、改訂する','Revise your plan.','計画を修正しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['revise']),
('revolution','レヴォリューション','革命','There was a revolution.','革命があった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['revolution']),
('reward','リワード','報酬、報いる','It is a good reward.','それは良い報酬だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['reward']),
('rhythm','リズム','リズム','Follow the rhythm.','リズムに従いなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['rhythm']),
('rice','ライス','米、ご飯','I like eating rice.','ご飯を食べるのが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['rice']),
('rich','リッチ','裕福な、豊かな','He is very rich.','彼はとても裕福だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['rich']),
('rid','リッド','取り除く','Get rid of it.','それを取り除きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rid']),
('ride','ライド','乗る','Can you ride a bike?','自転車に乗れますか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ride']),
('right','ライト','正しい、右、権利','You are right.','君は正しい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['right']),
('ring','リング','鳴る、指輪','The phone is ringing.','電話が鳴っている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ring']),
('rip','リップ','引き裂く','He ripped the paper.','彼は紙を引き裂いた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rip']),
('rise','ライズ','昇る、上がる','The sun rises in the east.','太陽は東から昇る。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['rise']),
('risk','リスク','危険、リスク','It is a high risk.','それは高いリスクだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['risk']),
('rival','ライヴァル','競争相手','He is my rival.','彼は私のライバルだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rival']),
('river','リバー','川','The river is wide.','その川は広い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['river']),
('road','ロード','道路','The road is very long.','その道はとても長い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['road']),
('roar','ロアー','ほえる、とどろく','The lion roared.','ライオンがほえた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['roar']),
('rob','ロブ','強奪する','They robbed the bank.','彼らは銀行を襲った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rob']),
('robot','ロボット','ロボット','He built a robot.','彼はロボットを作った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['robot']),
('rock','ロック','岩','Sit on the rock.','岩の上に座りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['rock']),
('role','ロール','役割','What is your role?','あなたの役割は何ですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['role']),
('roll','ロール','転がる、巻く','Roll the ball.','ボールを転がしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['roll']),
('romantic','ロマンティック','ロマンチックな','It is a romantic place.','それはロマンチックな場所だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['romantic']),
('roof','ルーフ','屋根','The cat is on the roof.','猫が屋根の上にいる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['roof']),
('room','ルーム','部屋','This is my room.','これが私の部屋だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['room']),
('root','ルート','根、根本','The tree has deep roots.','その木は深い根を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['root']),
('rope','ロープ','なわ、ロープ','Use this rope.','このロープを使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['rope']),
('rose','ローズ','バラ','The rose is beautiful.','バラが美しい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['rose']),
('rough','ラフ','粗い、大まかな','The surface is rough.','表面が粗い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rough']),
('round','ラウンド','丸い','The earth is round.','地球は丸い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['round']),
('route','ルート','経路、道筋','What is the best route?','最適な経路は何ですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['route']),
('routine','ルーティン','日課、ルーティン','It is my daily routine.','それが私の日課だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['routine']),
('row','ロウ','列、こぐ','Sit in the front row.','前列に座りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['row']),
('royal','ロイヤル','王室の、豪華な','It is a royal palace.','それは王宮だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['royal']),
('rub','ラブ','こする','Rub your hands.','手をこすりなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rub']),
('rubber','ラバー','ゴム','It is made of rubber.','それはゴムでできている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['rubber']),
('rude','ルード','失礼な、無礼な','Don''t be rude.','失礼なことをしてはいけない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rude']),
('rug','ラグ','敷物','I bought a new rug.','新しい敷物を買った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['rug']),
('ruin','ルイン','破壊する、台無しにする','The rain ruined our plans.','雨が私たちの計画を台無しにした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ruin']),
('rule','ルール','規則、支配する','Follow the school rules.','校則に従いなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['rule']),
('ruler','ルーラー','定規、支配者','Use a ruler.','定規を使いなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ruler']),
('run','ラン','走る','I run in the park.','公園で走る。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['run']),
('runner','ランナー','走者','He is a fast runner.','彼は足が速い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['runner']),
('rural','ルーラル','田舎の','He lives in a rural area.','彼は田舎に住んでいる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['rural']),
('rush','ラッシュ','急ぐ、突進する','Don''t rush me.','私を急かさないで。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['rush']),
('get rid of','ゲットリドオブ','〜を取り除く','Get rid of this trash.','このゴミを捨てなさい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['get rid of']),
('give off','ギブオフ','〜を発する','The fire gives off light.','火は光を発する。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['give off']),
('give out','ギブアウト','配る','Give out these papers.','これらの書類を配りなさい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['give out']),
('go on','ゴーン','〜し続ける','He went on talking.','彼は話し続けた。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['go on']),
('hand in','ハンドイン','提出する','Hand in your report.','レポートを提出しなさい。','中3','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['hand in','submit']),
('hand out','ハンドアウト','配る','Hand out the books.','本を配りなさい。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['hand out']),
('have a good time','ハブアグッドタイム','楽しく過ごす','Have a good time!','楽しんでね！','中1','基礎','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['have a good time','enjoy oneself']),
('have nothing to do with','ハブナッシングトゥドゥウィズ','〜と全く関係がない','It has nothing to do with me.','それは私とは全く関係がない。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['have nothing to do with']),
('in a hurry','インアハリー','急いで','I am in a hurry.','急いでいるのです。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['in a hurry']),
('in public','インパブリック','人前で','Don''t speak in public.','人前で話してはいけない。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['in public']),
('make a decision','メイクアディシジョン','決心する','Make a decision now.','今、決心しなさい。','中3','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['make a decision','decide']),
('make a mistake','メイクアミステイク','間違いをする','Don''t make a mistake.','間違いをしないで。','中1','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['make a mistake']),
('make sure','メイクシュア','確認する、確かめる','Make sure to lock it.','必ず鍵をかけなさい。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['make sure']),
('pass on','パソン','伝える','Pass on the message.','伝言を伝えなさい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['pass on']),
('put out','プットアウト','火を消す','Put out the fire.','火を消しなさい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['put out']),
('safe','セーフ','安全な','Are you safe here?','ここで安全ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['safe']),
('safety','セーフティ','安全','Safety first.','安全第一。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['safety']),
('sail','セイル','航海する、帆','He sailed across the sea.','彼は海を航海した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['sail']),
('salary','サラリー','給料','He earns a high salary.','彼は高い給料をもらっている。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['salary','wage']),
('sale','セール','販売、安売り','The store is having a sale.','その店はセール中だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['sale']),
('salt','ソルト','塩','Pass the salt, please.','塩を取ってください。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['salt']),
('same','セイム','同じ','We have the same book.','私たちは同じ本を持っている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['same']),
('sample','サンプル','標本、見本','Try this free sample.','この無料サンプルを試して。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['sample']),
('sand','サンド','砂','The sand is very hot.','砂がとても熱い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['sand']),
('satisfy','サティスファイ','満足させる','Nothing satisfies him.','何事も彼を満足させられない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['satisfy']),
('save','セイヴ','救う、節約する、保存する','Save water.','水を節約しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['save']),
('say','セイ','言う','What did you say?','何と言いましたか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['say']),
('scale','スケール','規模、尺度','It is a large scale project.','それは大規模な計画だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['scale']),
('scare','スケア','怖がらせる','Don''t scare me.','私を怖がらせないで。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['scare','frighten']),
('scene','シーン','場面、景色','It was a sad scene.','それは悲しい場面だった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['scene']),
('schedule','スケジュール','予定','Check your schedule.','予定を確認しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['schedule']),
('school','スクール','学校','I go to school by bus.','バスで学校へ行く。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['school']),
('science','サイエンス','科学','I like science class.','理科（科学）の授業が好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['science']),
('scientist','サイエンティスト','科学者','She is a famous scientist.','彼女は有名な科学者だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['scientist']),
('score','スコア','得点','What is your score?','あなたの得点は？','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['score']),
('screen','スクリーン','画面、スクリーン','Look at the screen.','画面を見なさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['screen']),
('sea','シー','海','The sea is very blue.','海はとても青い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sea']),
('search','サーチ','捜索する、探す','Search for the truth.','真実を探しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['search']),
('season','シーズン','季節','Summer is my favorite season.','夏が一番好きな季節だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['season']),
('seat','シート','座席','Take your seat.','座席に着きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['seat']),
('second','セカンド','第2の、秒','Wait a second.','1秒待って。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['second']),
('secret','シークレット','秘密','Can you keep a secret?','秘密を守れますか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['secret']),
('section','セクション','部分、部門','Read this section.','この部分を読みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['section']),
('see','シー','見る、会う','I see a bird.','鳥が見える。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['see']),
('seed','シード','種','Plant the seeds.','種を植えなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['seed']),
('seem','シーム','〜のように見える','You seem happy.','幸せそうに見える。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['seem']),
('seldom','セルダム','めったに〜ない','He seldom comes here.','彼はめったにここへ来ない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['seldom']),
('select','セレクト','選ぶ','Select the best one.','最も良いものを選びなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['select','choose']),
('self','セルフ','自身','He likes self study.','彼は独学が好きだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['self']),
('sell','セル','売る','They sell fresh fruit.','彼らは新鮮な果物を売っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['sell']),
('send','センド','送る','I sent a letter.','手紙を送った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['send']),
('sense','センス','感覚、良識','He has a good sense of humor.','彼はユーモアのセンスがある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['sense']),
('sensitive','センシティブ','敏感な','She is very sensitive.','彼女はとても敏感だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['sensitive']),
('sentence','センテンス','文','Write a long sentence.','長い文を書きなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sentence']),
('separate','セパレート','分ける、別々の','They live in separate houses.','彼らは別の家に住んでいる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['separate']),
('series','シリーズ','一連のもの','It is a book series.','それはシリーズ本だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['series']),
('serious','シリアス','真剣な、重大な','This is a serious problem.','これは重大な問題だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['serious']),
('serve','サーヴ','仕える、出す（食事を）','They served dinner.','彼らは夕食を出した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['serve']),
('service','サービス','奉仕、業務','The service is good here.','ここのサービスは良い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['service']),
('set','セット','置く、決める','Set the clock.','時計を合わせなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['set']),
('settle','セトル','解決する、落ち着く','They settled the argument.','彼らは議論を解決した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['settle']),
('several','セヴラル','いくつかの','I have several questions.','いくつか質問があります。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['several']),
('severe','シヴィア','厳しい、激しい','It was a severe winter.','厳しい冬だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['severe']),
('sex','セックス','性別','Write your name and sex.','名前と性別を書きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['sex','gender']),
('shadow','シャドウ','影','The shadow is long.','影が長い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['shadow']),
('shake','シェイク','振る、震える','Shake the bottle.','ボトルを振りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['shake']),
('shall','シャル','〜しましょうか','Shall we dance?','踊りましょうか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['shall']),
('shape','シェイプ','形','What is the shape?','形は何ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['shape']),
('share','シェア','分かち合う、共有する','Share it with your friend.','友達と分かち合いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['share']),
('sharp','シャープ','鋭い','The knife is sharp.','そのナイフは鋭い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['sharp']),
('she','シー','彼女は','She is my sister.','彼女は私の姉（妹）だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['she']),
('sheep','シープ','羊','I saw many sheep.','たくさんの羊を見た。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['sheep']),
('sheet','シート','一枚の紙、シーツ','Give me a sheet of paper.','紙を1枚ちょうだい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['sheet']),
('shelf','シェルフ','棚','Put it on the shelf.','それを棚に置きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['shelf']),
('shell','シェル','貝殻','I found a shell.','貝殻を見つけた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['shell']),
('shift','シフト','移動させる、交代','Shift your position.','位置を移動しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['shift']),
('shine','シャイン','輝く','The sun shines brightly.','太陽が明るく輝く。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['shine']),
('ship','シップ','船','The ship is very large.','その船はとても大きい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ship']),
('shirt','シャツ','シャツ','I bought a new shirt.','新しいシャツを買った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['shirt']),
('shock','ショック','衝撃','It was a big shock.','それは大きな衝撃だった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['shock']),
('shoe','シュー','靴','My shoes are new.','私の靴は新しい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['shoe']),
('shoot','シュート','撃つ、撮影する','He shot a photo.','彼は写真を撮った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['shoot']),
('shop','ショップ','店','I went to the shop.','店へ行った。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['shop','store']),
('short','ショート','短い','The story is short.','その話は短い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['short']),
('should','シュッド','〜すべきである','You should study hard.','一生懸命勉強すべきだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['should']),
('shoulder','ショルダー','肩','He put a hand on my shoulder.','彼は私の肩に手を置いた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['shoulder']),
('shout','シャウト','叫ぶ','Don''t shout.','叫んではいけない。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['shout','yell']),
('show','ショウ','見せる、示す','Show me the way.','道を教えて（示して）。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['show']),
('shut','シャット','閉める','Shut the door.','ドアを閉めなさい。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['shut','close']),
('sick','シック','病気の','I am sick today.','今日は気分が悪い（病気だ）。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['sick','ill']),
('side','サイド','側、面','Choose a side.','どちらかの側を選びなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['side']),
('sight','サイト','視力、光景','It was a beautiful sight.','それは美しい光景だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['sight']),
('sign','サイン','合図、署名する','He gave me a sign.','彼は合図をくれた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['sign']),
('signal','シグナル','合図、信号','The signal turned red.','信号が赤に変わった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['signal']),
('significance','シグニフィカンス','重要性','It has great significance.','それは大きな重要性がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['significance']),
('significant','シグニフィカント','重要な、意味のある','It is a significant change.','それは重要な変化だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['significant']),
('silence','サイレンス','沈黙','There was silence.','沈黙があった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['silence']),
('silent','サイレント','沈黙した','Keep silent.','静かにしていなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['silent']),
('silver','シルバー','銀、銀色の','I like silver.','銀が好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['silver']),
('similar','シミラー','類似した','They are similar.','それらは似ている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['similar']),
('simple','シンプル','単純な、簡単な','The rule is simple.','その規則は単純だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['simple']),
('simply','シンプリー','単に、簡単に','It is simply wrong.','それは単に間違っている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['simply']),
('since','シンス','〜以来、〜なので','I have lived here since then.','それ以来ずっとここに住んでいる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['since']),
('sing','シング','歌う','She sings well.','彼女は歌がうまい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sing']),
('singer','シンガー','歌手','He is a great singer.','彼は偉大な歌手だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['singer']),
('single','シングル','単一の、独身の','Is he single?','彼は独身ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['single']),
('sink','シンク','沈む、流し台','The ship sank.','その船は沈んだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['sink']),
('sir','サー','〜様、紳士','Yes, sir.','はい、旦那様（かしこまりました）。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sir']),
('sister','シスター','姉妹','I have two sisters.','姉妹が2人います。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sister']),
('sit','シット','座る','Please sit down.','座ってください。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sit']),
('site','サイト','敷地、場所、ウェブサイト','Visit our site.','私たちのサイトを訪問して。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['site']),
('situation','シチュエーション','状況','It is a difficult situation.','それは困難な状況だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['situation']),
('size','サイズ','大きさ、サイズ','What is your size?','サイズは何ですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['size']),
('skill','スキル','技術、技能','He has great skill.','彼は素晴らしい技術を持っている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['skill']),
('skin','スキン','肌、皮','She has soft skin.','彼女は肌が柔らかい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['skin']),
('sky','スカイ','空','The sky is clear.','空が晴れている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sky']),
('sleep','スリープ','眠る','I want to sleep.','眠りたい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sleep']),
('slide','スライド','すべる','The door slides.','そのドアはスライド式だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['slide']),
('slight','スライト','わずかな','There is a slight change.','わずかな変化がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['slight']),
('slightly','スライトリー','わずかに','It is slightly larger.','わずかに大きい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['slightly']),
('slow','スロー','遅い','The bus is slow.','そのバスは遅い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['slow']),
('slowly','スローリー','ゆっくりと','Speak slowly.','ゆっくり話しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['slowly']),
('small','スモール','小さい','It is a small house.','それは小さな家だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['small']),
('smart','スマート','賢い、頭が良い','He is a smart student.','彼は賢い生徒だ。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['smart','clever']),
('smell','スメル','におう、におい','It smells good.','良いにおいがする。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['smell']),
('smile','スマイル','ほほえむ、笑顔','She has a nice smile.','彼女は素敵な笑顔だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['smile']),
('smoke','スモーク','煙、吸う','Don''t smoke here.','ここでたばこを吸わないで。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['smoke']),
('smooth','スムーズ','滑らかな、順調な','The road is smooth.','その道は滑らかだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['smooth']),
('snake','スネーク','ヘビ','I saw a snake.','ヘビを見た。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['snake']),
('snow','スノー','雪','Do you like snow?','雪は好きですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['snow']),
('snowy','スノーウィ','雪の多い','It is a snowy day.','今日は雪の日だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['snowy']),
('so','ソー','だから、とても','I am so happy.','とても幸せだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['so']),
('soap','ソープ','石けん','Wash with soap.','石けんで洗いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['soap']),
('social','ソーシャル','社会の','It is a social problem.','それは社会問題だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['social']),
('society','ソサエティ','社会','We live in a society.','私たちは社会に生きている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['society']),
('sock','ソック','靴下','I lost a sock.','靴下を片方なくした。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['sock']),
('soft','ソフト','柔らかい','The bed is soft.','そのベッドは柔らかい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['soft']),
('soil','ソイル','土','The soil is good here.','ここの土は良い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['soil']),
('soldier','ソルジャー','兵士','He is a soldier.','彼は兵士だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['soldier']),
('solid','ソリッド','固体の、固い','It is a solid wall.','それは固い壁だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['solid']),
('solution','ソリューション','解決策','What is the solution?','解決策は何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['solution']),
('solve','ソルヴ','解決する','Solve this problem.','この問題を解決しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['solve']),
('some','サム','いくつかの、いくらかの','I have some ideas.','いくつか考えがある。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['some']),
('somebody','サムバディ','誰か','Somebody is calling.','誰か呼んでいる。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['somebody','someone']),
('someone','サムワン','誰か','Someone is here.','誰かここにいます。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['someone','somebody']),
('something','サムシング','何か','I want something to drink.','何か飲むものがほしい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['something']),
('sometimes','サムタイムズ','時々','I sometimes go there.','時々そこへ行く。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['sometimes']),
('somewhere','サムウェア','どこかに','I want to go somewhere.','どこかへ行きたい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['somewhere']),
('son','サン','息子','He is my son.','彼は私の息子だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['son']),
('song','ソング','歌','I like this song.','この歌が好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['song']),
('soon','スーン','すぐに','I will be home soon.','すぐに帰る。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['soon']),
('sorry','ソリー','残念に思う、すまない','I am sorry.','すみません。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sorry']),
('sort','ソート','種類','What sort of music?','どんな種類の音楽？','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['sort','kind']),
('soul','ソウル','魂','It touches my soul.','それは私の魂に触れる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['soul']),
('sound','サウンド','音、〜に聞こえる','That sounds good.','それは良さそう（良いと聞こえる）だね。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['sound']),
('soup','スープ','スープ','The soup is hot.','そのスープは熱い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['soup']),
('source','ソース','源、情報源','What is the source?','情報源は何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['source']),
('south','サウス','南、南の','Go south from here.','ここから南へ行きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['south']),
('space','スペース','空間、宇宙','There is no space here.','ここには場所がない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['space']),
('speak','スピーク','話す','Can you speak English?','英語を話せますか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['speak']),
('speaker','スピーカー','話者、スピーカー','He is a good speaker.','彼は話し上手だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['speaker']),
('special','スペシャル','特別な','This is a special day.','今日は特別な日だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['special']),
('specific','スペシフィック','具体的な、特定の','Give a specific example.','具体的な例を挙げなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['specific']),
('speech','スピーチ','演説','He gave a speech.','彼は演説をした。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['speech']),
('speed','スピード','速度','Reduce your speed.','速度を落としなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['speed']),
('spell','スペル','つづる','How do you spell it?','どうやってつづりますか。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['spell']),
('spend','スペンド','（時間やお金を）費やす','I spend time with him.','彼と時間を過ごす。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['spend']),
('spirit','スピリット','精神、魂','He has a fighting spirit.','彼は闘志を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['spirit']),
('split','スプリット','割る、裂く','Split the wood.','木を割りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['split']),
('sport','スポーツ','スポーツ','What sport do you like?','どのスポーツが好きですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sport']),
('spot','スポット','点、場所','I found a good spot.','良い場所を見つけた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['spot']),
('spread','スプレッド','広げる','Spread the news.','そのニュースを広めなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['spread']),
('spring','スプリング','春、ばね','Spring is coming.','春が来ている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['spring']),
('square','スクエア','正方形、広場','Meet at the town square.','町の広場で会いましょう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['square']),
('staff','スタッフ','職員、スタッフ','Ask the staff.','職員に尋ねなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['staff']),
('stage','ステージ','舞台、段階','He is on the stage.','彼は舞台の上にいる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['stage']),
('stair','ステア','階段','Go up the stairs.','階段を上がりなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['stair']),
('stand','スタンド','立つ、我慢する','Stand in a circle.','円になって立ちなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['stand']),
('star','スター','星','Look at the stars.','星を見なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['star']),
('stare','ステア','じっと見る','Don''t stare at me.','じっと見つめないで。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['stare']),
('start','スタート','始める','Start your work.','仕事を始めなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['start']),
('state','ステイト','州、状態、述べる','He stated his opinion.','彼は意見を述べた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['state']),
('statement','ステイトメント','声明、陳述','Read his statement.','彼の声明を読みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['statement']),
('station','ステーション','駅','Meet me at the station.','駅で会いましょう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['station']),
('statistic','スタティスティック','統計','Look at the statistics.','統計データを見なさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['statistic']),
('status','ステイタス','地位、状態','He has high status.','彼は高い地位にある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['status']),
('stay','ステイ','滞在する、とどまる','Stay here.','ここにいなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['stay']),
('steady','ステディ','安定した','He has a steady job.','彼は安定した仕事を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['steady']),
('steal','スティール','盗む','Don''t steal.','盗んではいけない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['steal']),
('steam','スティーム','蒸気','There is a lot of steam.','蒸気がたくさん出ている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['steam']),
('steel','スティール','鋼鉄','It is made of steel.','それは鋼鉄製だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['steel']),
('steep','スティープ','険しい','The hill is steep.','その丘は険しい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['steep']),
('step','ステップ','歩み、段階','Take a step forward.','前に一歩出なさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['step']),
('stick','スティック','棒、くっつく','It sticks to the wall.','壁にくっつく。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['stick']),
('still','スティル','まだ、静かに','Are you still here?','まだここにいるのですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['still']),
('stomach','ストマック','胃','I have a stomach ache.','胃が痛い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['stomach']),
('stone','ストーン','石','He threw a stone.','彼は石を投げた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['stone']),
('stop','ストップ','止める','Stop talking.','話すのをやめなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['stop']),
('storage','ストレージ','貯蔵、保管','We need more storage.','もっと保管場所が必要だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['storage']),
('store','ストア','店','Go to the store.','店へ行きなさい。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['store','shop']),
('storm','ストーム','嵐','A storm is coming.','嵐が来ている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['storm']),
('story','ストーリー','話、物語','Tell me a story.','話をして。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['story']),
('straight','ストレイト','まっすぐな','Go straight.','まっすぐ行きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['straight']),
('strange','ストレンジ','奇妙な','It is a strange story.','それは奇妙な話だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['strange']),
('stranger','ストレンジャー','見知らぬ人','Don''t talk to strangers.','知らない人に話しかけてはいけない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['stranger']),
('strategy','ストラテジー','戦略','What is your strategy?','あなたの戦略は何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['strategy']),
('stream','ストリーム','小川、流れ','Water flows in the stream.','小川に水が流れている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['stream']),
('street','ストリート','通り','Cross the street.','通りを渡りなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['street']),
('strength','ストレングス','力、強さ','He has great strength.','彼は大きな力を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['strength']),
('strengthen','ストレングスン','強くする','Strengthen your body.','体を強くしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['strengthen']),
('stress','ストレス','ストレス、強調','Don''t have too much stress.','ストレスをためすぎないで。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['stress']),
('strict','ストリクト','厳しい','He is a strict teacher.','彼は厳しい先生だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['strict']),
('strike','ストライク','打つ、攻撃する','The clock struck twelve.','時計が12時を打った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['strike']),
('string','ストリング','ひも、弦','Tie it with a string.','ひもで縛りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['string']),
('strip','ストリップ','取り去る、細長い一片','Strip the bark.','樹皮をはぎ取りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['strip']),
('strong','ストロング','強い','He is a strong boy.','彼は強い少年だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['strong']),
('structure','ストラクチャー','構造','The structure is simple.','その構造は単純だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['structure']),
('struggle','ストラグル','苦闘する、もがく','They struggled for success.','彼らは成功のために苦闘した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['struggle']),
('student','スチューデント','生徒、学生','I am a student.','私は学生です。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['student']),
('study','スタディ','勉強する、研究','Study for the test.','試験のために勉強しなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['study']),
('stuff','スタッフ','詰め込む、もの','He stuffs his bag.','彼はかばんに詰め込む。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['stuff']),
('style','スタイル','型、様式','I like his writing style.','彼の文章スタイルが好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['style']),
('subject','サブジェクト','主題、教科','What is your favorite subject?','好きな教科は何ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['subject']),
('submit','サブミット','提出する','Submit your report.','レポートを提出しなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['submit','hand in']),
('substance','サブスタンス','物質','It is a new substance.','それは新しい物質だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['substance']),
('succeed','サクシード','成功する、継承する','He succeeded in his work.','彼は仕事で成功した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['succeed']),
('success','サクセス','成功','Success is not easy.','成功は簡単ではない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['success']),
('successful','サクセスフル','成功した','He is a successful man.','彼は成功した人だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['successful']),
('such','サッチ','そのような','I have never seen such a thing.','そんなことは見たことがない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['such']),
('sudden','サドン','突然の','It was a sudden change.','突然の変化だった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['sudden']),
('suddenly','サドゥンリー','突然に','He suddenly left.','彼は突然去った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['suddenly']),
('suffer','サファー','苦しむ','He suffered from the cold.','彼は寒さに苦しんだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['suffer']),
('sugar','シュガー','砂糖','Add some sugar.','砂糖を加えなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sugar']),
('suggest','サジェスト','提案する','I suggest we go home.','帰宅することを提案します。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['suggest']),
('suggestion','サジェスチョン','提案','Do you have any suggestions?','何か提案はありますか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['suggestion']),
('suit','スーツ','スーツ、適する','That color suits you.','その色はあなたに似合う。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['suit']),
('suitable','スータブル','適した','It is a suitable place.','それは適した場所だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['suitable']),
('sum','サム','合計、金額','What is the sum?','合計は何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['sum']),
('summary','サマリー','要約','Write a brief summary.','短い要約を書きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['summary']),
('summer','サマー','夏','I like summer.','夏が好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['summer']),
('sun','サン','太陽','The sun is hot.','太陽は熱い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sun']),
('sunday','サンデイ','日曜日','I play soccer on Sunday.','日曜日にサッカーをする。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sunday'])
ON CONFLICT (word) DO NOTHING;
