-- 高校受験語彙（自動生成・冪等・既存は保護）part 1
INSERT INTO words (word, reading, meaning, example_en, example_ja, grade, level, tier, is_idiom, tags, answers_en) VALUES
('about','アバウト','約、〜について','It is about two o''clock.','約2時です。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['about']),
('abroad','アブロード','外国へ','He went abroad.','彼は海外へ行った。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['abroad','overseas']),
('accept','アクセプト','受け入れる','I accept your offer.','提案を受け入れます。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['accept']),
('accident','アクシデント','事故','I saw an accident.','事故を見た。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['accident']),
('achieve','アチーブ','達成する','She achieved her goal.','彼女は目標を達成した。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['achieve','accomplish']),
('across','アクロス','〜を横切って','Walk across the street.','通りを横切りなさい。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['across']),
('act','アクト','行動する、演じる','He acts quickly.','彼は素早く行動する。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['act']),
('action','アクション','行動','Take action now.','今行動を起こせ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['action']),
('active','アクティブ','活動的な','He is an active boy.','彼は活発な少年だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['active']),
('activity','アクティビティ','活動','I enjoy outdoor activities.','野外活動を楽しむ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['activity']),
('actor','アクター','俳優','He is a famous actor.','彼は有名な俳優だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['actor']),
('actually','アクチュアリー','実は、実際に','Actually, I am tired.','実は疲れている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['actually']),
('add','アド','加える','Add some milk.','牛乳を加えなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['add']),
('address','アドレス','住所','Write your address here.','ここに住所を書いて。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['address']),
('adult','アダルト','大人','He is an adult now.','彼はもう大人だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['adult']),
('advantage','アドバンテージ','利点、有利','This is a big advantage.','これは大きな利点だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['advantage']),
('advice','アドバイス','忠告、助言','I need your advice.','あなたの助言が必要だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['advice']),
('advise','アドバイズ','忠告する','I advise you to study.','勉強するよう忠告する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['advise']),
('afraid','アフレイド','恐れて','Don''t be afraid.','恐れないで。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['afraid']),
('after','アフター','〜のあとに','See you after school.','放課後に会おう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['after']),
('afternoon','アフタヌーン','午後','Good afternoon.','こんにちは。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['afternoon']),
('again','アゲイン','再び、もう一度','Try again.','もう一度試して。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['again']),
('against','アゲンスト','〜に反対して、〜に逆らって','I am against the plan.','その計画に反対だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['against']),
('age','エイジ','年齢、時代','What is your age?','あなたの年齢は？','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['age']),
('ago','アゴー','〜前に','He left three days ago.','彼は3日前に出発した。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['ago']),
('agree','アグリー','同意する','I agree with you.','あなたに同意します。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['agree']),
('air','エアー','空気、空','Fresh air is good.','新鮮な空気は良い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['air']),
('airport','エアポート','空港','Let''s go to the airport.','空港へ行こう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['airport']),
('alive','アライブ','生きている','The fish is still alive.','その魚はまだ生きている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['alive']),
('all','オール','すべての','All students are here.','すべての生徒がここにいる。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['all']),
('allow','アロウ','許す','Allow me to go.','私が行くのを許して。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['allow','permit']),
('almost','オールモースト','ほとんど','It is almost over.','それはほとんど終わりだ。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['almost','nearly']),
('alone','アローン','一人で','She lives alone.','彼女は一人で住んでいる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['alone']),
('along','アロング','〜に沿って','Walk along the river.','川に沿って歩きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['along']),
('already','オールレディ','すでに','I have already finished.','すでに終えました。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['already']),
('also','オールソー','〜もまた','He is also a doctor.','彼もまた医者だ。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['also']),
('always','オールウェイズ','いつも','I always wake up early.','私はいつも早起きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['always']),
('amazing','アメイジング','驚くべき、素晴らしい','That is an amazing story.','それは驚くべき話だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['amazing']),
('among','アマング','〜の間に、〜の中で','Share it among yourselves.','君たちの間で分けなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['among']),
('anger','アンガー','怒り','He showed his anger.','彼は怒りを見せた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['anger']),
('angry','アングリー','怒って','My mother is angry.','母は怒っている。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['angry','mad']),
('animal','アニマル','動物','I love animals.','私は動物が好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['animal']),
('another','アナザー','もう一つの、別の','Show me another one.','別のものを見せて。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['another']),
('answer','アンサー','答え、答える','Answer my question.','私の質問に答えなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['answer']),
('any','エニー','いくつかの、少しの','Do you have any brothers?','兄弟はいますか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['any']),
('anyone','エニワン','誰か、誰も','Is anyone there?','誰かそこにいますか。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['anyone','anybody']),
('anything','エニシング','何か、何も','Do you need anything?','何か必要ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['anything']),
('anyway','エニウェイ','とにかく','Anyway, thank you.','とにかく、ありがとう。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['anyway']),
('anywhere','エニウェア','どこかに、どこにも','I can''t find it anywhere.','どこにも見つからない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['anywhere']),
('appear','アピアー','現れる、〜のように見える','A man appeared.','男が現れた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['appear']),
('area','エリア','地域、区域','This area is quiet.','この地域は静かだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['area']),
('arm','アーム','腕','He broke his left arm.','彼は左腕を折った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['arm']),
('around','アラウンド','〜の周りに、あちこち','Look around you.','周りを見なさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['around']),
('arrive','アライブ','到着する','We arrived in Tokyo.','私たちは東京に到着した。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['arrive','reach']),
('art','アート','芸術、美術','I like art very much.','私は美術がとても好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['art']),
('artist','アーティスト','芸術家','She is a great artist.','彼女は偉大な芸術家だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['artist']),
('as','アズ','〜として、〜と同じくらい','He works as a doctor.','彼は医者として働いている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['as']),
('ask','アスク','尋ねる、頼む','Can I ask a question?','質問してもいいですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ask']),
('asleep','アスリープ','眠って','He fell asleep quickly.','彼はすぐに眠りに落ちた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['asleep']),
('attack','アタック','攻撃する','The dog attacked him.','その犬は彼を攻撃した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['attack']),
('attend','アテンド','出席する','I will attend the meeting.','会議に出席します。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['attend']),
('attention','アテンション','注意、注目','Pay attention to the teacher.','先生に注意を払いなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['attention']),
('aunt','アント','おば','My aunt lives in Kyoto.','私のおばは京都に住んでいる。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['aunt']),
('autumn','オータム','秋','Autumn is my favorite season.','秋は私のお気に入りの季節だ。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['autumn','fall']),
('awake','アウェイク','目が覚めて','I was awake all night.','私は一晩中起きていた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['awake']),
('away','アウェイ','離れて','He went away.','彼は立ち去った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['away']),
('baby','ベイビー','赤ちゃん','The baby is crying.','赤ちゃんが泣いている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['baby']),
('back','バック','背中、後ろへ','Come back soon.','すぐに戻ってきて。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['back']),
('bad','バッド','悪い','That is a bad idea.','それは悪い考えだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['bad']),
('luggage','ラゲッジ','手荷物','I have a lot of luggage.','私は手荷物がたくさんある。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['luggage','baggage']),
('bake','ベイク','（パンなどを）焼く','She bakes bread every day.','彼女は毎日パンを焼く。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bake']),
('ball','ボール','球、ボール','Throw the ball to me.','私にボールを投げて。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ball']),
('band','バンド','バンド、楽団','He plays in a rock band.','彼はロックバンドで演奏している。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['band']),
('bank','バンク','銀行、土手','I went to the bank.','私は銀行へ行った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['bank']),
('base','ベース','基礎、土台','This story is based on a fact.','この話は事実に基づいている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['base']),
('baseball','ベースボール','野球','Let''s play baseball.','野球をしよう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['baseball']),
('basic','ベーシック','基本的な','These are basic rules.','これらは基本的な規則だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['basic']),
('basketball','バスケットボール','バスケットボール','He is good at basketball.','彼はバスケットボールが得意だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['basketball']),
('bath','バス','入浴','I took a bath.','私はお風呂に入った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['bath']),
('bathroom','バスルーム','浴室、トイレ','Where is the bathroom?','トイレはどこですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['bathroom']),
('be','ビー','〜である、いる、ある','I want to be a doctor.','私は医者になりたい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['be']),
('beach','ビーチ','浜辺','We walked on the beach.','私たちは浜辺を歩いた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['beach']),
('bear','ベアー','クマ、耐える','I saw a bear in the forest.','森でクマを見た。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bear']),
('beat','ビート','打ち負かす、打つ','We beat their team.','私たちは彼らのチームを打ち負かした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['beat']),
('beauty','ビューティー','美しさ','Nature has its own beauty.','自然には独自の美しさがある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['beauty']),
('because','ビコーズ','〜だから','I am happy because you are here.','あなたがここにいるので私は嬉しい。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['because']),
('become','ビカム','〜になる','He became a teacher.','彼は先生になった。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['become']),
('bed','ベッド','ベッド','I went to bed early.','私は早く寝た。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['bed']),
('bedroom','ベッドルーム','寝室','Clean your bedroom.','寝室を掃除しなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['bedroom']),
('beef','ビーフ','牛肉','We ate roast beef.','私たちはローストビーフを食べた。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['beef']),
('before','ビフォア','〜の前に','Wash your hands before dinner.','夕食の前に手を洗いなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['before']),
('begin','ビギン','始める、始まる','The movie begins at seven.','映画は7時に始まる。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['begin','start']),
('beginner','ビギナー','初心者','I am a beginner at tennis.','私はテニスの初心者です。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['beginner']),
('beginning','ビギニング','始まり','In the beginning, it was hard.','最初は難しかった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['beginning']),
('behind','ビハインド','〜の後ろに','Stand behind me.','私の後ろに立ちなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['behind']),
('believe','ビリーブ','信じる','I believe you.','あなたを信じます。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['believe']),
('bell','ベル','鐘、ベル','The bell rang.','ベルが鳴った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['bell']),
('belong','ビロング','所属する','Does this belong to you?','これはあなたのものですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['belong']),
('below','ビロウ','〜の下に','Read the sentences below.','下の文を読みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['below']),
('beside','ビサイド','〜のそばに','Come and sit beside me.','来て私のそばに座りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['beside']),
('best','ベスト','最も良い、最もよく','He is my best friend.','彼は私の親友だ。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['best']),
('better','ベター','より良い、よりよく','You will feel better soon.','すぐによくなるよ。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['better']),
('between','ビトウィーン','〜の間に','The shop is between the bank and the park.','店は銀行と公園の間にある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['between']),
('bicycle','バイシクル','自転車','I ride my bicycle to school.','自転車で学校へ行きます。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['bicycle','bike']),
('bill','ビル','請求書、紙幣','Check the bill, please.','お勘定をお願いします。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bill']),
('birth','バース','誕生','She gave birth to a boy.','彼女は男の子を出産した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['birth']),
('birthday','バースデー','誕生日','Happy birthday!','お誕生日おめでとう！','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['birthday']),
('bite','バイト','かむ','The dog bit my leg.','その犬は私の脚をかんだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bite']),
('black','ブラック','黒、黒い','He has a black cat.','彼は黒猫を飼っている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['black']),
('blind','ブラインド','目の不自由な','He helps blind people.','彼は目の不自由な人を助ける。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['blind']),
('blood','ブラッド','血','Blood is red.','血は赤い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['blood']),
('blow','ブロウ','吹く','The wind is blowing hard.','風が強く吹いている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['blow']),
('blue','ブルー','青、青い','The sky is blue today.','今日は空が青い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['blue']),
('board','ボード','板、委員会','Write it on the board.','それを黒板に書きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['board']),
('boat','ボート','ボート、船','We rented a boat.','私たちはボートを借りた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['boat']),
('body','ボディ','体','Exercise is good for your body.','運動は体に良い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['body']),
('bone','ボーン','骨','Dogs like bones.','犬は骨が好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bone']),
('borrow','ボロウ','借りる','Can I borrow your pen?','ペンを借りてもいいですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['borrow']),
('boss','ボス','上司','My boss is very kind.','私の上司はとても親切だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['boss']),
('both','ボース','両方とも','I like both of them.','私は彼らの両方とも好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['both']),
('bother','ボザー','悩ませる、じゃまをする','Don''t bother me.','私のじゃまをしないで。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bother']),
('bottom','ボトム','底','Look at the bottom of the page.','ページの底（一番下）を見なさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bottom']),
('box','ボックス','箱','Open this box.','この箱を開けなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['box']),
('brain','ブレイン','脳、頭脳','Use your brain.','頭を使いなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['brain']),
('branch','ブランチ','枝、支店','A bird is on the branch.','鳥が枝に止まっている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['branch']),
('brave','ブレイブ','勇敢な','He is a brave soldier.','彼は勇敢な兵士だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['brave']),
('break','ブレイク','壊す、休憩','Don''t break the window.','窓を壊さないで。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['break']),
('breakfast','ブレックファースト','朝食','I ate breakfast at seven.','7時に朝食を食べた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['breakfast']),
('bridge','ブリッジ','橋','Let''s cross the bridge.','橋を渡ろう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bridge']),
('bright','ブライト','明るい、賢い','The stars are bright today.','今日は星が明るい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bright']),
('bring','ブリング','持ってくる、連れてくる','Bring your notebook.','ノートを持ってきなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bring']),
('sibling','シブリング','きょうだい','Do you have any siblings?','きょうだいはいますか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['sibling']),
('brown','ブラウン','茶色、茶色の','He has brown eyes.','彼は茶色の目をしている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['brown']),
('brush','ブラッシュ','ブラシをかける、磨く','Brush your teeth.','歯を磨きなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['brush']),
('build','ビルド','建てる','They build a new house.','彼らは新しい家を建てる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['build']),
('building','ビルディング','建物','This is a tall building.','これは高い建物だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['building']),
('burn','バーン','燃える、燃やす','Paper burns easily.','紙は燃えやすい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['burn']),
('bus','バス','バス','I go to school by bus.','バスで学校へ行きます。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['bus']),
('business','ビジネス','商売、仕事','He is in Paris on business.','彼は仕事でパリにいる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['business']),
('busy','ビジー','忙しい','I am very busy today.','今日はとても忙しい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['busy']),
('but','バット','しかし','I am tired but happy.','疲れているが幸せだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['but']),
('butter','バター','バター','I need some butter.','バターが少し必要です。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['butter']),
('button','ボタン','ボタン','Push this button.','このボタンを押しなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['button']),
('by','バイ','〜によって、〜のそばに','The book was written by him.','その本は彼によって書かれた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['by']),
('cafe','カフェ','カフェ、喫茶店','Let''s go to a cafe.','カフェに行こう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cafe']),
('cake','ケーキ','ケーキ','I baked a cake.','ケーキを焼いた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cake']),
('call','コール','呼ぶ、電話する','Please call me Ken.','ケンと呼んでください。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['call']),
('camera','カメラ','カメラ','I bought a new camera.','新しいカメラを買った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['camera']),
('camp','キャンプ','キャンプ','We went to a summer camp.','私たちはサマーキャンプに行った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['camp']),
('can','キャン','〜できる','I can swim fast.','速く泳ぐことができる。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['can']),
('cancel','キャンセル','取り消す','I want to cancel my reservation.','予約をキャンセルしたい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['cancel']),
('cancer','キャンサー','がん','He died of cancer.','彼はがんで亡くなった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cancer']),
('capital','キャピタル','首都、大文字','Tokyo is the capital of Japan.','東京は日本の首都だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['capital']),
('captain','キャプテン','キャプテン、船長','He is the captain of our team.','彼は私たちのチームのキャプテンだ。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['captain']),
('car','カー','車','My father washes his car.','父は車を洗う。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['car']),
('card','カード','カード、トランプ','I sent her a birthday card.','彼女に誕生日カードを送った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['card']),
('care','ケア','世話、注意','Take care of yourself.','体に気をつけて。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['care']),
('careful','ケアフル','注意深い','Be careful.','気をつけなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['careful']),
('carefully','ケアフリー','注意深く','Listen carefully.','注意深く聞きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['carefully']),
('carry','キャリー','運ぶ','Can you carry this bag?','このかばんを運んでくれますか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['carry']),
('a lot of','アロットオブ','たくさんの','I have a lot of homework.','たくさんの宿題がある。','中1','基礎','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['a lot of','lots of']),
('at first','アットファースト','最初は','At first, I didn''t like it.','最初はそれが好きではなかった。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['at first']),
('at last','アットラスト','ついに','At last, we arrived.','ついに私たちは到着した。','中2','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['at last','finally']),
('be able to','ビーエイブルトゥ','〜できる','He will be able to come.','彼は来ることができるだろう。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be able to']),
('be famous for','ビーフェイマスフォー','〜で有名である','Kyoto is famous for its temples.','京都は寺で有名だ。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be famous for']),
('be full of','ビーフルオブ','〜でいっぱいである','The box is full of apples.','その箱はリンゴでいっぱいだ。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be full of']),
('be good at','ビーグッドアット','〜が得意である','She is good at playing tennis.','彼女はテニスをするのが得意だ。','中1','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be good at']),
('be interested in','ビーインタレステッドイン','〜に興味がある','I am interested in history.','歴史に興味がある。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be interested in']),
('be late for','ビーレイトフォー','〜に遅れる','Don''t be late for school.','学校に遅れないように。','中1','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be late for']),
('be proud of','ビープラウドオブ','〜を誇りに思う','I am proud of my son.','息子を誇りに思う。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['be proud of']),
('be used to','ビーユーズドトゥ','〜に慣れている','I am used to living alone.','一人暮らしに慣れている。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['be used to']),
('because of','ビコーズオブ','〜のために、〜の理由で','We stayed home because of rain.','雨のため家にいた。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['because of']),
('belong to','ビロングトゥ','〜に属する、〜のものである','This bag belongs to me.','このかばんは私のものだ。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['belong to']),
('catch up with','キャッチアップウィズ','〜に追いつく','I''ll catch up with you soon.','すぐにあなたに追いつきます。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['catch up with']),
('depend on','ディペンドオン','〜による、〜に頼る','It depends on the weather.','それは天気による。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['depend on']),
('do one''s best','ドゥワンズベスト','最善を尽くす','I will do my best.','最善を尽くします。','中2','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['do one''s best','do my best']),
('for example','フォーエグザンプル','例えば','I like fruit, for example, apples.','例えばリンゴなど、果物が好きだ。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['for example']),
('get along with','ゲットアロングウィズ','〜とうまくやる','He gets along with his friends.','彼は友達とうまくやっている。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['get along with']),
('get off','ゲットオフ','降りる','Let''s get off the bus here.','ここでバスを降りよう。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['get off']),
('get on','ゲットオン','乗る','He got on the train.','彼は電車に乗った。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['get on']),
('get up','ゲットアップ','起きる','I get up early every day.','毎日早く起きます。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['get up']),
('give up','ギブアップ','あきらめる','Never give up your dream.','決して夢をあきらめるな。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['give up']),
('go to bed','ゴートゥベッド','寝る','I usually go to bed at ten.','たいてい10時に寝る。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['go to bed']),
('grow up','グロウアップ','成長する、大人になる','What will you be when you grow up?','大人になったら何になりますか。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['grow up']),
('hear from','ヒアフロム','〜から便りがある','Did you hear from him?','彼から便りがありましたか。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['hear from']),
('hear of','ヒアオブ','〜のことを見聞きする','I have never heard of it.','それについて聞いたことがない。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['hear of']),
('in front of','インフロントオブ','〜の前に','He stood in front of me.','彼は私の前に立った。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['in front of']),
('in the future','インザフューチャー','将来は','I want to visit there in the future.','将来そこを訪れたい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['in the future']),
('instead of','インステッドオブ','〜の代わりに','I will go instead of you.','あなたの代わりに私がいく。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['instead of']),
('laugh at','ラフアット','〜を笑う','Don''t laugh at him.','彼を笑ってはいけない。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['laugh at']),
('ask for','アスクフォー','〜を求める','He asked for help.','彼は助けを求めた。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['ask for']),
('arrive at','アライブアット','〜に到着する','We arrived at the station.','私たちは駅に到着した。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['arrive at']),
('bring up','ブリングアップ','育てる','She was brought up in Tokyo.','彼女は東京で育った。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['bring up']),
('find out','ファインドアウト','見つけ出す、わかる','I will find out the truth.','真実を見つけ出します。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['find out']),
('make up one''s mind','メイクアップワンズマインド','決心する','I made up my mind.','私は決心した。','中3','難関','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['make up one''s mind','make up my mind']),
('more and more','モアアンドモア','ますます','I like it more and more.','それがますます好きになった。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['more and more']),
('of course','オブコース','もちろん','Of course you can.','もちろんいいですよ。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['of course']),
('put on','プットオン','着る、身につける','Put on your coat.','コートを着なさい。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['put on']),
('take care of','テイクケアオブ','〜の世話をする','Take care of your sister.','妹の世話をしなさい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['take care of']),
('take part in','テイクパートイン','〜に参加する','I will take part in the event.','そのイベントに参加します。','中3','難関','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['take part in','participate in']),
('case','ケース','場合、事件','In that case, I will go.','その場合は、私が行きます。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['case']),
('catch','キャッチ','捕まえる','Catch the ball.','ボールを捕まえて。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['catch']),
('cause','コーズ','原因、引き起こす','What caused the accident?','何が事故を引き起こしたのですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['cause']),
('center','センター','中心','Look at the center of the circle.','円の中心を見なさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['center']),
('century','センチュリー','世紀','We live in the 21st century.','私たちは21世紀に生きている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['century']),
('certain','サーテン','確かな、ある〜','I am certain of his success.','彼の成功を確信している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['certain']),
('certainly','サーテンリー','確かに、承知しました','Certainly, sir.','承知いたしました。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['certainly','sure']),
('chance','チャンス','機会、偶然','This is a good chance.','これは良い機会だ。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['chance','opportunity']),
('change','チェンジ','変える、お釣り','He changed his mind.','彼は心を変えた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['change']),
('character','キャラクター','性格、登場人物','He has a strong character.','彼は強い性格だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['character']),
('cheap','チープ','安い','This watch is very cheap.','この時計はとても安い。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['cheap']),
('check','チェック','調べる、確認する','Check your answers.','答えを確認しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['check']),
('cheer','チアー','応援する、元気づける','We cheered for our team.','私たちはチームを応援した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cheer']),
('cheese','チーズ','チーズ','I like cheese very much.','私はチーズがとても好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cheese']),
('child','チャイルド','子ども','She is a smart child.','彼女は賢い子どもだ。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['child','kid']),
('choose','チューズ','選ぶ','Choose one from these.','これらから一つ選びなさい。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['choose','select']),
('church','チャーチ','教会','They go to church on Sunday.','彼らは日曜日に教会へ行く。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['church']),
('circle','サークル','円、輪','Draw a circle.','円を描きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['circle']),
('citizen','シティズン','市民','He is a good citizen.','彼は善良な市民だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['citizen']),
('clear','クリア','明確な、晴れた','The water is very clear.','その水はとても透き通っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['clear']),
('clearly','クリアリー','はっきりと','Speak clearly.','はっきりと話しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['clearly']),
('clerk','クラーク','店員、事務員','Ask the clerk.','店員に尋ねなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['clerk']),
('clever','クレバー','賢い','He is a clever boy.','彼は賢い少年だ。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['clever','smart']),
('clock','クロック','時計','Look at the clock.','時計を見なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['clock']),
('close','クローズ','閉める、近い','Close the door, please.','ドアを閉めてください。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['close','shut']),
('clothes','クローズ','衣服','I bought new clothes.','新しい服を買った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['clothes']),
('cloud','クラウド','雲','Look at that white cloud.','あの白い雲を見なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cloud']),
('cloudy','クラウディ','曇りの','It is cloudy today.','今日は曇りだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cloudy']),
('club','クラブ','クラブ、部','I am in the tennis club.','私はテニス部に入っている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['club']),
('coast','コースト','海岸','We drove along the coast.','私たちは海岸沿いをドライブした。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['coast']),
('coat','コート','コート、上着','Put on your coat.','コートを着なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['coat']),
('coffee','コーヒー','コーヒー','I drink coffee every morning.','毎朝コーヒーを飲む。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['coffee']),
('coin','コイン','硬貨','He dropped a coin.','彼は硬貨を落とした。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['coin']),
('collect','コレクト','集める','I collect stamps.','私は切手を集めている。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['collect','gather']),
('college','カレッジ','大学','She goes to college.','彼女は大学に通っている。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['college','university']),
('comb','コーム','くし、くしでとく','I comb my hair.','私は髪をくしでとかす。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['comb']),
('comfortable','コンフォータブル','快適な','This chair is comfortable.','この椅子は快適だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['comfortable']),
('common','コモン','共通の、普通の','It is a common mistake.','それはよくある間違いだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['common']),
('communicate','コミュニケイト','意思を伝える、連絡する','We communicate by email.','私たちはメールで連絡し合う。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['communicate']),
('communication','コミュニケーション','意思疎通、通信','Communication is important.','コミュニケーションは重要だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['communication']),
('company','カンパニー','会社、仲間','He works for a computer company.','彼はコンピュータ会社で働いている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['company']),
('compare','コンペア','比較する','Don''t compare me with him.','私を彼と比べないで。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compare']),
('complain','コンプレイン','不平を言う','She always complains.','彼女はいつも文句を言う。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['complain']),
('complete','コンプリート','完全な、完成させる','My homework is complete.','私の宿題は完成した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['complete']),
('concert','コンサート','演奏会','I went to a piano concert.','ピアノのコンサートに行った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['concert']),
('condition','コンディション','状態、条件','The car is in good condition.','その車は良い状態だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['condition']),
('continue','コンティニュー','続ける、続く','Please continue your story.','話を続けてください。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['continue']),
('control','コントロール','支配する、制御する','Control your anger.','怒りを抑えなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['control']),
('cook','クック','料理する、料理人','My father cooks well.','父は料理が上手だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cook']),
('cool','クール','涼しい、かっこいい','It is cool today.','今日は涼しい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cool']),
('copy','コピー','写す、複写','Copy this page.','このページをコピーしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['copy']),
('corner','コーナー','角','Turn right at the corner.','その角を右に曲がりなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['corner']),
('correct','コレクト','正しい、訂正する','Your answer is correct.','あなたの答えは正しい。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['correct','right']),
('cost','コスト','費用がかかる','How much does it cost?','いくらかかりますか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['cost']),
('cotton','コットン','綿','This shirt is made of cotton.','このシャツは綿で作られている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cotton']),
('cough','カフ','咳をする、咳','I have a bad cough.','ひどい咳が出る。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['cough']),
('count','カウント','数える','Count from one to ten.','1から10まで数えなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['count']),
('course','コース','進路、課程','I take an English course.','私は英語のコースをとっている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['course']),
('cover','カバー','覆う、表紙','Snow covered the mountain.','雪が山を覆った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cover']),
('cow','カウ','牛','Look at the cows.','牛を見なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cow']),
('crazy','クレイジー','夢中である、おかしい','He is crazy about soccer.','彼はサッカーに夢中だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['crazy']),
('create','クリエイト','創造する','She created a new design.','彼女は新しいデザインを作った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['create']),
('cross','クロス','横切る、十字架','Let''s cross the street.','通りを渡ろう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cross']),
('crowd','クラウド','群衆、人混み','A large crowd gathered.','大きな群衆が集まった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['crowd']),
('crowded','クラウディッド','混雑した','The train was crowded.','電車は混んでいた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['crowded']),
('cry','クライ','泣く、叫ぶ','The baby began to cry.','赤ちゃんが泣き始めた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cry']),
('culture','カルチャー','文化','I want to learn Japanese culture.','日本の文化を学びたい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['culture']),
('cup','カップ','カップ、茶碗','I want a cup of tea.','お茶を一杯欲しい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cup']),
('custom','カスタム','習慣、風習','It is a traditional custom.','それは伝統的な風習だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['custom']),
('cut','カット','切る','He cut the paper.','彼は紙を切った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cut']),
('cute','キュート','かわいい','What a cute baby!','なんてかわいい赤ちゃんなんでしょう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cute']),
('daily','デイリー','毎日の、日常の','This is our daily life.','これが私たちの日常生活だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['daily']),
('dance','ダンス','踊る、ダンス','She likes to dance.','彼女は踊るのが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['dance']),
('danger','デンジャー','危険','He is in danger.','彼は危険な状態にある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['danger']),
('dangerous','デンジャラス','危険な','It is dangerous to swim here.','ここで泳ぐのは危険だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['dangerous']),
('dark','ダーク','暗い','It is getting dark.','暗くなってきた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['dark']),
('date','デイト','日付、デート','What is the date today?','今日は何日ですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['date']),
('daughter','ドーター','娘','My daughter is three years old.','娘は3歳です。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['daughter']),
('dead','デッド','死んでいる','The tree is dead.','その木は枯れている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['dead']),
('deal','ディール','扱う、取引','How do you deal with it?','それをどう扱いますか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['deal']),
('dear','ディアー','親愛なる','Dear Ken.','親愛なるケンへ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['dear']),
('death','デス','死','He heard of her death.','彼は彼女の死を聞いた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['death']),
('decide','ディサイド','決める','I decided to go to America.','アメリカに行くことを決めた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['decide']),
('decision','ディシジョン','決定、決心','It was a hard decision.','それは難しい決定だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['decision']),
('deep','ディープ','深い','The river is very deep.','その川はとても深い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['deep']),
('deeply','ディープリー','深く','I was deeply moved.','私は深く感動した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['deeply']),
('degree','ディグリー','度、程度','It is 30 degrees today.','今日は30度だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['degree']),
('delicious','デリシャス','とてもおいしい','This cake is delicious.','このケーキはとてもおいしい。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['delicious','tasty']),
('deliver','デリバー','配達する','Please deliver this pizza.','このピザを配達してください。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['deliver']),
('department','デパートメント','部門、売り場','I went to a department store.','デパートに行った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['department']),
('depend','ディペンド','頼る、次第である','It depends on you.','それはあなた次第だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['depend']),
('design','デザイン','デザイン、設計する','I like this design.','このデザインが好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['design']),
('destroy','デストロイ','破壊する','The fire destroyed the building.','火事がその建物を破壊した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['destroy']),
('detail','ディテール','細部、詳細','Tell me the details.','詳細を教えてください。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['detail']),
('develop','ディベロップ','発達させる、開発する','They developed a new game.','彼らは新しいゲームを開発した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['develop']),
('dictionary','ディクショナリー','辞書','I need an English dictionary.','英語の辞書が必要だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['dictionary']),
('die','ダイ','死ぬ','His grandfather died last year.','彼の祖父は去年亡くなった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['die']),
('difference','ディファレンス','違い','What is the difference?','違いは何ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['difference']),
('different','ディファレント','違った、いろいろな','We have different opinions.','私たちは違った意見を持っている。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['different']),
('difficult','ディフィカルト','難しい','This test was difficult.','このテストは難しかった。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['difficult','hard']),
('difficulty','ディフィカルティ','困難','We faced a difficulty.','私たちは困難に直面した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['difficulty']),
('dig','ディグ','掘る','They dug a hole.','彼らは穴を掘った。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['dig']),
('dirty','ダーティ','汚れた','Wash your dirty hands.','汚れた手を洗いなさい。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['dirty']),
('discover','ディスカバー','発見する','He discovered a new star.','彼は新しい星を発見した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['discover']),
('discuss','ディスカス','話し合う、議論する','Let''s discuss this problem.','この問題について話し合おう。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['discuss']),
('disease','ディジーズ','病気','He suffered from a rare disease.','彼は珍しい病気に苦しんだ。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['disease','illness']),
('dish','ディッシュ','皿、料理','I washed the dishes.','私は皿を洗った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['dish']),
('distance','ディスタンス','距離','It is a long distance.','それは長い距離だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['distance']),
('divide','ディバイド','分ける','Divide the cake into four.','ケーキを4つに分けなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['divide']),
('doctor','ドクター','医者','You should see a doctor.','医者に診てもらうべきだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['doctor']),
('dollar','ダラー','ドル','It costs ten dollars.','それは10ドルかかります。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['dollar']),
('door','ドア','ドア、戸','Open the door.','ドアを開けて。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['door']),
('double','ダブル','2倍の、2倍にする','He has double my money.','彼は私の2倍のお金を持っている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['double']),
('doubt','ダウト','疑う、疑い','I doubt his story.','私は彼の話を疑っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['doubt']),
('down','ダウン','下へ、下がって','Please sit down.','座ってください。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['down']),
('draw','ドロー','（線で）描く、引く','Can you draw a map?','地図を描けますか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['draw']),
('dream','ドリーム','夢','I had a strange dream.','変な夢を見た。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['dream']),
('dress','ドレス','ドレス、服','She wore a red dress.','彼女は赤いドレスを着ていた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['dress']),
('drill','ドリル','ドリル、反復練習','We did a math drill.','私たちは数学のドリルをした。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['drill']),
('drive','ドライブ','運転する','My father drives a taxi.','父はタクシーを運転している。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['drive']),
('driver','ドライバー','運転手','He is a safe driver.','彼は安全な運転手だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['driver']),
('drop','ドロップ','落とす、滴','I dropped my phone.','電話を落とした。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['drop']),
('dry','ドライ','乾いた、乾かす','Dry your hair.','髪を乾かしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['dry']),
('duck','ダック','アヒル、カモ','I saw a duck in the park.','公園でアヒルを見た。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['duck']),
('during','デュアリング','〜の間に','I slept during the class.','授業中に寝てしまった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['during']),
('duty','デューティ','義務、職務','It is my duty.','それは私の義務だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['duty']),
('each','イーチ','それぞれの','Each student has a book.','それぞれの生徒が本を持っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['each']),
('ear','イヤー','耳','My left ear hurts.','左耳が痛い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ear']),
('early','アーリー','早く、早い','I got up early.','私は早く起きた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['early']),
('earth','アース','地球、土','The earth is round.','地球は丸い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['earth']),
('east','イースト','東、東の','The sun rises in the east.','太陽は東から昇る。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['east']),
('easily','イージリー','簡単に','I can do it easily.','簡単にできます。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['easily']),
('effort','エフォート','努力','He made a great effort.','彼は大変な努力をした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['effort']),
('either','イーザー','どちらの、どちらか','You can take either bus.','どちらのバスに乗ってもいいですよ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['either']),
('elephant','エレファント','ゾウ','Elephants are very big.','ゾウはとても大きい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['elephant']),
('else','エルス','他に','What else do you want?','他に何が欲しいですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['else']),
('email','イーメール','Eメール','Send me an email.','メールを送ってください。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['email','e-mail']),
('empty','エンプティ','空の','The box is empty.','その箱は空だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['empty']),
('end','エンド','終わり、終わる','This is the end of the story.','これがその話の終わりだ。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['end']),
('energy','エナジー','エネルギー、活力','We need more energy.','私たちはもっとエネルギーが必要だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['energy']),
('engine','エンジン','エンジン','Start the engine.','エンジンをかけなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['engine']),
('engineer','エンジニア','技師、エンジニア','He wants to be an engineer.','彼はエンジニアになりたい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['engineer']),
('enjoy','エンジョイ','楽しむ','We enjoyed the party.','私たちはパーティーを楽しんだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['enjoy']),
('enough','イナフ','十分な、十分に','I have enough money.','十分なお金がある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['enough']),
('enter','エンター','入る、入学する','He entered the room.','彼は部屋に入った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['enter']),
('environment','エンバイロメント','環境','We must protect the environment.','私たちは環境を守らなければならない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['environment']),
('equal','イコール','等しい、平等な','All men are equal.','すべての人は平等だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['equal']),
('escape','エスケープ','逃げる','The bird escaped from the cage.','鳥がかごから逃げた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['escape']),
('especially','エスペシャリー','特に','I like fruit, especially apples.','私は果物、特にリンゴが好きだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['especially']),
('even','イーヴン','〜でさえ','Even a child knows it.','子どもでさえそれを知っている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['even']),
('evening','イブニング','夕方、晩','I watch TV in the evening.','夕方にテレビを見る。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['evening']),
('event','イベント','出来事、行事','It was a big school event.','それは大きな学校行事だった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['event']),
('ever','エバー','今までに','Have you ever been to Kyoto?','今までに京都に行ったことがありますか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['ever']),
('everyone','エブリワン','みんな','Everyone likes him.','みんな彼が好きだ。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['everyone','everybody']),
('everything','エブリシング','すべてのこと','Everything is fine.','すべて順調です。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['everything']),
('everywhere','エブリウェア','どこでも','I looked everywhere.','私はどこでも探した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['everywhere']),
('exact','イグザクト','正確な','What is the exact time?','正確な時間は何時ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['exact']),
('exactly','イグザクトリー','正確に、その通り','That is exactly right.','それはまさにその通りだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['exactly']),
('exam','イグザム','試験','I passed the math exam.','数学の試験に合格した。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['exam','examination']),
('examine','イグザミン','調査する、診察する','The doctor examined me.','医者が私を診察した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['examine']),
('excellent','エクセレント','優秀な、素晴らしい','That is an excellent idea.','それは素晴らしい考えだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['excellent']),
('exchange','エクスチェンジ','交換する','Let''s exchange emails.','メールアドレスを交換しよう。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['exchange']),
('excite','エキサイト','興奮させる','The game excited everyone.','その試合はみんなを興奮させた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['excite']),
('excited','エキサイティッド','興奮して','I am very excited.','私はとても興奮している。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['excited']),
('exciting','エキサイティング','興奮させる、ワクワクする','It was an exciting game.','それはワクワクする試合だった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['exciting']),
('excuse','エクスキューズ','許す、言い訳','Excuse me.','すみません。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['excuse']),
('exercise','エクササイズ','運動、練習問題','I exercise every morning.','毎朝運動をする。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['exercise']),
('expect','エクスペクト','予期する、期待する','I didn''t expect this.','私はこれを予期していなかった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['expect']),
('expensive','エクスペンシブ','高価な','This car is expensive.','この車は高価だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['expensive']),
('experience','エクスペリエンス','経験、経験する','It was a good experience.','それは良い経験だった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['experience']),
('explain','エクスプレイン','説明する','Please explain the rule.','その規則を説明してください。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['explain']),
('express','エクスプレス','表現する、急行','I can''t express my feelings.','感情を表現できない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['express']),
('extra','エクストラ','余分な、追加の','We need extra time.','追加の時間が必要だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['extra']),
('fact','ファクト','事実','Tell me the facts.','事実を教えて。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['fact']),
('factory','ファクトリー','工場','He works in a car factory.','彼は自動車工場で働いている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['factory']),
('fail','フェイル','失敗する、落ちる','I failed the test.','テストに落ちた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['fail']),
('fair','フェア','公平な','That''s not fair.','それは不公平だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['fair']),
('false','フォルス','誤った、偽の','Is it true or false?','それは本当ですか、嘘ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['false']),
('familiar','ファミリアー','なじみのある','Her face looks familiar.','彼女の顔は見覚えがある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['familiar']),
('famous','フェイマス','有名な','He is a famous singer.','彼は有名な歌手だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['famous']),
('fan','ファン','ファン、扇','I am a big fan of his.','私は彼の大ファンだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['fan']),
('far','ファー','遠くに','Do you live far from here?','ここから遠くに住んでいますか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['far']),
('farm','ファーム','農場','They work on a farm.','彼らは農場で働いている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['farm']),
('farmer','ファーマー','農民','He is a successful farmer.','彼は成功した農民だ。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['farmer']),
('fashion','ファッション','流行、ファッション','She likes fashion.','彼女はファッションが好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['fashion']),
('fault','フォルト','責任、欠点','It is my fault.','それは私の責任だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['fault']),
('favor','フェイバー','親切な行為、お願い','Can you do me a favor?','お願いがあるのですが。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['favor']),
('favorite','フェイバリット','お気に入りの','This is my favorite song.','これは私のお気に入りの歌だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['favorite']),
('fear','フィアー','恐怖、恐れる','He has a fear of heights.','彼は高所恐怖症だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['fear']),
('feel','フィール','感じる','I feel sick today.','今日は気分が悪い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['feel']),
('feeling','フィーリング','感情、感覚','I have a bad feeling.','嫌な予感がする。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['feeling']),
('festival','フェスティバル','祭り','We enjoyed the summer festival.','私たちは夏祭りを楽しんだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['festival']),
('few','フュー','ほとんどない、少数の','I have few friends here.','ここに友達はほとんどいない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['few']),
('field','フィールド','野原、分野','We played in the field.','私たちは野原で遊んだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['field']),
('fight','ファイト','戦う、けんか','Don''t fight with your brother.','弟とけんかしてはいけない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['fight']),
('fill','フィル','満たす','Fill the glass with water.','グラスを水で満たしなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['fill']),
('film','フィルム','映画、フィルム','I watched a good film.','良い映画を見た。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['film','movie']),
('final','ファイナル','最後の','This is the final game.','これが最後の試合だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['final']),
('finally','ファイナリー','ついに、最後に','I finally finished my homework.','ついに宿題を終えた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['finally']),
('find','ファインド','見つける','I can''t find my keys.','鍵が見つからない。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['find']),
('fine','ファイン','元気な、立派な','I am fine, thank you.','元気です、ありがとう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['fine']),
('finger','フィンガー','指','She cut her finger.','彼女は指を切った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['finger']),
('finish','フィニッシュ','終える','I finished reading the book.','本を読み終えた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['finish']),
('fire','ファイア','火、火事','Don''t play with fire.','火遊びをしてはいけない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['fire']),
('firm','ファーム','会社、固い','He works for a law firm.','彼は法律事務所で働いている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['firm']),
('first','ファースト','最初の、最初に','She was the first to come.','彼女が一番最初に来た。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['first']),
('flight','フライト','飛行の便、空の旅','My flight was canceled.','私の飛行機はキャンセルされた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['flight']),
('floor','フロア','床、階','Clean the floor.','床をきれいにしなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['floor']),
('fly','フライ','飛ぶ、飛行機で行く','Birds fly in the sky.','鳥が空を飛ぶ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['fly']),
('focus','フォーカス','集中する、焦点','Focus on your study.','勉強に集中しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['focus']),
('follow','フォロー','ついて行く、従う','Follow me.','私についてきなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['follow']),
('foolish','フーリッシュ','愚かな','That is a foolish idea.','それは愚かな考えだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['foolish']),
('foreign','フォーリン','外国の','I want to learn foreign languages.','外国語を学びたい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['foreign']),
('foreigner','フォーリナー','外国人','He is a foreigner.','彼は外国人だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['foreigner']),
('forest','フォレスト','森','We walked in the forest.','私たちは森の中を歩いた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['forest']),
('forget','フォーゲット','忘れる','Don''t forget your umbrella.','傘を忘れないで。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['forget']),
('forgive','フォーギブ','許す','Please forgive me.','私を許してください。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['forgive']),
('form','フォーム','形、用紙','Fill in this form.','この用紙に記入してください。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['form']),
('free','フリー','自由な、暇な、無料の','Are you free tomorrow?','明日は暇ですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['free']),
('freedom','フリーダム','自由','We have freedom of speech.','私たちには言論の自由がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['freedom']),
('fresh','フレッシュ','新鮮な','These vegetables are fresh.','これらの野菜は新鮮だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['fresh']),
('fridge','フリッジ','冷蔵庫','Put it in the fridge.','それを冷蔵庫に入れなさい。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['fridge','refrigerator']),
('friendly','フレンドリー','友好的な、親切な','He is very friendly.','彼はとても友好的だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['friendly']),
('friendship','フレンドシップ','友情','Our friendship will never end.','私たちの友情は決して終わらない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['friendship']),
('front','フロント','前部、正面','Go to the front.','前に行きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['front']),
('fruit','フルーツ','果物','I like eating fresh fruit.','新鮮な果物を食べるのが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['fruit']),
('full','フル','いっぱいの、満腹の','I am full now.','私は今お腹がいっぱいだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['full']),
('fun','ファン','楽しみ、面白いこと','It was a lot of fun.','とても楽しかった。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['fun']),
('funny','ファニー','おかしい、滑稽な','He told a funny story.','彼はおかしい話をした。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['funny']),
('future','フューチャー','未来、将来','We must think about the future.','私たちは未来について考えなければならない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['future']),
('look for','ルックフォー','〜を探す','What are you looking for?','何を探しているのですか。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['look for']),
('look forward to','ルックフォワードトゥ','〜を楽しみに待つ','I am looking forward to seeing you.','あなたに会うのを楽しみにしています。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['look forward to']),
('look after','ルックアフター','〜の世話をする','Please look after my cat.','猫の世話をお願いします。','中2','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['look after','take care of']),
('look like','ルックライク','〜のように見える、似ている','He looks like his father.','彼は父親に似ている。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['look like']),
('make friends with','メイクフレンズウィズ','〜と友達になる','I want to make friends with him.','彼と友達になりたい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['make friends with']),
('pay attention to','ペイアテンショントゥ','〜に注意を払う','Pay attention to the signs.','標識に注意を払いなさい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['pay attention to']),
('run away','ランアウェイ','逃げる','The thief ran away.','泥棒は逃げた。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['run away']),
('show up','ショウアップ','現れる','He didn''t show up.','彼は現れなかった。','中3','難関','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['show up','appear']),
('smile at','スマイルアット','〜にほほえむ','She smiled at me.','彼女は私にほほえみかけた。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['smile at']),
('speak to','スピークトゥ','〜に話しかける','I spoke to the teacher.','先生に話しかけた。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['speak to']),
('stand up','スタンドアップ','立ち上がる','Please stand up.','立ち上がってください。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['stand up']),
('stay up','ステイアップ','（寝ないで）起きている','Don''t stay up late.','遅くまで起きているな。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['stay up']),
('take a walk','テイクアウォーク','散歩する','I took a walk in the park.','公園を散歩した。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['take a walk']),
('take off','テイクオフ','脱ぐ、離陸する','Take off your shoes.','靴を脱ぎなさい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['take off']),
('talk about','トークアバウト','〜について話す','We talked about the movie.','私たちはその映画について話した。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['talk about']),
('think of','シンクオブ','〜を思いつく、〜のことについて考える','What do you think of it?','それについてどう思いますか。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['think of']),
('try on','トライオン','試着する','Can I try this on?','これを試着してもいいですか。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['try on']),
('turn off','ターンオフ','（電気やテレビを）消す','Turn off the light.','電気を消しなさい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['turn off']),
('turn on','ターンオン','（電気やテレビを）つける','Turn on the TV.','テレビをつけなさい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['turn on']),
('wait for','ウェイトフォー','〜を待つ','I am waiting for a bus.','バスを待っている。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['wait for'])
ON CONFLICT (word) DO NOTHING;
