-- 高校受験語彙（自動生成・冪等・既存は保護）part 4
INSERT INTO words (word, reading, meaning, example_en, example_ja, grade, level, tier, is_idiom, tags, answers_en) VALUES
('sunny','サニー','晴れた','It is a sunny day.','今日は晴れだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sunny']),
('super','スーパー','素晴らしい、超の','It is a super idea.','素晴らしい考えだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['super']),
('support','サポート','支持する、支える','Support your family.','家族を支えなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['support']),
('suppose','サポーズ','想定する、思う','I suppose you are right.','君が正しいと思う。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['suppose']),
('sure','シュア','確信して、もちろん','Are you sure?','確信していますか？','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sure']),
('surface','サーフェス','表面','The surface is smooth.','その表面は滑らかだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['surface']),
('surprise','サプライズ','驚き、驚かせる','What a surprise!','なんて驚きだろう！','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['surprise']),
('surprised','サプライズド','驚いて','I am surprised at the news.','そのニュースに驚いている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['surprised']),
('surprising','サプライジング','驚くべき','It is a surprising fact.','それは驚くべき事実だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['surprising']),
('surround','サラウンド','取り囲む','Trees surround the house.','木々がその家を取り囲んでいる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['surround']),
('survive','サヴァイヴ','生き残る','He survived the accident.','彼はその事故から生き残った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['survive']),
('suspect','サスペクト','疑う、容疑者','Who do you suspect?','誰を疑いますか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['suspect']),
('swallow','スワロー','飲み込む','Swallow the pill.','その錠剤を飲み込みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['swallow']),
('swear','スウェア','誓う、罵る','I swear it''s true.','本当だと誓う。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['swear']),
('sweat','スウェット','汗、汗をかく','I am covered in sweat.','汗でびっしょりだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['sweat']),
('sweater','スウェター','セーター','Wear a sweater.','セーターを着なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sweater']),
('sweep','スイープ','掃く','Sweep the floor.','床を掃きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['sweep']),
('sweet','スイート','甘い','The apple is sweet.','そのリンゴは甘い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['sweet']),
('swell','スウェル','膨らむ','My foot swelled up.','足が腫れ上がった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['swell']),
('swim','スイム','泳ぐ','I like to swim.','泳ぐのが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['swim']),
('swing','スウィング','揺れる','The swing is moving.','ブランコが動いている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['swing']),
('switch','スイッチ','切り替える、スイッチ','Switch the light off.','電気を切りなさい（消しなさい）。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['switch']),
('sword','ソード','剣','He holds a sword.','彼は剣を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['sword']),
('system','システム','体系、仕組み','The system is working.','そのシステムは動いている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['system']),
('set up','セットアップ','準備する、設立する','Set up the new computer.','新しいコンピュータをセットアップしなさい。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['set up']),
('show off','ショウオフ','見せびらかす','Don''t show off.','見せびらかしてはいけない。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['show off']),
('so far','ソーファー','今までのところ','It''s good so far.','今までのところ順調だ。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['so far']),
('speak to oneself','スピークトゥワンセルフ','独り言を言う','He was speaking to himself.','彼は独り言を言っていた。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['speak to oneself']),
('stand for','スタンドフォー','〜を表す、意味する','What does UFO stand for?','UFOは何の略ですか。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['stand for']),
('stay in bed','ステイインベッド','寝ている','You should stay in bed.','寝ていなさい。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['stay in bed']),
('take a rest','テイクアレスト','休息をとる','Let''s take a rest.','休息をとろう。','中2','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['take a rest','take a break']),
('take back','テイクバック','取り戻す、前言を取り消す','Take back your words.','前言を取り消しなさい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['take back']),
('take place','テイクプレイス','行われる','The meeting takes place today.','会議は今日行われる。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['take place']),
('think over','シンクオーバー','よく考える','Think it over.','よく考えなさい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['think over']),
('try one''s best','トライワンズベスト','最善を尽くす','I will try my best.','最善を尽くします。','中3','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['try one''s best','try my best']),
('turn down','ターンダウン','断る、音を小さくする','He turned down my offer.','彼は申し出を断った。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['turn down']),
('table','テーブル','テーブル、表','Sit at the table.','テーブルに座りなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['table']),
('tail','テイル','しっぽ','The dog has a long tail.','その犬は長いしっぽがある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['tail']),
('take','テイク','取る、連れて行く','Take your umbrella.','傘を持って行きなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['take']),
('talent','タレント','才能','He has a talent for music.','彼は音楽の才能がある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['talent']),
('talk','トーク','話す、話し合い','Let''s talk about it.','それについて話そう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['talk']),
('tall','トール','背が高い','He is very tall.','彼はとても背が高い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['tall']),
('task','タスク','課題、仕事','Finish your task.','課題を終わらせなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['task']),
('taste','テイスト','味、味わう','The soup tastes good.','そのスープは良い味がする。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['taste']),
('tax','タックス','税金','We must pay tax.','税金を払わなければならない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['tax']),
('teach','ティーチ','教える','He teaches us English.','彼は私たちに英語を教える。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['teach']),
('team','チーム','チーム','Our team won.','私たちのチームが勝った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['team']),
('tear','ティア','涙、引き裂く','Tears came to her eyes.','彼女は涙を流した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['tear']),
('technical','テクニカル','技術的な','It is a technical problem.','それは技術的な問題だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['technical']),
('technique','テクニック','技術、技巧','He has a good technique.','彼は良い技術を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['technique']),
('technology','テクノロジー','科学技術','Technology is changing.','技術が変化している。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['technology']),
('teenager','ティーンエイジャー','10代の若者','He is a teenager.','彼は10代の若者だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['teenager']),
('telephone','テレフォン','電話','Answer the telephone.','電話に出なさい。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['telephone','phone']),
('television','テレビジョン','テレビ','Watch television.','テレビを見なさい。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['television','tv']),
('tell','テル','話す、告げる','Tell me the truth.','真実を話しなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['tell']),
('temperature','テンパラチャー','温度、体温','The temperature is high.','気温（体温）が高い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['temperature']),
('temple','テンプル','寺','We visited the temple.','私たちは寺を訪れた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['temple']),
('temporary','テンポラリー','一時的な','It is a temporary job.','それは一時的な仕事だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['temporary']),
('tend','テンド','傾向がある','I tend to forget names.','名前を忘れる傾向がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['tend']),
('term','ターム','期間、学期、用語','The second term starts.','2学期が始まる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['term']),
('terrible','テリブル','ひどい、恐ろしい','What a terrible accident.','なんてひどい事故だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['terrible']),
('test','テスト','テスト、試験','Study for the test.','テストのために勉強しなさい。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['test','exam']),
('text','テキスト','本文、文章','Read the text.','本文を読みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['text']),
('than','ザン','〜より','He is taller than me.','彼は私より背が高い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['than']),
('thank','サンク','感謝する','Thank you for everything.','すべてに感謝します。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['thank']),
('that','ザット','あの、あれ','That is my book.','あれは私の本だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['that']),
('the','ザ','その','The book is good.','その本は良い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['the']),
('theater','シアター','劇場、映画館','Let''s go to the theater.','劇場へ行こう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['theater']),
('their','ゼア','彼らの','That is their house.','あれは彼らの家だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['their']),
('theirs','ゼアズ','彼らのもの','The car is theirs.','その車は彼らのものだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['theirs']),
('them','ゼム','彼らを','I know them well.','彼らをよく知っている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['them']),
('themselves','ゼムセルヴズ','彼ら自身','They did it themselves.','彼らは自分たちでやった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['themselves']),
('then','ゼン','その時、それから','What happened then?','その時何が起きた？','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['then']),
('theory','セオリー','理論','It is a new theory.','それは新しい理論だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['theory']),
('there','ゼア','そこに','I will go there.','そこへ行く。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['there']),
('therefore','ゼアフォー','したがって','Therefore, he is right.','したがって、彼は正しい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['therefore','so']),
('these','ジーズ','これら','These are my friends.','これらは私の友達だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['these']),
('they','ゼイ','彼らは','They are students.','彼らは学生だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['they']),
('thick','シック','厚い、太い','The book is very thick.','その本はとても厚い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['thick']),
('thin','シン','薄い、細い','The paper is very thin.','その紙はとても薄い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['thin']),
('thing','スィング','物、事','What is that thing?','あれは何ですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['thing']),
('think','シンク','思う、考える','I think so.','そう思う。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['think']),
('third','サード','第3の','This is my third try.','これが3回目の試みだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['third']),
('though','ゾウ','〜だけれども','Though it was late, I went.','遅かったけれども、行った。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['though']),
('thought','ソート','考え','He had a good thought.','彼は良い考えを持っていた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['thought']),
('thousand','サウザンド','1000','I have a thousand yen.','1000円持っている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['thousand']),
('threat','スレット','脅威、脅迫','It is a serious threat.','それは重大な脅威だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['threat']),
('threaten','スレトゥン','脅かす','Don''t threaten me.','私を脅かさないで。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['threaten']),
('throat','スロート','のど','I have a sore throat.','のどが痛い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['throat']),
('through','スルー','〜を通って、〜を通して','Walk through the park.','公園を通って歩きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['through']),
('throw','スロウ','投げる','Throw the ball to me.','私にボールを投げて。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['throw']),
('thumb','サム','親指','He hurt his thumb.','彼は親指を痛めた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['thumb']),
('thunder','サンダー','雷','I heard thunder.','雷の音を聞いた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['thunder']),
('thus','ザス','このように、したがって','Thus, we succeeded.','このようにして、私たちは成功した。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['thus','so']),
('ticket','チケット','切符、券','Do you have a ticket?','切符を持っていますか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ticket']),
('tidy','タイディ','整頓された','Keep your room tidy.','部屋をきれいに片付けなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['tidy']),
('tie','タイ','縛る、ネクタイ','Tie your shoes.','靴ひもを結びなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['tie']),
('tight','タイト','きつい、堅い','These shoes are tight.','これらの靴はきつい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['tight']),
('time','タイム','時間','What time is it?','何時ですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['time']),
('tiny','タイニー','とても小さい','A tiny bug is on the leaf.','葉の上に小さな虫がいる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['tiny']),
('tip','チップ','先端、助言','Here is a good tip.','ここに良いアドバイスがある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['tip']),
('tired','タイアード','疲れた','I am very tired.','私はとても疲れている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['tired']),
('title','タイトル','題名','What is the title?','題名は何ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['title']),
('to','トゥ','〜へ、〜に','I go to school.','私は学校へ行く。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['to']),
('today','トゥデイ','今日','It is cold today.','今日は寒い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['today']),
('toe','トー','足の指','I hurt my toe.','足の指を痛めた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['toe']),
('together','トゥゲザー','一緒に','Let''s go together.','一緒に行こう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['together']),
('toilet','トイレット','トイレ','Where is the toilet?','トイレはどこですか。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['toilet','bathroom']),
('tomorrow','トゥモロー','明日','I will go tomorrow.','明日行く。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['tomorrow']),
('tonight','トゥナイト','今夜','I am busy tonight.','今夜は忙しい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['tonight']),
('too','トゥー','〜もまた、あまりに〜すぎる','I am too tired.','あまりに疲れすぎている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['too']),
('tool','ツール','道具','Use the right tool.','正しい道具を使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['tool']),
('tooth','トゥース','歯','Brush your teeth.','歯を磨きなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['tooth']),
('top','トップ','頂上、トップ','We reached the top.','頂上に達した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['top']),
('topic','トピック','話題','It is a good topic.','それは良い話題だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['topic']),
('total','トータル','合計の、全体の','The total is 100.','合計は100だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['total']),
('touch','タッチ','触れる','Don''t touch it.','それに触れてはいけない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['touch']),
('tough','タフ','困難な、頑丈な','It was a tough day.','困難な一日だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['tough']),
('tour','ツアー','旅行、周遊','We went on a tour.','私たちはツアーに行った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['tour']),
('tourist','ツーリスト','観光客','The city has many tourists.','その町には多くの観光客がいる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['tourist']),
('toward','トワード','〜の方へ','He walked toward me.','彼は私の方へ歩いてきた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['toward']),
('tower','タワー','塔','The tower is very high.','その塔はとても高い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['tower']),
('town','タウン','町','It is a small town.','それは小さな町だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['town']),
('toy','トイ','おもちゃ','I have many toys.','たくさんのおもちゃを持っている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['toy']),
('trade','トレード','貿易、交換する','We trade with them.','私たちは彼らと貿易している。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['trade']),
('tradition','トラディション','伝統','It is our tradition.','それは私たちの伝統だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['tradition']),
('traditional','トラディショナル','伝統的な','Eat traditional food.','伝統的な食べ物を食べなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['traditional']),
('traffic','トラフィック','交通','There is much traffic.','交通量が多い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['traffic']),
('train','トレイン','電車、訓練する','Take the train.','電車に乗りなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['train']),
('training','トレーニング','訓練','It is good training.','それは良い訓練だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['training']),
('transfer','トランスファー','移す、乗り換える','Transfer to the bus.','バスに乗り換えなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['transfer']),
('translate','トランスレイト','翻訳する','Translate this into English.','これを英語に翻訳しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['translate']),
('translation','トランスレーション','翻訳','The translation is wrong.','その翻訳は間違っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['translation']),
('transport','トランスポート','輸送する','They transport goods.','彼らは商品を輸送する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['transport']),
('travel','トラベル','旅行する','I love to travel.','旅行するのが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['travel']),
('treasure','トレジャー','宝物','He found a treasure.','彼は宝物を見つけた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['treasure']),
('treat','トリート','扱う、治療する','Treat others well.','他人を親切に扱いなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['treat']),
('treatment','トリートメント','治療、扱い','He needs treatment.','彼は治療が必要だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['treatment']),
('tree','ツリー','木','Climb the tree.','木に登りなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['tree']),
('trend','トレンド','傾向、流行','It is a new trend.','それは新しい流行だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['trend']),
('trial','トライアル','試み、裁判','It was a fair trial.','それは公平な裁判だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['trial']),
('trick','トリック','策略、手品','That is a clever trick.','それは巧妙なトリックだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['trick']),
('trip','トリップ','小旅行','I enjoyed my trip.','旅行を楽しんだ。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['trip','journey']),
('trouble','トラブル','困難、悩み','I am in trouble.','困っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['trouble']),
('true','トゥルー','真実の、本当の','It is a true story.','それは実話だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['true']),
('truly','トゥルーリー','本当に、心から','I am truly sorry.','本当に申し訳なく思う。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['truly']),
('trust','トラスト','信頼する','I trust you.','あなたを信頼している。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['trust']),
('truth','トゥルース','真実','Tell me the truth.','真実を話しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['truth']),
('try','トライ','試みる、挑戦する','Try your best.','最善を尽くしなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['try']),
('tube','チューブ','管、チューブ','It is a plastic tube.','それはプラスチックのチューブだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['tube']),
('tune','チューン','曲、調子','I like this tune.','この曲が好きだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['tune']),
('turn','ターン','回転、順番','It is your turn.','君の番だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['turn']),
('twice','トワイス','2度','I went there twice.','そこへ2度行った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['twice']),
('twin','ツイン','双子','They are twins.','彼らは双子だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['twin']),
('type','タイプ','型、種類','What type of music?','どんなタイプの音楽？','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['type']),
('typical','ティピカル','典型的な','It is a typical example.','それは典型的な例だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['typical']),
('ugly','アグリー','醜い','It is an ugly building.','それは醜い建物だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ugly']),
('ultimate','アルティメット','最終的な、究極の','It is the ultimate goal.','それが究極の目標だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ultimate']),
('umbrella','アンブレラ','傘','Take your umbrella.','傘を持って行きなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['umbrella']),
('unable','アナブル','〜できない','I am unable to go.','行くことができない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['unable']),
('uncle','アンクル','おじ','My uncle is kind.','私のおじは親切だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['uncle']),
('under','アンダー','〜の下に','It is under the desk.','机の下にある。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['under']),
('understand','アンダースタンド','理解する','I understand English.','英語を理解している。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['understand']),
('union','ユニオン','結合、組合','They joined the union.','彼らは組合に加入した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['union']),
('unique','ユニーク','唯一の、独特な','That is a unique idea.','それは独特な考えだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['unique']),
('unit','ユニット','単位、構成単位','What is the unit?','単位は何ですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['unit']),
('unite','ユナイト','団結する','We must unite.','私たちは団結しなければならない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['unite']),
('unity','ユニティ','団結、統一','We need unity.','団結が必要だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['unity']),
('universe','ユニヴァース','宇宙','The universe is huge.','宇宙は巨大だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['universe']),
('university','ユニヴァーシティ','大学','He goes to university.','彼は大学に通っている。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['university','college']),
('unless','アンレス','〜でない限り','Unless you hurry, you''ll be late.','急がない限り、遅れるぞ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['unless']),
('until','アンティル','〜まで','Wait until I come back.','私が戻るまで待って。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['until']),
('up','アップ','上へ','Look up at the sky.','空を見上げなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['up']),
('upon','アポン','〜の上に','Once upon a time.','昔々。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['upon']),
('upper','アッパー','上の、上部の','The upper part is red.','上部が赤い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['upper']),
('upset','アップセット','動転した、腹を立てた','Don''t get upset.','動転してはいけない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['upset']),
('upstairs','アップステアズ','上の階へ','Go upstairs.','上の階へ行きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['upstairs']),
('urge','アージ','強く促す','He urged me to go.','彼は行くよう私を強く促した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['urge']),
('urgent','アージェント','緊急の','It is an urgent matter.','それは緊急の件だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['urgent']),
('us','アス','私たちを','Help us.','私たちを助けて。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['us']),
('use','ユーズ','使う','Can I use your pen?','ペンを使ってもいいですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['use']),
('useful','ユースフル','役に立つ','This is a useful book.','これは役に立つ本だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['useful']),
('useless','ユースレス','役に立たない','The tool is useless.','その道具は役に立たない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['useless']),
('user','ユーザー','ユーザー、利用者','I am a new user.','私は新しいユーザーです。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['user']),
('usual','ユージュアル','いつもの、普通の','It is his usual style.','それが彼のいつものスタイルだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['usual']),
('usually','ユージュアリー','たいてい','I usually go by bus.','たいていバスで行く。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['usually']),
('vacation','ヴァケーション','休暇','I have a summer vacation.','夏休みがある。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['vacation']),
('vague','ヴェイグ','曖昧な','It is a vague memory.','それは曖昧な記憶だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['vague']),
('valid','ヴァリッド','有効な','Is the ticket valid?','その切符は有効ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['valid']),
('valley','ヴァレー','谷','The village is in the valley.','その村は谷にある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['valley']),
('valuable','ヴァリュアブル','価値のある、貴重な','This is a valuable book.','これは貴重な本だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['valuable']),
('value','ヴァリュー','価値','What is the value?','価値は何ですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['value']),
('vanish','ヴァニッシュ','消える','The bird vanished.','鳥が消えた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['vanish']),
('variety','ヴァラエティ','多様性、種類','A wide variety of books.','多種多様な本。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['variety']),
('various','ヴェアリアス','さまざまな','We have various ideas.','私たちはさまざまな考えを持っている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['various']),
('vary','ヴェアリー','異なる、変化する','Prices vary here.','価格はここで異なる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['vary']),
('vast','ヴァスト','広大な','The desert is vast.','砂漠は広大だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['vast']),
('vegetable','ヴェジタブル','野菜','Eat your vegetables.','野菜を食べなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['vegetable']),
('vehicle','ヴィークル','乗り物、車両','What kind of vehicle?','どんな種類の乗り物？','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['vehicle']),
('very','ヴェリー','とても','It is very cold.','とても寒い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['very']),
('victim','ヴィクティム','犠牲者','He is a victim of the accident.','彼は事故の犠牲者だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['victim']),
('victory','ヴィクトリー','勝利','It was a great victory.','それは偉大な勝利だった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['victory']),
('video','ヴィデオ','動画、ビデオ','Watch this video.','このビデオを見なさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['video']),
('view','ヴュー','眺め、意見','The view is great.','眺めが最高だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['view']),
('village','ヴィレッジ','村','He lives in a small village.','彼は小さな村に住んでいる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['village']),
('violence','ヴァイオレンス','暴力','I hate violence.','私は暴力が嫌いだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['violence']),
('violent','ヴァイオレント','暴力的な','Don''t be violent.','暴力的になってはいけない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['violent']),
('visit','ヴィジット','訪れる','I will visit my friend.','友達を訪ねるつもりだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['visit']),
('visitor','ヴィジター','訪問者','We have many visitors.','多くの訪問者がいる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['visitor']),
('voice','ヴォイス','声','She has a beautiful voice.','彼女は美しい声をしている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['voice']),
('volume','ヴォリューム','音量、量','Turn up the volume.','音量を上げなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['volume']),
('vote','ヴォート','投票、投票する','Did you vote?','投票しましたか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['vote']),
('voyage','ヴォイッジ','航海','It was a long voyage.','それは長い航海だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['voyage']),
('wait','ウェイト','待つ','Wait for me.','私を待って。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['wait']),
('wake','ウェイク','目を覚ます','Wake me at seven.','7時に起こして。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wake']),
('walk','ウォーク','歩く','I like to walk.','歩くのが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['walk']),
('wall','ウォール','壁','The wall is white.','その壁は白い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['wall']),
('want','ウォント','ほしい','I want this book.','この本がほしい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['want']),
('war','ウォー','戦争','We don''t want war.','私たちは戦争を望まない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['war']),
('warm','ウォーム','温かい','It is warm today.','今日は温かい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['warm']),
('warn','ウォーン','警告する','He warned me.','彼は私に警告した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['warn']),
('wash','ウォッシュ','洗う','Wash your face.','顔を洗いなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['wash']),
('waste','ウェスト','無駄にする、無駄','Don''t waste your time.','時間を無駄にするな。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['waste']),
('watch','ウォッチ','見る、腕時計','I watch TV.','テレビを見る。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['watch']),
('water','ウォーター','水','Drink some water.','水を飲みなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['water']),
('wave','ウェイヴ','波、手を振る','The waves are big.','波が大きい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wave']),
('way','ウェイ','道、方法','Show me the way.','道を教えて。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['way']),
('we','ウィー','私たちは','We are students.','私たちは学生だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['we']),
('weak','ウィーク','弱い','He is very weak.','彼はとても弱い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['weak']),
('wealth','ウェルス','富、財産','Wealth is not everything.','富がすべてではない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['wealth']),
('wealthy','ウェルシー','裕福な','He is a wealthy man.','彼は裕福な男だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['wealthy']),
('wear','ウェア','着ている','She wears a blue dress.','彼女は青いドレスを着ている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['wear']),
('weather','ウェザー','天気','The weather is good.','天気が良い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['weather']),
('week','ウィーク','週','I will go next week.','来週行く。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['week']),
('weekend','ウィークエンド','週末','I am free this weekend.','今週末は暇だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['weekend']),
('weekly','ウィークリー','毎週の','It is a weekly magazine.','それは週刊誌だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['weekly']),
('weigh','ウェイ','重さがある、量る','It weighs 50 kilos.','それは50キロの重さがある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['weigh']),
('weight','ウェイト','重さ、体重','I want to lose weight.','ダイエット（減量）したい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['weight']),
('welcome','ウェルカム','歓迎する','You are welcome.','どういたしまして。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['welcome']),
('well','ウェル','よく、上手に','He speaks well.','彼は上手に話す。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['well']),
('west','ウェスト','西、西の','Go west from here.','ここから西へ行きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['west']),
('wet','ウェット','濡れた','My clothes are wet.','服が濡れている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wet']),
('what','ワット','何','What is this?','これは何ですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['what']),
('when','ウェン','いつ','When is your birthday?','誕生日（の月日）はいつ？','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['when']),
('where','ウェア','どこ','Where do you live?','どこに住んでいますか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['where']),
('whether','ウェザー','〜かどうか','I don''t know whether he will come.','彼が来るかどうか知らない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['whether']),
('which','ウィッチ','どちら、どれ','Which do you like?','どちらが好きですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['which']),
('while','ワイル','〜する間に','Read while I eat.','私が食べている間に読みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['while']),
('white','ホワイト','白、白い','The wall is white.','その壁は白い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['white']),
('who','フー','誰','Who is that boy?','あの少年は誰？','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['who']),
('whole','ホール','全体の、全部の','The whole family is here.','家族全員がここにいる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['whole']),
('whom','フーム','誰を（目的格）','To whom shall I give this?','誰にこれを渡すべきですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['whom']),
('whose','フーズ','誰の','Whose pen is this?','これは誰のペンですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['whose']),
('why','ワイ','なぜ','Why are you late?','なぜ遅れたのですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['why']),
('wide','ワイド','広い','The river is very wide.','その川はとても広い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wide']),
('wife','ワイフ','妻','His wife is kind.','彼の妻は親切だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['wife']),
('wild','ワイルド','野生の','I saw wild animals.','野生動物を見た。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wild']),
('will','ウィル','〜するつもりだ','I will study English.','英語を勉強するつもりだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['will']),
('win','ウィン','勝つ','We want to win.','勝ちたい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['win']),
('wind','ウィンド','風','The wind is strong.','風が強い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['wind']),
('window','ウィンドウ','窓','Open the window.','窓を開けなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['window']),
('windy','ウィンディ','風の強い','It is windy today.','今日は風が強い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['windy']),
('wine','ワイン','ワイン','I like red wine.','赤ワインが好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wine']),
('wing','ウィング','翼','The bird has wings.','その鳥は翼がある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wing']),
('winner','ウィナー','勝者','He is the winner.','彼が勝者だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['winner']),
('winter','ウィンター','冬','Winter is cold.','冬は寒い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['winter']),
('wire','ワイヤー','針金、ワイヤー','Cut the wire.','針金を切りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['wire']),
('wise','ワイズ','賢い','He is a wise man.','彼は賢い男だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['wise']),
('wish','ウィッシュ','願う','I wish you luck.','幸運を祈る。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wish']),
('with','ウィズ','〜と一緒に','Come with me.','私と一緒に来なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['with']),
('within','ウィズイン','〜以内に','Do it within an hour.','1時間以内にやりなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['within']),
('without','ウィズアウト','〜なしで','I can''t live without you.','君なしでは生きられない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['without']),
('woman','ウーマン','女性','She is a woman.','彼女は女性だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['woman']),
('women','ウィメン','女性たち（womanの複数形）','The women are talking.','女性たちが話している。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['women']),
('wonder','ワンダー','不思議に思う','I wonder why.','なぜだろうと思う。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['wonder']),
('wonderful','ワンダフル','素晴らしい','It is a wonderful day.','素晴らしい一日だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wonderful']),
('wood','ウッド','木材、森','The table is made of wood.','そのテーブルは木製だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wood']),
('wooden','ウッデン','木製の','It is a wooden box.','それは木製の箱だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['wooden']),
('wool','ウール','羊毛、ウール','It is made of wool.','それはウール製だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['wool']),
('word','ワード','単語、言葉','Learn this word.','この単語を学びなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['word']),
('work','ワーク','働く、仕事','I have a lot of work.','仕事がたくさんある。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['work']),
('worker','ワーカー','労働者、作業員','He is a hard worker.','彼は働き者だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['worker']),
('world','ワールド','世界','The world is changing.','世界が変化している。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['world']),
('worry','ウォリー','心配する','Don''t worry about it.','心配しないで。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['worry']),
('worse','ワース','より悪い','It is getting worse.','より悪くなっている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['worse']),
('worst','ワースト','最も悪い','It is the worst day.','それが最悪の日だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['worst']),
('worth','ワース','価値がある','It is worth trying.','試す価値がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['worth']),
('would','ウッド','〜だろう、〜したい','Would you like tea?','お茶はいかがですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['would']),
('wound','ワウンド','傷、傷つける','He has a deep wound.','彼は深い傷を負っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['wound']),
('wrap','ラップ','包む','Wrap the present.','プレゼントを包みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['wrap']),
('write','ライト','書く','Write your name.','名前を書きなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['write']),
('writer','ライター','作家、筆者','He is a famous writer.','彼は有名な作家だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['writer']),
('wrong','ロング','間違った','Your answer is wrong.','答えが間違っている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['wrong']),
('yard','ヤード','庭、ヤード','Children play in the yard.','子どもたちが庭で遊んでいる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['yard']),
('year','イヤー','年','I study every year.','毎年勉強する。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['year']),
('yell','イェル','叫ぶ','Don''t yell at me.','私に向かって叫ぶな。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['yell','shout']),
('yellow','イエロー','黄色、黄色の','I like yellow.','黄色が好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['yellow']),
('yes','イエス','はい','Yes, I am.','はい、そうです。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['yes']),
('yesterday','イエスタデイ','昨日','I went yesterday.','昨日行った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['yesterday']),
('yet','イェット','まだ、もう','Not yet.','まだです。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['yet']),
('you','ユー','あなた','I like you.','あなたが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['you']),
('young','ヤング','若い','He is very young.','彼はとても若い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['young']),
('your','ユア','あなたの','This is your pen.','これはあなたのペンだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['your']),
('yours','ユアーズ','あなたのもの','That book is yours.','あの本はあなたのものだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['yours']),
('yourself','ユアセルフ','あなた自身','Take care of yourself.','自分自身を大事にしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['yourself']),
('youth','ユース','若さ、青年期','He spent his youth here.','彼は若さをここで過ごした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['youth']),
('zero','ゼロ','0','It is zero degrees.','0度だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['zero']),
('zone','ゾーン','地域、区域','It is a safe zone.','それは安全地帯だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['zone']),
('zoom','ズーム','ズームする','Zoom in the photo.','写真をズームしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['zoom']),
('be used to -ing','ビーユーズドトゥ〜イング','〜することに慣れている','I am used to getting up early.','早起きすることに慣れている。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['be used to -ing']),
('by oneself','バイワンセルフ','一人で','I did it by myself.','自分でそれを行った。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['by oneself']),
('come across','カムアクロス','偶然出会う','I came across him.','彼と偶然出会った。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['come across']),
('come up with','カムアップウィズ','思いつく','I came up with an idea.','考えを思いついた。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['come up with']),
('cut down','カットダウン','切り倒す、減らす','Cut down the trees.','木を切り倒しなさい。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['cut down']),
('get over','ゲットオーバー','乗り越える','He got over the problem.','彼は問題を乗り越えた。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['get over']),
('give away','ギブアウェイ','与える、バラす','Give away your old toys.','古いおもちゃをあげなさい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['give away']),
('go on -ing','ゴーン〜イング','〜し続ける','He went on reading.','彼は読み続けた。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['go on -ing']),
('hold back','ホールドバック','抑える','He held back his tears.','彼は涙をこらえた。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['hold back']),
('keep on -ing','キープオン〜イング','〜し続ける','Keep on trying.','挑戦し続けなさい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['keep on -ing']),
('look forward to -ing','ルックフォワードトゥ〜イング','〜することを楽しみに待つ','I look forward to meeting you.','お会いできるのを楽しみにしています。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['look forward to -ing']),
('make up','メイクアップ','作り上げる、仲直りする','Make up your mind.','決心しなさい。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['make up']),
('pick out','ピックアウト','選び出す','Pick out the best one.','一番良いものを選び出しなさい。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['pick out']),
('run out of','ランアウトオブ','〜を使い果たす','We ran out of gas.','ガスを使い果たした。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['run out of']),
('set free','セットフリー','解放する','Set the bird free.','鳥を解放しなさい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['set free']),
('take after','テイクアフター','似ている','He takes after his father.','彼は父親に似ている。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['take after']),
('take over','テイクオーバー','引き継ぐ','He will take over the work.','彼がその仕事を引き継ぐだろう。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['take over']),
('turn up','ターンアップ','現れる、音を大きくする','Turn up the volume.','音量を大きくしなさい。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['turn up']),
('write down','ライトダウン','書き留める','Write down the address.','住所を書き留めなさい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['write down'])
ON CONFLICT (word) DO NOTHING;
