-- 高校受験語彙（Claude著者・第1バッチ・冪等）
INSERT INTO words (word, reading, meaning, example_en, example_ja, grade, level, tier, is_idiom, tags, answers_en) VALUES
('look up','ルック アップ','（辞書などで）調べる','Look up the word.','その単語を調べなさい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['look up']),
('carry out','キャリー アウト','実行する','They carried out the plan.','彼らは計画を実行した。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['carry out']),
('wake up','ウェイク アップ','目を覚ます','I wake up at six.','私は6時に起きる。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['wake up']),
('sit down','シット ダウン','座る','Sit down, please.','座ってください。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['sit down']),
('come from','カム フロム','〜の出身である','I come from Japan.','私は日本出身です。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['come from']),
('work out','ワーク アウト','運動する、解決する','I work out every morning.','私は毎朝運動する。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['work out']),
('break down','ブレイク ダウン','故障する','My car broke down.','車が故障した。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['break down']),
('be made of','ビー メイド オブ','〜でできている','This desk is made of wood.','この机は木でできている。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be made of']),
('be made from','ビー メイド フロム','〜から作られる','Wine is made from grapes.','ワインはぶどうから作られる。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be made from']),
('be covered with','ビー カバード ウィズ','〜で覆われている','The mountain is covered with snow.','山は雪で覆われている。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['be covered with']),
('be filled with','ビー フィルド ウィズ','〜でいっぱいである','The box is filled with toys.','箱はおもちゃでいっぱいだ。','中3','難関','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['be filled with','be full of']),
('be known as','ビー ノウン アズ','〜として知られている','He is known as a singer.','彼は歌手として知られている。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['be known as']),
('be different from','ビー ディファレント フロム','〜と異なる','Mine is different from yours.','私のはあなたのと違う。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be different from']),
('be similar to','ビー シミラー トゥ','〜に似ている','This is similar to that.','これはあれに似ている。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['be similar to']),
('be ready for','ビー レディ フォー','〜の準備ができている','Are you ready for the test?','テストの準備はできた？','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be ready for']),
('be absent from','ビー アブセント フロム','〜を欠席する','He was absent from school.','彼は学校を欠席した。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['be absent from']),
('be good for','ビー グッド フォー','〜に良い','Walking is good for health.','歩くことは健康に良い。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be good for']),
('be kind to','ビー カインド トゥ','〜に親切である','Be kind to others.','他人に親切にしなさい。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be kind to']),
('be surprised at','ビー サプライズド アット','〜に驚く','I was surprised at the news.','その知らせに驚いた。','中3','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['be surprised at','be surprised by']),
('be worried about','ビー ワリード アバウト','〜を心配している','She is worried about you.','彼女はあなたを心配している。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be worried about']),
('be excited about','ビー エキサイテッド アバウト','〜にわくわくしている','I''m excited about the trip.','旅行にわくわくしている。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['be excited about']),
('be tired of','ビー タイアード オブ','〜にうんざりしている','I''m tired of waiting.','待つのにうんざりだ。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['be tired of']),
('be fond of','ビー フォンド オブ','〜が好きである','She is fond of music.','彼女は音楽が好きだ。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['be fond of']),
('be based on','ビー ベイスト オン','〜に基づいている','The movie is based on a true story.','その映画は実話に基づいている。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['be based on']),
('at least','アット リースト','少なくとも','It costs at least ten dollars.','少なくとも10ドルかかる。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['at least']),
('at once','アット ワンス','すぐに、一度に','Come here at once.','すぐにここに来なさい。','中3','難関','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['at once','immediately']),
('by the way','バイ ザ ウェイ','ところで','By the way, where is he?','ところで、彼はどこ？','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['by the way']),
('for a while','フォー ア ホワイル','しばらくの間','Wait here for a while.','しばらくここで待って。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['for a while']),
('for the first time','フォー ザ ファースト タイム','初めて','I saw snow for the first time.','初めて雪を見た。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['for the first time']),
('no longer','ノー ロンガー','もはや〜ない','He is no longer a child.','彼はもう子どもではない。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['no longer']),
('as soon as','アズ スーン アズ','〜するとすぐに','Call me as soon as you arrive.','着いたらすぐ電話して。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['as soon as']),
('as well as','アズ ウェル アズ','〜と同様に','He speaks French as well as English.','彼は英語だけでなくフランス語も話す。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['as well as']),
('as long as','アズ ロング アズ','〜する限り','You can stay as long as you like.','好きなだけいていいよ。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['as long as']),
('such as','サッチ アズ','〜のような','Fruits such as apples are healthy.','リンゴのような果物は健康的だ。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['such as']),
('thanks to','サンクス トゥ','〜のおかげで','Thanks to you, I passed.','あなたのおかげで合格した。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['thanks to']),
('according to','アコーディング トゥ','〜によれば','According to the news, it will rain.','ニュースによれば雨が降る。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['according to']),
('up to','アップ トゥ','〜まで、〜次第','It''s up to you.','それは君次第だ。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['up to']),
('next to','ネクスト トゥ','〜の隣に','She sat next to me.','彼女は私の隣に座った。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['next to']),
('far from','ファー フロム','〜から遠い','The station is far from here.','駅はここから遠い。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['far from']),
('rather than','ラザー ザン','〜よりむしろ','I walk rather than run.','私は走るよりむしろ歩く。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['rather than']),
('used to','ユーストゥ','以前は〜したものだ','I used to play tennis.','以前はテニスをしたものだ。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['used to']),
('each other','イーチ アザー','お互い','They helped each other.','彼らは互いに助け合った。','中2','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['each other','one another']),
('a few','ア フュー','少しの（数）','I have a few friends here.','ここには数人の友達がいる。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['a few']),
('a little','ア リトル','少しの（量）','Add a little salt.','塩を少し加えて。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['a little']),
('a number of','ア ナンバー オブ','いくつもの、多数の','A number of people came.','多くの人が来た。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['a number of']),
('plenty of','プレンティ オブ','たくさんの','We have plenty of time.','時間はたっぷりある。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['plenty of']),
('a kind of','ア カインド オブ','一種の','It''s a kind of fruit.','それは一種の果物だ。','中3','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['a kind of']),
('a pair of','ア ペア オブ','一対の','I bought a pair of shoes.','靴を一足買った。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['a pair of']),
('get to','ゲット トゥ','〜に着く','How can I get to the station?','駅へはどう行けますか。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['get to']),
('jacket','ジャケット','上着、ジャケット','Put on your jacket.','上着を着なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['jacket']),
('jam','ジャム','ジャム、渋滞','I like strawberry jam.','いちごジャムが好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['jam']),
('job','ジョブ','仕事','She has a good job.','彼女は良い仕事をしている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['job']),
('jog','ジョグ','ジョギングする','I jog in the park.','私は公園でジョギングする。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['jog']),
('join','ジョイン','参加する、加わる','Will you join us?','私たちに加わりませんか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['join']),
('joke','ジョーク','冗談','He told a funny joke.','彼は面白い冗談を言った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['joke']),
('journalist','ジャーナリスト','記者','She is a journalist.','彼女は記者だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['journalist']),
('journey','ジャーニー','旅','We had a long journey.','私たちは長い旅をした。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['journey','trip']),
('joy','ジョイ','喜び','Her eyes were full of joy.','彼女の目は喜びに満ちていた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['joy']),
('judge','ジャッジ','判断する、裁判官','Don''t judge by looks.','見た目で判断するな。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['judge']),
('juice','ジュース','ジュース','I want some orange juice.','オレンジジュースが欲しい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['juice']),
('jump','ジャンプ','跳ぶ','The cat jumped high.','猫は高く跳んだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['jump']),
('jungle','ジャングル','ジャングル','Many animals live in the jungle.','多くの動物がジャングルに住む。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['jungle']),
('junior','ジュニア','年下の、下級の','He is junior to me.','彼は私より年下だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['junior']),
('justice','ジャスティス','正義','We must fight for justice.','正義のために戦わねばならない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['justice']),
('just','ジャスト','ちょうど、ただ〜だけ','I just arrived.','ちょうど着いたところだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['just']),
('x-ray','エックスレイ','レントゲン、X線','The doctor took an X-ray.','医者はレントゲンを撮った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['x-ray']),
('ladder','ラダー','はしご','He climbed up the ladder.','彼ははしごを登った。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['ladder']),
('level','レベル','水準、段階','His English is at a high level.','彼の英語は高いレベルだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['level']),
('lie','ライ','横たわる、うそをつく','Don''t lie to me.','私にうそをつくな。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['lie']),
('limit','リミット','限界、制限','There is a time limit.','制限時間がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['limit']),
('local','ローカル','地元の、その土地の','I visited a local market.','私は地元の市場を訪れた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['local']),
('locate','ロケート','位置する','The shop is located near here.','店はこの近くにある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['locate']),
('magazine','マガジン','雑誌','I read a fashion magazine.','私はファッション雑誌を読む。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['magazine']),
('major','メジャー','主要な、大きい','This is a major problem.','これは大きな問題だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['major']),
('manage','マネージ','管理する、なんとかやり遂げる','She manages a restaurant.','彼女はレストランを経営している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['manage']),
('marry','マリー','結婚する','He married her last year.','彼は去年彼女と結婚した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['marry']),
('master','マスター','習得する、達人','He mastered English.','彼は英語を習得した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['master']),
('natural','ナチュラル','自然の','It is a natural reaction.','それは自然な反応だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['natural']),
('noble','ノーブル','高貴な、立派な','He has a noble heart.','彼は高潔な心を持つ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['noble']),
('obey','オベイ','従う','Obey the rules.','規則に従いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['obey']),
('operation','オペレーション','手術、操作','The operation was successful.','手術は成功した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['operation']),
('origin','オリジン','起源','What is the origin of this word?','この語の起源は何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['origin']),
('percent','パーセント','パーセント','Ninety percent agreed.','90パーセントが賛成した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['percent']),
('photograph','フォトグラフ','写真','He took a photograph.','彼は写真を撮った。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['photograph','photo'])
ON CONFLICT (word) DO NOTHING;
