-- 高校受験語彙 追加分(a-c) part 1・冪等
INSERT INTO words (word, reading, meaning, example_en, example_ja, grade, level, tier, is_idiom, tags, answers_en) VALUES
('absent','アブセント','欠席している','He is absent from school today.','彼は今日学校を欠席している。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['absent']),
('abolish','アボリッシュ','廃止する','They decided to abolish the law.','彼らはその法律を廃止することに決めた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['abolish']),
('abundant','アバンダント','豊富な','Water is abundant here.','ここでは水が豊富だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['abundant']),
('acceptable','アクセプタブル','許容できる','That is not acceptable.','それは許容できない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['acceptable']),
('access','アクセス','利用、接近','I have access to the web.','ウェブにアクセスできる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['access']),
('accessible','アクセシブル','利用しやすい','The library is easily accessible.','図書館は利用しやすい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['accessible']),
('accomplish','アコンプリッシュ','成し遂げる','He accomplished his goal.','彼は目標を成し遂げた。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['accomplish','achieve']),
('accurate','アキュレイト','正確な','Give me an accurate answer.','正確な答えをください。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['accurate','correct']),
('accuse','アキュウズ','非難する、告発する','Don''t accuse him of lying.','彼が嘘をついたと非難しないで。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['accuse']),
('acid','アシッド','酸、酸性の','This is a strong acid.','これは強い酸だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['acid']),
('acknowledge','アクノレッジ','認める','He acknowledged his mistake.','彼はミスを認めた。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['acknowledge','admit']),
('acquaintance','アクウェインタンス','知人','He is an old acquaintance.','彼は昔からの知人だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['acquaintance']),
('acquire','アクワイア','獲得する','I acquired new skills.','新しいスキルを獲得した。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['acquire','get']),
('acre','エーカー','エーカー（面積の単位）','The farm is ten acres.','その農場は10エーカーある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['acre']),
('activate','アクティヴェイト','作動させる','Activate the alarm system.','警報装置を作動させなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['activate']),
('adapt','アダプト','適合させる','Adapt to the new life.','新しい生活に適合しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['adapt']),
('adequate','アディクィット','十分な','That is an adequate answer.','それは十分な答えだ。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['adequate','enough']),
('adjust','アジャスト','調節する','Adjust your seat.','座席を調節しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['adjust']),
('administration','アドミニストレーション','管理、運営','Improve the administration.','管理体制を改善しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['administration']),
('admire','アドマイアー','賞賛する','I admire her work.','彼女の仕事を賞賛する。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['admire']),
('admission','アドミッション','入場許可、入会','The admission is free.','入場は無料だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['admission']),
('admit','アドミット','認める','He admitted his guilt.','彼は罪を認めた。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['admit','acknowledge']),
('adopt','アダプト','採用する、養子にする','Adopt a new plan.','新しい計画を採用する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['adopt']),
('advance','アドヴァンス','前進、進歩','We made great advances.','私たちは大きな進歩を遂げた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['advance']),
('advanced','アドヴァンスド','高度な','It is an advanced class.','それは高度なクラスだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['advanced']),
('advantageous','アドヴァンティジャス','有利な','It is advantageous to us.','それは私たちに有利だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['advantageous']),
('adventure','アドヴェンチャー','冒険','The adventure was fun.','その冒険は楽しかった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['adventure']),
('adverse','アドヴァース','不利な、有害な','It had an adverse effect.','有害な影響があった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['adverse']),
('advertise','アドヴァタイズ','宣伝する','Advertise the product.','その製品を宣伝しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['advertise']),
('advertisement','アドヴァタイズメント','広告','I saw an advertisement.','広告を見た。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['advertisement','ad']),
('advocate','アドヴォケイト','主張する、支持する','He advocates peace.','彼は平和を主張する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['advocate']),
('aesthetic','エスセティック','美学の、審美的な','It is an aesthetic choice.','それは審美的な選択だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['aesthetic']),
('affect','アフェクト','影響する','Weather affects my mood.','天気が気分に影響する。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['affect','influence']),
('affection','アフェクション','愛情','He has deep affection.','彼は深い愛情を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['affection']),
('affirm','アファーム','断言する','He affirmed his intention.','彼は意図を断言した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['affirm']),
('afford','アフォード','〜する余裕がある','I can''t afford it.','それを買う余裕がない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['afford']),
('affordable','アフォーダブル','手頃な','This is an affordable price.','これは手頃な価格だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['affordable']),
('aftermath','アフターマス','余波、直後','The aftermath was terrible.','余波はひどいものだった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['aftermath']),
('agency','エイジェンシー','機関、代理店','I work at the agency.','その代理店で働いている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['agency']),
('agenda','アジェンダ','議題','What is the agenda?','議題は何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['agenda']),
('aggression','アグレッション','攻撃性、侵略','He showed aggression.','彼は攻撃性を見せた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['aggression']),
('aggressive','アグレッシヴ','攻撃的な','Don''t be aggressive.','攻撃的にならないで。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['aggressive']),
('agony','アゴニー','苦痛、苦悩','He is in agony.','彼は苦痛の中にいる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['agony']),
('agreeable','アグリーアブル','快い、同意できる','He is an agreeable person.','彼は快い人だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['agreeable']),
('agriculture','アグリカルチャー','農業','Agriculture is important.','農業は重要だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['agriculture']),
('aid','エイド','援助、助け','They sent aid.','彼らは援助を送った。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['aid','help']),
('aim','エイム','狙う、目的','Aim at the target.','標的を狙いなさい。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['aim','goal']),
('aircraft','エアクラフト','航空機','The aircraft took off.','その航空機は離陸した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['aircraft']),
('airline','エアライン','航空会社','Which airline do you use?','どの航空会社を使いますか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['airline']),
('alarm','アラーム','警報、驚き','The alarm rang.','警報が鳴った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['alarm']),
('album','アルバム','アルバム','I have a photo album.','写真アルバムを持っている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['album']),
('alcohol','アルコール','アルコール','He does not drink alcohol.','彼はアルコールを飲まない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['alcohol']),
('alert','アラート','油断のない、警告','Stay alert.','警戒しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['alert']),
('alien','エイリアン','外国人、宇宙人','He is an alien here.','彼はここでは外国人だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['alien']),
('align','アライン','整列させる','Align the rows.','行を整列させなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['align']),
('alike','アライク','同様の','They think alike.','彼らは同様に考える。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['alike']),
('allege','アレッジ','主張する','He alleged it was true.','彼はそれが真実だと主張した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['allege']),
('alleviate','アリーヴィエイト','軽減する','Alleviate the pain.','痛みを軽減しなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['alleviate','relieve']),
('allocate','アロケイト','割り当てる','Allocate the funds.','資金を割り当てなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['allocate']),
('allowance','アロアンス','手当、小遣い','I get a weekly allowance.','週ごとの小遣いをもらう。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['allowance']),
('ally','アライ','同盟国','They are our allies.','彼らは私たちの同盟国だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ally']),
('aloud','アラウンド','声を出して','Read it aloud.','声に出して読みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['aloud']),
('alphabet','アルファベット','アルファベット','Learn the alphabet.','アルファベットを学びなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['alphabet']),
('alter','オルター','変える','Alter the plan.','計画を変更しなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['alter','change']),
('alternate','オルタネイト','交互の','Take alternate days.','交互の日を取りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['alternate']),
('alternative','オルタネイティヴ','代わりの、選択肢','Do you have an alternative?','代替案（選択肢）はありますか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['alternative']),
('altitude','アルティチュード','高度','The altitude is high.','高度が高い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['altitude']),
('amateur','アマチュア','素人の','He is an amateur player.','彼は素人の選手だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['amateur']),
('amaze','アメイズ','驚かせる','It amazed me.','それは私を驚かせた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['amaze']),
('ambassador','アンバサダー','大使','He is the ambassador.','彼が大使だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ambassador']),
('ambition','アンビション','野心、熱望','He has great ambition.','彼は大きな野心を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ambition']),
('ambitious','アンビシャス','野心的な','He is an ambitious man.','彼は野心的な男だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ambitious']),
('amend','アメンド','修正する','Amend the law.','法律を修正しなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['amend','revise']),
('amiable','エイミアブル','愛想の良い','She is an amiable person.','彼女は愛想の良い人だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['amiable']),
('ample','アンプル','十分な','There is ample space.','十分なスペースがある。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['ample','enough']),
('amplify','アンプリファイ','増幅する','Amplify the sound.','音を増幅しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['amplify']),
('amuse','アミューズ','楽しませる','It amused the children.','それは子どもたちを楽しませた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['amuse']),
('amusement','アミューズメント','娯楽','It is for amusement.','それは娯楽のためだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['amusement']),
('analogy','アナロジー','類推','Use an analogy.','類推を使いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['analogy']),
('analyze','アナライズ','分析する','Analyze the data.','データを分析しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['analyze']),
('analysis','アナリシス','分析','The analysis is correct.','その分析は正しい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['analysis']),
('ancestor','アンセスター','先祖','He is my ancestor.','彼は私の先祖だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ancestor']),
('anchor','アンカー','錨','Drop the anchor.','錨を下ろしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['anchor']),
('ancient','エンシェント','古代の','It is an ancient city.','それは古代都市だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['ancient']),
('anecdote','アネクドート','逸話','He told an anecdote.','彼は逸話を語った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['anecdote']),
('angle','アングル','角度','Measure the angle.','角度を測りなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['angle']),
('animate','アニメイト','活気づける','It animated the talk.','それが話を活気づけた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['animate']),
('ankle','アンクル','足首','I hurt my ankle.','足首を痛めた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['ankle']),
('annex','アネックス','付加する','Annex the land.','その土地を付加しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['annex']),
('anniversary','アニヴァーサリー','記念日','It is our anniversary.','私たちの記念日だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['anniversary']),
('annotate','アノテイト','注釈をつける','Annotate the text.','本文に注釈をつけなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['annotate']),
('announce','アナウンス','発表する','They announced it.','彼らはそれを発表した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['announce']),
('announcement','アナウンスメント','発表','Did you hear the announcement?','発表を聞いた？','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['announcement']),
('annoy','アノイ','悩ませる','Don''t annoy me.','私を悩ませないで。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['annoy']),
('annual','アニュアル','年次の','It is an annual event.','それは年次行事だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['annual']),
('anonymous','アノニマス','匿名の','It is an anonymous call.','それは匿名電話だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['anonymous']),
('ant','アント','アリ','Look at the ant.','アリを見なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ant']),
('anticipate','アンティシペイト','予想する','I anticipate a change.','変化を予想している。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['anticipate','predict']),
('antique','アンティーク','骨董品の','It is an antique chair.','それは骨董品の椅子だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['antique']),
('anxious','アンクシャス','心配して、切望して','I am anxious about you.','君のことを心配している。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['anxious']),
('anybody','エニバディ','誰か','Is anybody here?','誰かいますか。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['anybody','anyone']),
('apart','アパート','離れて','Stand apart.','離れて立ちなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['apart']),
('apologize','アポロジャイズ','謝罪する','I must apologize.','謝罪しなければならない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['apologize']),
('apology','アポロジー','謝罪','I accept your apology.','君の謝罪を受け入れる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['apology']),
('apparatus','アパラタス','器具、装置','The apparatus is ready.','装置の準備ができている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['apparatus']),
('apparent','アパレント','明白な','It is apparent to all.','それは誰にも明白だ。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['apparent','obvious']),
('appeal','アピール','訴える、魅力','He appealed for help.','彼は助けを訴えた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['appeal']),
('appearance','アピアランス','出現、外見','Judge by appearance.','外見で判断しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['appearance']),
('append','アペンド','付け加える','Append the note.','注釈を付け加えなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['append']),
('appetite','アペタイト','食欲','I have no appetite.','食欲がない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['appetite']),
('applaud','アプロード','拍手する','They applauded him.','彼らは彼に拍手した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['applaud']),
('applause','アプローズ','拍手','Thunderous applause.','割れんばかりの拍手。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['applause']),
('applicable','アプリカブル','適用できる','This rule is applicable.','この規則は適用できる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['applicable']),
('applicant','アプリカント','志願者','He is an applicant.','彼は志願者だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['applicant']),
('application','アプリケーション','申請、応用','Send your application.','申請を送りなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['application']),
('apply','アプライ','申し込む、適用する','Apply for the job.','その仕事に申し込みなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['apply']),
('appoint','アポイント','任命する','They appointed him.','彼らは彼を任命した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['appoint']),
('appointment','アポイントメント','予約、約束','I have an appointment.','予約がある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['appointment']),
('appreciate','アプリシエイト','感謝する、真価を認める','I appreciate your help.','助けてくれて感謝する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['appreciate']),
('approach','アプローチ','近づく、取り組み','Approach the house.','その家に近づきなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['approach']),
('appropriate','アプロプリエイト','適切な','It is an appropriate gift.','それは適切な贈り物だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['appropriate']),
('approval','アプルーヴァル','承認','I need your approval.','承認が必要です。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['approval']),
('approve','アプルーヴ','承認する','They approved the plan.','彼らは計画を承認した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['approve']),
('approximate','アプロクシメイト','おおよその','Give me an approximate cost.','おおよその費用を教えて。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['approximate']),
('approximately','アプロクシメイトリー','おおよそ','It takes approximately one hour.','おおよそ1時間かかる。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['approximately','about']),
('apt','アプト','〜しがちな、適切な','He is apt to forget.','彼は忘れがちだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['apt']),
('arbitrary','アービトラリー','任意の、独断的な','It was an arbitrary decision.','それは独断的な決定だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['arbitrary']),
('architecture','アーキテクチャー','建築','I like modern architecture.','現代建築が好きだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['architecture']),
('ardent','アーダント','熱心な','He is an ardent fan.','彼は熱心なファンだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ardent']),
('argue','アーギュー','論争する、主張する','Don''t argue with me.','私と論争しないで。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['argue']),
('argument','アーギュメント','論争、議論','They had an argument.','彼らは議論をした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['argument']),
('arise','アライズ','起こる、生じる','Problems may arise.','問題が生じるかもしれない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['arise']),
('arithmetic','アリスメティック','算数','Practice arithmetic.','算数を練習しなさい。','中2','難関','premium',false,ARRAY['高校受験'],ARRAY['arithmetic']),
('armchair','アームチェア','ひじ掛け椅子','Sit in the armchair.','ひじ掛け椅子に座りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['armchair']),
('arouse','アロウズ','喚起する','It aroused my interest.','それが私の興味を喚起した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['arouse']),
('arrange','アレインジ','準備する、手配する','Arrange a meeting.','会議を手配しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['arrange']),
('arrangement','アレインジメント','準備、手配','Make travel arrangements.','旅行の準備をしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['arrangement']),
('arrest','アレスト','逮捕する','The police arrested him.','警察が彼を逮捕した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['arrest']),
('arrival','アライヴァル','到着','I wait for his arrival.','彼の到着を待っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['arrival']),
('arrogant','アロガント','傲慢な','Don''t be so arrogant.','そんなに傲慢にならないで。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['arrogant']),
('arrow','アロウ','矢、矢印','Follow the arrow.','矢印に従いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['arrow']),
('artery','アーテリー','動脈','This is a main artery.','これは主要な動脈だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['artery']),
('article','アーティクル','記事、品物','I read the article.','その記事を読んだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['article']),
('articulate','アーティキュレイト','はっきりと述べる','He articulated his views.','彼は自分の見解をはっきりと述べた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['articulate']),
('artificial','アーティフィシャル','人工の','It is artificial light.','それは人工の光だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['artificial']),
('ascent','アセント','上昇、登ること','The ascent was difficult.','登ることは困難だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ascent']),
('ascertain','アサテイン','確かめる','Ascertain the truth.','真実を確かめなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['ascertain','find out']),
('ascribe','アスクライブ','〜のせいにする','Ascribe it to luck.','それを運のせいにする。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ascribe']),
('ash','アッシュ','灰','There is a lot of ash.','灰がたくさんある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ash']),
('ashamed','アシェイムド','恥じて','I am ashamed of myself.','自分を恥じている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['ashamed']),
('aside','アサイド','わきに','Put it aside.','それをわきに置きなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['aside']),
('aspect','アスペクト','側面、観点','Consider every aspect.','すべての側面を考慮しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['aspect']),
('aspiration','アスピレーション','熱望、抱負','He has high aspirations.','彼には高い抱負がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['aspiration']),
('aspire','アスパイア','熱望する','He aspires to be a doctor.','彼は医者になることを熱望している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['aspire']),
('assault','アソルト','襲撃、強襲','He led an assault.','彼は襲撃を指揮した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assault']),
('assemble','アセンブル','組み立てる、集まる','Assemble the parts.','部品を組み立てなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assemble']),
('assembly','アセンブリ','組み立て、集会','Attend the assembly.','集会に出席しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assembly']),
('assert','アサート','主張する','Assert your rights.','自分の権利を主張しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assert']),
('assertion','アサーション','主張','Read his assertion.','彼の主張を読みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assertion']),
('assess','アセス','評価する、査定する','Assess the situation.','状況を評価しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assess']),
('assessment','アセスメント','評価、査定','The assessment is good.','その評価は良い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assessment']),
('asset','アセット','資産、財産','He has many assets.','彼は多くの資産を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['asset']),
('assign','アサイン','割り当てる','Assign the task.','その仕事を割り当てなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assign']),
('assignment','アサインメント','割り当て、宿題','Finish the assignment.','宿題を終わらせなさい。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['assignment','homework']),
('assist','アシスト','助ける','He assisted me.','彼は私を助けてくれた。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['assist','help']),
('assistance','アシスタンス','援助、支援','I need your assistance.','あなたの援助が必要です。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['assistance']),
('assistant','アシスタント','助手、アシスタント','He is my assistant.','彼は私の助手だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['assistant']),
('associate','アソシエイト','関連づける、仲間','Do not associate with them.','彼らと関わってはいけない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['associate']),
('association','アソシエーション','協会、関連','Join the association.','その協会に参加しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['association']),
('assume','アシューム','想定する','I assume it is true.','それが真実だと想定している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assume']),
('assumption','アサンプション','想定、仮定','Based on an assumption.','想定に基づいて。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assumption']),
('assurance','アシュアランス','保証、確信','I need an assurance.','保証が必要です。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assurance']),
('assure','アシュア','保証する、確信させる','I assure you.','保証します。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['assure']),
('astonish','アストニッシュ','驚かせる','It astonished me.','それは私を驚かせた。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['astonish','surprise']),
('astonishing','アストニッシング','驚くべき','It is an astonishing fact.','それは驚くべき事実だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['astonishing']),
('astronomy','アストロノミー','天文学','He studies astronomy.','彼は天文学を学んでいる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['astronomy']),
('asylum','アサイラム','避難所、亡命','He sought asylum.','彼は亡命を求めた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['asylum']),
('athlete','アスリート','運動選手','He is a great athlete.','彼は偉大な選手だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['athlete']),
('atmosphere','アトモスフィア','大気、雰囲気','The atmosphere is heavy.','雰囲気が重い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['atmosphere']),
('atom','アトム','原子','Everything is made of atoms.','すべてのものは原子からできている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['atom']),
('atomic','アトミック','原子の','It is atomic energy.','それは原子力だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['atomic']),
('attach','アタッチ','取り付ける','Attach the label.','ラベルを取り付けなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['attach']),
('attachment','アタッチメント','取り付け、愛着','He has deep attachment.','彼は深い愛着を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['attachment']),
('attain','アテイン','達成する','Attain your goal.','目標を達成しなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['attain','achieve']),
('attempt','アテンプト','試みる、試み','Make an attempt.','試みなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['attempt','try']),
('attendance','アテンダンス','出席、出席者数','The attendance is low.','出席率が低い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['attendance']),
('attitude','アティチュード','態度','He has a good attitude.','彼は良い態度だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['attitude']),
('attorney','アトーニー','弁護士','Consult your attorney.','弁護士に相談しなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['attorney','lawyer']),
('attract','アトラクト','引きつける','It attracts attention.','それは注目を引きつける。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['attract']),
('attraction','アトラクション','魅力、呼び物','The park has attractions.','その公園にはアトラクションがある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['attraction']),
('attractive','アトラクティヴ','魅力的な','She is an attractive woman.','彼女は魅力的な女性だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['attractive']),
('attribute','アトリビュート','〜のせいにする、属性','Attribute it to luck.','それを運のせいにする。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['attribute']),
('auction','オークション','競売','It was sold at auction.','それは競売で売られた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['auction']),
('audience','オーディエンス','聴衆','The audience applauded.','聴衆が拍手した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['audience']),
('audio','オーディオ','音声の','The audio is clear.','音声がはっきりしている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['audio']),
('audit','オーディット','監査','Conduct an audit.','監査を実施しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['audit']),
('augment','オーグメント','増大させる','Augment your income.','収入を増大させなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['augment']),
('authentic','オーセンティック','本物の','It is an authentic painting.','それは本物の絵画だ。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['authentic','real']),
('author','オーサー','著者','Who is the author?','著者は誰ですか。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['author','writer']),
('authority','オーソリティ','権威、当局','He is an authority.','彼は権威者だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['authority']),
('authorize','オーソライズ','権限を与える','I authorized him.','彼に権限を与えた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['authorize']),
('auto','オート','自動車','I bought an auto.','自動車を買った。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['auto','car']),
('autobiography','オートバイオグラフィー','自伝','He wrote an autobiography.','彼は自伝を書いた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['autobiography']),
('automate','オートメイト','自動化する','Automate the process.','その過程を自動化しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['automate']),
('automatic','オートマティック','自動の','It is an automatic door.','それは自動ドアだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['automatic']),
('automobile','オートモービル','自動車','An automobile factory.','自動車工場。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['automobile','car']),
('autonomous','オートノマス','自律的な','It is an autonomous system.','それは自律的なシステムだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['autonomous']),
('autonomy','オートノミー','自治、自律','They demand autonomy.','彼らは自治を要求する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['autonomy']),
('avail','アヴェイル','役立つ','It was of no avail.','それは何の役にも立たなかった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['avail']),
('available','アヴェイラブル','利用可能な','Is it available now?','今利用可能ですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['available']),
('avenge','アヴェンジ','復讐する','Avenge the death.','死の復讐をしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['avenge']),
('avenue','アヴェニュー','大通り','Walk down the avenue.','その大通りを歩きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['avenue']),
('average','アヴェレッジ','平均、平均の','The average is ten.','平均は10だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['average']),
('avert','アヴァート','避ける','Avert the danger.','危険を避けなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['avert','avoid']),
('aviation','エイヴィエーション','航空','He works in aviation.','彼は航空業界で働いている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['aviation']),
('avoid','アヴォイド','避ける','Avoid mistakes.','間違いを避けなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['avoid']),
('await','アウェイト','待つ','Await the results.','結果を待ちなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['await','wait for']),
('award','アワード','賞、授与する','He won an award.','彼は賞を受けた。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['award','prize']),
('aware','アウェア','気づいて','I am aware of the risk.','リスクに気づいている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['aware']),
('awareness','アウェアネス','自覚、意識','Raise public awareness.','公共の意識を高めなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['awareness']),
('awful','オーフル','ひどい','It was an awful day.','ひどい一日だった。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['awful','terrible']),
('awkward','オークワッド','気まずい、不器用な','It was an awkward silence.','気まずい沈黙だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['awkward']),
('axis','アクシス','軸','The earth rotates on its axis.','地球はその軸で回転する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['axis']),
('axle','アクスル','車軸','The axle is broken.','車軸が壊れている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['axle']),
('bachelor','バチェラー','独身者、学士','He is a bachelor.','彼は独身だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bachelor']),
('backbone','バックボーン','背骨、気骨','He has backbone.','彼には気骨がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['backbone']),
('background','バックグラウンド','背景','The background is dark.','背景が暗い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['background']),
('bacteria','バクテリア','細菌','Bacteria cause disease.','細菌が病気を引き起こす。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bacteria']),
('badge','バッジ','バッジ、記章','He wears a badge.','彼はバッジをつけている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['badge']),
('badly','バッドリー','ひどく','I need it badly.','ひどくそれが必要だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['badly']),
('baggage','バゲッジ','手荷物','Check your baggage.','荷物を預けなさい。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['baggage','luggage']),
('balance','バランス','均衡、バランス','Keep your balance.','バランスを保ちなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['balance']),
('balloon','バルーン','風船','The balloon flew away.','風船が飛んでいった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['balloon']),
('ballot','バロット','投票、投票用紙','Cast your ballot.','投票しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ballot']),
('ban','バン','禁止する','They banned smoking.','彼らは喫煙を禁止した。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['ban','prohibit']),
('bandage','バンデージ','包帯','Apply a bandage.','包帯を巻きなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bandage']),
('bang','バン','バンと鳴る音','I heard a loud bang.','大きなバンという音を聞いた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bang']),
('banish','バニッシュ','追放する','They banished him.','彼らは彼を追放した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['banish']),
('bankrupt','バンク・ラプト','破産した','The company is bankrupt.','その会社は破産した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bankrupt']),
('banner','バナー','横断幕','Hang the banner.','横断幕を掛けなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['banner']),
('bar','バー','棒、酒場','A bar of soap.','石けん1個。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bar']),
('barbecue','バーベキュー','バーベキュー','Let''s have a barbecue.','バーベキューをしよう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['barbecue']),
('bare','ベア','裸の、むき出しの','His feet were bare.','彼の足は裸だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bare']),
('barely','ベアリー','かろうじて','I barely made it.','かろうじて間に合った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['barely']),
('bargain','バーゲン','取引、バーゲン品','It was a good bargain.','良い買い物だった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bargain']),
('bark','バーク','吠える、樹皮','The dog is barking.','犬が吠えている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bark']),
('barrel','バレル','樽','A barrel of wine.','ワイン1樽。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['barrel']),
('barren','バレン','不毛の','The land is barren.','その土地は不毛だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['barren']),
('barrier','バリアー','障壁','Break the barrier.','障壁を壊しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['barrier']),
('basement','ベースメント','地下室','He is in the basement.','彼は地下室にいる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['basement']),
('basin','ベイスン','洗面器、流域','Wash in the basin.','洗面器で洗いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['basin']),
('basis','ベイシス','基礎、根拠','There is no basis for it.','それには根拠がない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['basis']),
('basket','バスケット','かご','Put it in the basket.','かごに入れなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['basket']),
('bat','バット','バット、コウモリ','He uses a heavy bat.','彼は重いバットを使う。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['bat']),
('bathe','ベイズ','入浴させる','Bathe the baby.','赤ちゃんをお風呂に入れなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bathe']),
('battery','バッテリー','電池','Change the battery.','電池を交換しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['battery']),
('battle','バトル','戦闘、戦い','He fought in the battle.','彼は戦闘で戦った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['battle']),
('bay','ベイ','湾','The bay is calm.','その湾は穏やかだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bay']),
('beacon','ビーコン','灯台、合図','The beacon shone.','灯台が光った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['beacon']),
('bead','ビード','ビーズ、数珠','Make a bead necklace.','ビーズのネックレスを作りなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bead']),
('beak','ビーク','くちばし','The bird has a sharp beak.','その鳥は鋭いくちばしがある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['beak']),
('beam','ビーム','光線、ほほえむ','A beam of light.','一筋の光線。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['beam']),
('bean','ビーン','豆','I like eating beans.','豆を食べるのが好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bean']),
('beard','ビアード','あごひげ','He has a long beard.','彼は長いあごひげがある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['beard']),
('beast','ビースト','獣','The beast is wild.','その獣は野生だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['beast']),
('became','ビケイム','なった（becomeの過去形）','He became a doctor.','彼は医者になった。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['became']),
('bee','ビー','ハチ','A bee stung me.','ハチに刺された。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bee']),
('beer','ビア','ビール','He drinks beer.','彼はビールを飲む。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['beer']),
('beg','ベグ','懇願する','I beg your pardon.','すみません（お許しください）。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['beg']),
('began','ビガン','始めた（beginの過去形）','He began the work.','彼は仕事を始めた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['began']),
('begun','ビガン','始めた（beginの過去分詞）','The game has begun.','試合が始まっている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['begun']),
('behalf','ビハーフ','〜のために、代表して','On behalf of us all.','私たち全員を代表して。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['behalf']),
('behave','ビヘイヴ','振る舞う','Behave yourself.','行儀よくしなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['behave']),
('behavior','ビヘイヴィアー','振る舞い、行動','His behavior is good.','彼の振る舞いは良い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['behavior']),
('being','ビーイング','存在、人間','A human being.','人間（という存在）。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['being']),
('belief','ビリーフ','信念、信頼','It is my firm belief.','それは私の固い信念だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['belief']),
('belly','ベリー','腹','He has a big belly.','彼は大きな腹をしている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['belly']),
('beloved','ビラヴド','最愛の','My beloved daughter.','私の最愛の娘。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['beloved']),
('belt','ベルト','ベルト、帯','Tighten your belt.','ベルトを締めなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['belt']),
('bench','ベンチ','ベンチ','Sit on the bench.','ベンチに座りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bench']),
('bend','ベンド','曲げる','Bend your knees.','ひざを曲げなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bend']),
('beneath','ビニース','〜の下に','Beneath the surface.','表面の下に。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['beneath']),
('beneficial','ベネフィシャル','有益な','It is beneficial to health.','それは健康に有益だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['beneficial']),
('benefit','ベネフィット','利益、恩恵','I got many benefits.','多くの利益を得た。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['benefit']),
('bent','ベント','曲がった（bendの過去・過去分詞）','The stick is bent.','その棒は曲がっている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bent']),
('besides','ビサイズ','その上、〜に加えて','Besides, it is cheap.','その上、それは安い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['besides']),
('bet','ベット','賭ける','I bet it is true.','それが真実だと賭けるよ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bet']),
('betray','ビトレイ','裏切る','Do not betray me.','私を裏切ってはいけない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['betray']),
('beverage','ベヴリッジ','飲み物','What is your beverage?','飲み物は何ですか。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['beverage','drink']),
('beware','ビウェア','用心する','Beware of the dog.','犬に用心しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['beware']),
('beyond','ビヨンド','〜の向こうに','Beyond the mountain.','山の向こうに。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['beyond']),
('bias','バイアス','偏見','He has a bias.','彼には偏見がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bias']),
('bible','バイブル','聖書','He reads the bible.','彼は聖書を読んでいる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bible']),
('bid','ビッド','入札、命令','He made a bid.','彼は入札した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bid']),
('bike','バイク','自転車','I like my bike.','自分の自転車が好きだ。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['bike','bicycle']),
('bilateral','バイラテラル','双方向の','It is a bilateral deal.','それは双方の合意だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bilateral']),
('bind','バインド','縛る','Bind the book.','その本を製本しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bind']),
('biography','バイオグラフィー','伝記','He wrote a biography.','彼は伝記を書いた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['biography']),
('biological','バイオロジカル','生物学的な','It is a biological need.','それは生物学的な必要性だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['biological']),
('biology','バイオロジー','生物学','She studies biology.','彼女は生物学を学んでいる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['biology']),
('biscuit','ビスケット','ビスケット','Have a biscuit.','ビスケットを食べなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['biscuit']),
('bishop','ビショップ','主教','The bishop is kind.','主教は親切だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bishop']),
('bit','ビット','少し','A bit of salt.','少量の塩。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bit']),
('bitter','ビター','苦い','The medicine is bitter.','その薬は苦い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bitter']),
('blade','ブレイド','刃','The blade is sharp.','刃が鋭い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['blade']),
('blame','ブレイム','非難する、責任を負わせる','Don''t blame me.','私を責めないで。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['blame']),
('blank','ブランク','空白の','Fill in the blank.','空欄を埋めなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['blank']),
('blanket','ブランケット','毛布','Use a blanket.','毛布を使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['blanket']),
('blast','ブラスト','爆発、突風','The blast was loud.','爆発音が大きかった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['blast']),
('bleak','ブリーク','荒涼とした、寒々しい','The landscape is bleak.','風景が荒涼としている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bleak']),
('bleed','ブリード','出血する','My nose is bleeding.','鼻血が出ている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bleed']),
('blend','ブレンド','混ぜる','Blend the colors.','色を混ぜなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['blend','mix']),
('bless','ブレス','祝福する','God bless you.','神の祝福がありますように。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bless']),
('blessing','ブレッシング','恵み、祝福','It is a great blessing.','それは大きな恵みだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['blessing']),
('blink','ブリンク','まばたきする','Blink your eyes.','まばたきしなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['blink']),
('block','ブロック','ふさぐ、塊','Block the road.','道をふさぎなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['block']),
('blond','ブロンド','金髪の','She has blond hair.','彼女は金髪だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['blond']),
('bloom','ブルーム','花が咲く','The flowers are in bloom.','花が咲いている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bloom']),
('blossom','ブロッサム','花','Cherry blossoms are pretty.','桜の花はきれいだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['blossom']),
('blot','ブロット','しみ','There is an ink blot.','インクのしみがある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['blot']),
('blouse','ブラウス','ブラウス','She wears a blouse.','彼女はブラウスを着ている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['blouse']),
('blueprint','ブループリント','青写真、計画','Follow the blueprint.','青写真（計画）に従いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['blueprint']),
('blunder','ブランダー','大失敗','It was a big blunder.','それは大きな失敗だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['blunder']),
('blunt','ブラント','ぶっきらぼうな、鈍い','He is very blunt.','彼はとてもぶっきらぼうだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['blunt']),
('blur','ブラー','ぼやけさせる','Don''t blur the photo.','写真をぼやけさせないで。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['blur']),
('blush','ブラッシュ','赤面する','She blushed.','彼女は赤面した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['blush']),
('boast','ボースト','自慢する','Don''t boast.','自慢してはいけない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['boast']),
('boil','ボイル','沸騰する','Boil the water.','水を沸騰させなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['boil']),
('bold','ボールド','大胆な','He is bold.','彼は大胆だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bold']),
('bolt','ボルト','ボルト、戸締り','Check the bolt.','ボルトを確認しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bolt']),
('bomb','ボム','爆弾','The bomb exploded.','爆弾が爆発した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bomb']),
('bond','ボンド','きずな、債券','A strong bond.','強いきずな。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bond']),
('bonus','ボーナス','賞与、特典','He got a bonus.','彼はボーナスをもらった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bonus']),
('booking','ブッキング','予約','Check your booking.','予約を確認しなさい。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['booking','reservation']),
('boom','ブーム','急成長、急騰','The economy is in a boom.','経済が急成長している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['boom']),
('boost','ブースト','促進する','Boost your energy.','活力を高めなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['boost']),
('boot','ブート','ブーツ','Wear boots.','ブーツを履きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['boot']),
('border','ボーダー','国境','Cross the border.','国境を越えなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['border']),
('bore','ボア','退屈させる','It bored me.','それは私を退屈させた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bore']),
('bored','ボード','退屈して','I am bored.','退屈だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bored']),
('boring','ボーリング','退屈な','It is a boring movie.','それは退屈な映画だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['boring']),
('born','ボーン','生まれた','I was born here.','ここで生まれた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['born']),
('botany','ボタニー','植物学','She studies botany.','彼女は植物学を学んでいる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['botany']),
('bottle','ボトル','びん','A bottle of water.','水1本。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['bottle']),
('bough','バウ','大きな枝','The bough broke.','大きな枝が折れた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bough']),
('bounce','バウンス','跳ね返る','The ball bounces.','ボールが跳ね返る。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bounce']),
('bound','バウンド','行こうとしている、縛られた','The train is bound for Tokyo.','その電車は東京行きだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bound']),
('boundary','バウンダリー','境界','Set the boundary.','境界を設定しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['boundary']),
('bouquet','ブーケ','花束','She received a bouquet.','彼女は花束を受け取った。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bouquet']),
('bout','バウト','試合、期間','A boxing bout.','ボクシングの試合。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bout']),
('bow','ボウ','お辞儀する、弓','Bow before the king.','王の前でお辞儀しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bow']),
('bowl','ボウル','ボウル、鉢','Use a bowl.','ボウルを使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bowl']),
('boycott','ボイコット','ボイコットする','They boycotted it.','彼らはそれをボイコットした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['boycott']),
('brace','ブレイス','支える','Brace yourself.','心構えしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brace']),
('bracelet','ブレスレット','ブレスレット','Wear a bracelet.','ブレスレットをつけなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bracelet']),
('bracket','ブラケット','括弧、棚受け','Put it in brackets.','括弧に入れなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['bracket']),
('brag','ブラグ','自慢する','He is always bragging.','彼はいつも自慢している。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['brag','boast']),
('braid','ブレイド','編む、三つ編み','Braid your hair.','髪を編みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['braid']),
('brake','ブレイク','ブレーキ','Hit the brake.','ブレーキをかけなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['brake']),
('brand','ブランド','ブランド、銘柄','What brand is it?','どこのブランドですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['brand']),
('brass','ブラス','真鍮','It is made of brass.','それは真鍮製だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brass']),
('breach','ブリーチ','違反、侵害','It is a breach of rules.','それは規則違反だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['breach']),
('breakdown','ブレイクダウン','故障、内訳','The breakdown is sad.','故障は残念だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['breakdown']),
('breakthrough','ブレイクスルー','飛躍的進歩','A major breakthrough.','大きな飛躍的進歩。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['breakthrough']),
('breast','ブレスト','胸','He hit his breast.','彼は自分の胸をたたいた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['breast']),
('breath','ブレス','息','Take a deep breath.','深呼吸しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['breath']),
('breathe','ブリーズ','呼吸する','Breathe in deeply.','深く息を吸いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['breathe']),
('breathtaking','ブレステイキング','息をのむような','The view is breathtaking.','景色が息をのむほど美しい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['breathtaking']),
('breed','ブリード','繁殖する、品種','They breed dogs.','彼らは犬を繁殖させる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['breed']),
('breeze','ブリーズ','そよ風','A gentle breeze.','心地よいそよ風。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['breeze']),
('brew','ブルー','醸造する、いれる','Brew some coffee.','コーヒーをいれなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brew']),
('bribe','ブライブ','賄賂','He offered a bribe.','彼は賄賂を渡した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bribe']),
('brick','ブリック','れんが','Build with bricks.','れんがで建てなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['brick']),
('bride','ブライド','花嫁','She is a pretty bride.','彼女はかわいい花嫁だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bride']),
('brief','ブリーフ','短い、簡潔な','Keep it brief.','簡潔にしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['brief']),
('briefly','ブリーフリー','簡潔に','Speak briefly.','簡潔に話しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['briefly']),
('brilliant','ブリリアント','すばらしい、光り輝く','It is a brilliant idea.','それは素晴らしい考えだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brilliant']),
('brim','ブリム','ふち','Fill to the brim.','ふちまで満たしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brim']),
('brink','ブリンク','瀬戸際','On the brink of disaster.','災難の瀬戸際に。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brink']),
('brisk','ブリスク','活発な','A brisk walk.','活発な散歩。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brisk']),
('brittle','ブリトル','もろい','The glass is brittle.','そのガラスはもろい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brittle']),
('broad','ブロード','広い','A broad street.','広い通り。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['broad','wide']),
('broadcast','ブロードキャスト','放送する','Broadcast the news.','ニュースを放送しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['broadcast']),
('brochure','ブロシュア','パンフレット','Read the brochure.','パンフレットを読みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['brochure']),
('broken','ブロークン','壊れた','The cup is broken.','コップが壊れている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['broken']),
('broker','ブローカー','仲介人','Consult a broker.','仲介人に相談しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['broker']),
('bronze','ブロンズ','青銅、ブロンズ','He won bronze.','彼は銅メダルを取った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bronze']),
('brook','ブルック','小川','Cross the brook.','小川を渡りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brook']),
('broom','ブルーム','ほうき','Use the broom.','ほうきを使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['broom']),
('broth','ブロス','だし汁','Drink the broth.','だし汁を飲みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['broth']),
('brow','ブラウ','眉、額','He wiped his brow.','彼は額を拭いた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brow']),
('browse','ブラウズ','閲覧する','Browse the web.','ウェブを閲覧しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['browse']),
('bruise','ブルーズ','打ち身、青あざ','I have a bruise.','打ち身がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bruise']),
('brutal','ブルータル','残忍な','It was a brutal attack.','それは残忍な攻撃だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['brutal']),
('bubble','バブル','泡','The bubble popped.','泡がはじけた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bubble']),
('buckle','バックル','バックル、締め金','Fasten the buckle.','バックルを締めなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['buckle']),
('bud','バッド','つぼみ','The buds are opening.','つぼみが開いている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bud']),
('budget','バジェット','予算','We have a small budget.','予算が少ない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['budget']),
('buffalo','バッファロー','水牛','The buffalo is large.','その水牛は大きい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['buffalo']),
('bug','バグ','虫、欠陥','Fix the bug.','バグを修正しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bug']),
('builder','ビルダー','建築業者','Ask the builder.','建築業者に聞きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['builder']),
('bulb','バルブ','電球、球根','Change the bulb.','電球を交換しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bulb']),
('bulk','バルク','大部分、巨大なもの','The bulk of the work.','仕事の大部分。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bulk']),
('bull','ブル','雄牛','The bull is strong.','その雄牛は強い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bull']),
('bullet','ブレット','弾丸','A bullet hit the wall.','弾丸が壁に当たった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bullet']),
('bulletin','ブレティン','会報、掲示','Read the bulletin.','掲示を読みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bulletin']),
('bump','バンプ','ぶつかる','I bumped into him.','彼とぶつかった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bump']),
('bunch','バンチ','束','A bunch of keys.','鍵の束。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bunch']),
('bundle','バンドル','束','A bundle of paper.','紙の束。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bundle']),
('burden','バーデン','負担','It is a heavy burden.','それは重い負担だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['burden']),
('bureau','ビューロー','局、事務所','Work at the bureau.','局で働きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bureau']),
('burglar','バーグラー','強盗','A burglar broke in.','強盗が押し入った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['burglar']),
('burial','ベリアル','埋葬','Attend the burial.','埋葬に出席しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['burial']),
('burst','バースト','破裂する','The balloon burst.','風船が破裂した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['burst']),
('bury','ベリー','埋める','Bury it in the sand.','それを砂に埋めなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bury']),
('bush','ブッシュ','茂み','He hid in the bushes.','彼は茂みに隠れた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bush']),
('businessman','ビジネスマン','実業家','He is a successful businessman.','彼は成功した実業家だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['businessman']),
('bust','バスト','破壊する、失敗','The deal went bust.','取引が失敗した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bust']),
('butcher','ブッチャー','肉屋','Go to the butcher.','肉屋へ行きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['butcher']),
('butt','バット','突き飛ばす','The goat butted me.','ヤギが私を突き飛ばした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['butt']),
('butterfly','バタフライ','チョウ','The butterfly is pretty.','そのチョウはきれいだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['butterfly']),
('buyer','バイヤー','買い手','Find a buyer.','買い手を見つけなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['buyer']),
('buzz','バズ','ぶんぶんいう','The bees are buzzing.','ハチがぶんぶんいっている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['buzz']),
('bypass','バイパス','迂回する','Bypass the city.','市街地を迂回しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['bypass']),
('byte','バイト','バイト（データ単位）','A thousand bytes.','1000バイト。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['byte']),
('cabin','キャビン','小屋、客室','A small log cabin.','小さな丸太小屋。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cabin']),
('cabinet','キャビネット','戸棚、内閣','Put it in the cabinet.','戸棚に入れなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cabinet']),
('cable','ケーブル','ケーブル','Connect the cable.','ケーブルを接続しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cable']),
('cactus','カクタス','サボテン','The cactus has thorns.','そのサボテンにはとげがある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cactus']),
('cadet','カデット','士官候補生','He is a cadet.','彼は士官候補生だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cadet']),
('cafeteria','カフェテリア','食堂','Eat in the cafeteria.','食堂で食べなさい。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['cafeteria','canteen']),
('cage','ケージ','おり','Put the bird in a cage.','鳥をおりに入れなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cage']),
('calculate','カルキュレイト','計算する','Calculate the total.','合計を計算しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['calculate']),
('calculation','カルキュレーション','計算','The calculation is right.','その計算は正しい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['calculation']),
('calculator','カルキュレーター','計算機','Use a calculator.','計算機を使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['calculator']),
('calendar','カレンダー','カレンダー','Check the calendar.','カレンダーを確認しなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['calendar']),
('calf','カーフ','子牛、ふくらはぎ','The calf is small.','その子牛は小さい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['calf']),
('caliber','カリバー','能力、口径','A man of high caliber.','高能力の人。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['caliber']),
('calibrate','カリブレイト','目盛りを合わせる','Calibrate the device.','装置の目盛りを合わせなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['calibrate']),
('calm','カーム','穏やかな','Keep calm.','落ち着いていなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['calm']),
('calorie','カロリー','カロリー','It has many calories.','それはカロリーが高い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['calorie']),
('campaign','キャンペーン','活動、運動','Start a campaign.','キャンペーンを始めなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['campaign']),
('canal','カナル','運河','The canal is deep.','その運河は深い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['canal']),
('cancellation','キャンセレーション','取り消し','Send a cancellation.','取り消しを送りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cancellation']),
('candidate','キャンディデイト','候補者','He is a candidate.','彼は候補者だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['candidate']),
('candle','キャンドル','ろうそく','Light a candle.','ろうそくに火をつけなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['candle']),
('cane','ケイン','杖','He uses a cane.','彼は杖を使っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cane']),
('canine','ケーナイン','犬の','Canine teeth.','犬歯。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['canine']),
('canteen','キャンティーン','食堂、水筒','The canteen is open.','食堂が開いている。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['canteen','cafeteria']),
('canvas','キャンヴァス','キャンバス','Paint on canvas.','キャンバスに描きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['canvas'])
ON CONFLICT (word) DO NOTHING;
