-- 高校受験語彙 追加分(a-c) part 2・冪等
INSERT INTO words (word, reading, meaning, example_en, example_ja, grade, level, tier, is_idiom, tags, answers_en) VALUES
('canvass','キャンヴァス','勧誘する、調査する','Canvass for votes.','投票を求めて勧誘しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['canvass']),
('canyon','キャニオン','峡谷','The canyon is deep.','その峡谷は深い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['canyon']),
('cap','キャップ','帽子、ふた','Put the cap on.','ふたを閉めなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cap']),
('capability','ケイパビリティ','能力','He has the capability.','彼には能力がある。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['capability','ability']),
('capable','ケイパブル','能力がある','He is capable of it.','彼はそれをやる能力がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['capable']),
('capacity','カパシティ','収容能力','Full capacity.','満員（収容能力いっぱい）。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['capacity']),
('cape','ケープ','岬','The cape is rocky.','その岬は岩が多い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cape']),
('caption','キャプション','見出し、説明文','Read the caption.','説明文を読みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['caption']),
('captive','キャプティヴ','捕虜','The captive escaped.','その捕虜が逃げた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['captive']),
('capture','キャプチャー','捕らえる','Capture the flag.','旗を奪いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['capture']),
('caravan','キャラヴァン','キャラバン、隊商','The caravan moved.','隊商が移動した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['caravan']),
('carbon','カーボン','炭素','Carbon is an element.','炭素は元素だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['carbon']),
('cardboard','カードボード','厚紙、段ボール','A cardboard box.','段ボール箱。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cardboard']),
('cardiac','カーディアック','心臓の','Cardiac disease.','心疾患。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cardiac']),
('career','キャリア','職業、経歴','He has a long career.','彼は長い経歴がある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['career']),
('careless','ケアレス','不注意な','Don''t be careless.','不注意にならないで。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['careless']),
('cargo','カーゴ','貨物','Load the cargo.','貨物を積み込みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cargo']),
('caricature','カリカチュア','風刺画','He drew a caricature.','彼は風刺画を描いた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['caricature']),
('carnival','カーニヴァル','カーニバル、祭り','The carnival is fun.','カーニバルは楽しい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['carnival']),
('carpenter','カーペンター','大工','Ask the carpenter.','大工に頼みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['carpenter']),
('carpet','カーペット','じゅうたん','Clean the carpet.','じゅうたんを掃除しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['carpet']),
('carriage','キャリッジ','馬車、車両','The carriage stopped.','馬車が止まった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['carriage']),
('carrier','キャリアー','運送人、キャリア','Contact the carrier.','運送人に連絡しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['carrier']),
('carrot','キャロット','ニンジン','I eat carrots.','ニンジンを食べる。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['carrot']),
('cart','カート','荷車、カート','Push the cart.','カートを押しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cart']),
('cartoon','カートゥーン','漫画、アニメ','Watch a cartoon.','漫画を見なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cartoon']),
('carve','カーヴ','彫る','Carve the wood.','その木を彫りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['carve']),
('cash','キャッシュ','現金','Do you have cash?','現金を持っていますか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cash']),
('casino','カジノ','カジノ','He visited the casino.','彼はカジノを訪れた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['casino']),
('casket','キャスケット','小箱、ひつぎ','The casket is old.','その小箱は古い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['casket']),
('cast','キャスト','投げる、配役','Cast the net.','網を投げなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cast']),
('castle','キャッスル','城','The castle is beautiful.','その城は美しい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['castle']),
('casual','カジュアル','気軽な、何気ない','It is a casual dress.','それはカジュアルな服だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['casual']),
('catalog','カタログ','カタログ','Check the catalog.','カタログを確認しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['catalog']),
('catastrophe','カタストロフィー','大惨事','It was a catastrophe.','それは大惨事だった。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['catastrophe','disaster']),
('category','カテゴリー','分類','What is the category?','カテゴリーは何ですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['category']),
('cater','ケーター','まかなう','Cater for the party.','パーティーの料理をまかないなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cater']),
('caterpillar','キャタピラー','イモムシ','The caterpillar is green.','そのイモムシは緑色だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['caterpillar']),
('cathedral','カテドラル','大聖堂','Visit the cathedral.','大聖堂を訪れなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cathedral']),
('catholic','カソリック','カトリックの','He is a catholic.','彼はカトリック教徒だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['catholic']),
('cattle','キャトル','牛、家畜','The cattle are grazing.','家畜が草を食べている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cattle']),
('caution','コーション','用心、警告','Proceed with caution.','用心して進みなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['caution']),
('cautious','コーシャス','慎重な','He is very cautious.','彼はとても慎重だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cautious']),
('cavalry','キャヴァルリー','騎兵隊','The cavalry arrived.','騎兵隊が到着した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cavalry']),
('cave','ケイヴ','洞窟','They entered the cave.','彼らは洞窟に入った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cave']),
('cavern','キャヴァーン','巨大な洞窟','The cavern is dark.','その洞窟は暗い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cavern']),
('cavity','キャヴィティ','虫歯、空洞','I have a cavity.','虫歯がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cavity']),
('cease','シース','やめる、終わる','Cease fire.','射撃をやめなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cease']),
('cedar','シダー','杉','The cedar is tall.','その杉は高い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cedar']),
('ceiling','シーリング','天井','Look at the ceiling.','天井を見なさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['ceiling']),
('celebrate','セレブレイト','祝う','Celebrate his birthday.','彼の誕生日を祝いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['celebrate']),
('celebration','セレブレーション','祝い、祝典','A grand celebration.','盛大な祝典。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['celebration']),
('celebrity','セレブリティ','有名人','He is a celebrity.','彼は有名人だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['celebrity']),
('celestial','セレスティアル','空の、天体の','Celestial bodies.','天体。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['celestial']),
('cell','セル','細胞、小部屋','Every cell is alive.','すべての細胞が生きている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cell']),
('cellar','セラー','地下室','Go to the cellar.','地下室へ行きなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['cellar']),
('cello','チェロ','チェロ','He plays the cello.','彼はチェロを弾く。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cello']),
('cellular','セルラー','細胞の','Cellular structure.','細胞構造。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cellular']),
('cemetery','セメタリー','墓地','Visit the cemetery.','墓地を訪れなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['cemetery']),
('censor','センサー','検閲する','Censor the book.','その本を検閲しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['censor']),
('censure','センシュア','非難する','They censured him.','彼らは彼を非難した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['censure']),
('census','センサス','国勢調査','Conduct a census.','国勢調査を実施しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['census']),
('cent','セント','セント','It costs fifty cents.','50セントかかる。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cent']),
('centimeter','センチメーター','センチメートル','Ten centimeters.','10センチメートル。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['centimeter']),
('central','セントラル','中心の','The central part.','中心部分。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['central']),
('ceramic','セラミック','陶磁器の','It is a ceramic cup.','それは陶磁器のコップだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ceramic']),
('cereal','シリアル','穀物、シリアル','Eat cereal.','シリアルを食べなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cereal']),
('ceremony','セレモニー','式典','Attend the ceremony.','式典に出席しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['ceremony']),
('certificate','サーティフィケイト','証明書','Show your certificate.','証明書を見せなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['certificate']),
('certify','サーティファイ','証明する','Certify the result.','結果を証明しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['certify']),
('cessation','セセーション','中止、停止','The cessation of work.','仕事の中止。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cessation']),
('chain','チェイン','鎖、一連の','Break the chain.','鎖を壊しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chain']),
('chairman','チェアマン','議長','The chairman spoke.','議長が話した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chairman']),
('chalk','チョーク','白亜、チョーク','Use the chalk.','チョークを使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chalk']),
('challenge','チャレンジ','挑戦、課題','Face the challenge.','課題に立ち向かいなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['challenge']),
('chamber','チェンバー','部屋、室','The chamber is big.','その部屋は大きい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chamber']),
('champion','チャンピオン','優勝者','He is the champion.','彼が優勝者だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['champion']),
('championship','チャンピオンシップ','選手権','Win the championship.','選手権で勝ちなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['championship']),
('chancellor','チャンセラー','首相、学長','The chancellor spoke.','首相が話した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chancellor']),
('chandelier','シャンデリア','シャンデリア','The chandelier is bright.','シャンデリアが明るい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chandelier']),
('channel','チャンネル','海峡、水路','The English Channel.','英国海峡。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['channel']),
('chaos','ケイオス','大混乱','The room is in chaos.','部屋が大混乱だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chaos']),
('chapel','チャペル','礼拝堂','Visit the chapel.','礼拝堂を訪れなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['chapel']),
('chapter','チャプター','章','Read this chapter.','この章を読みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chapter']),
('characteristic','キャラクテリスティック','特徴','What is the characteristic?','特徴は何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['characteristic']),
('characterize','キャラクテライズ','特徴づける','Characterize the era.','その時代を特徴づけなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['characterize']),
('charge','チャージ','請求する、責任','Charge the battery.','電池を充電しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['charge']),
('charity','チャリティ','慈善','Give to charity.','慈善に寄付しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['charity']),
('charm','チャーム','魅力','She has a lot of charm.','彼女はとても魅力がある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['charm']),
('charming','チャーミング','魅力的な','It is a charming place.','それは魅力的な場所だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['charming']),
('chart','チャート','図表','Look at the chart.','図表を見なさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chart']),
('chase','チェイス','追う','Chase the cat.','猫を追いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chase']),
('chasm','カズム','裂け目、隔たり','A chasm in the ice.','氷の裂け目。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chasm']),
('chassis','シャシー','車台','The chassis is strong.','その車台は頑丈だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chassis']),
('chaste','チェイスト','貞淑な','She is chaste.','彼女は貞淑だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chaste']),
('chasten','チェイスン','懲らしめる','Chasten him.','彼を懲らしめなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chasten']),
('chastise','チャスタイズ','厳しく非難する','He chastised the boy.','彼はその少年を厳しく非難した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chastise']),
('chat','チャット','おしゃべりする','Let''s chat.','おしゃべりしよう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chat']),
('chatter','チャッター','ぺちゃくちゃ話す','Stop chattering.','ぺちゃくちゃ話すのをやめなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['chatter']),
('cheat','チート','だます、カンニングする','Don''t cheat on the test.','テストでカンニングしてはいけない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cheat']),
('cheek','チーク','ほお','She has red cheeks.','彼女はほおが赤い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cheek']),
('cheerful','チアフル','陽気な','He is a cheerful person.','彼は陽気な人だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['cheerful']),
('chef','シェフ','料理長','He is the head chef.','彼が料理長だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chef']),
('chemical','ケミカル','化学の','It is a chemical reaction.','それは化学反応だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['chemical']),
('chemist','ケミスト','化学者、薬剤師','He is a chemist.','彼は化学者だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['chemist']),
('chemistry','ケミストリー','化学','I study chemistry.','化学を学んでいる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chemistry']),
('cherish','チェリッシュ','大切にする','Cherish the memory.','その思い出を大切にしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cherish']),
('cherry','チェリー','サクランボ','I like cherries.','サクランボが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cherry']),
('chess','チェス','チェス','Let''s play chess.','チェスをしよう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chess']),
('chest','チェスト','胸、箱','He has a strong chest.','彼は胸がたくましい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chest']),
('chew','チュー','かむ','Chew your food well.','食べ物をよくかみなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chew']),
('chic','シック','粋な、シックな','She is very chic.','彼女はとても粋だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chic']),
('chick','チック','ひよこ','The chick is cute.','そのひよこはかわいい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chick']),
('chicken','チキン','鶏肉、臆病者','I eat chicken.','鶏肉を食べる。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['chicken']),
('chief','チーフ','主要な、長の','He is the chief editor.','彼が編集長だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['chief']),
('childhood','チャイルドフッド','子供時代','In my childhood.','私の子供時代に。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['childhood']),
('chill','チル','冷え、寒気','There is a chill in the air.','空気に冷気がある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['chill']),
('chilly','チリー','肌寒い','It is chilly today.','今日は肌寒い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chilly']),
('chimney','チムニー','煙突','Smoke rises from the chimney.','煙突から煙が出る。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['chimney']),
('chin','チン','あご','He has a strong chin.','彼はあごがしっかりしている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chin']),
('chip','チップ','欠片、欠ける','A chip of wood.','木の欠片。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chip']),
('chirp','チャープ','ちゅんちゅん鳴く','Birds are chirping.','鳥が鳴いている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chirp']),
('chisel','チゼル','のみ、彫刻刀','Use the chisel.','のみを使いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chisel']),
('choice','チョイス','選択','Make your choice.','選択しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['choice']),
('choir','クワイア','聖歌隊','He is in the choir.','彼は聖歌隊にいる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['choir']),
('choke','チョーク','窒息する','Don''t choke.','窒息してはいけない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['choke']),
('chop','チョップ','切る','Chop the meat.','肉を切りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chop']),
('chord','コード','和音','Play the chord.','和音を弾きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chord']),
('chore','チョア','雑用','Do your chores.','雑用をしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['chore']),
('chronic','クロニック','慢性の','It is a chronic illness.','それは慢性的な病気だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chronic']),
('chronicle','クロニクル','年代記','Read the chronicle.','年代記を読みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chronicle']),
('chuckle','チャックル','くすくす笑う','He chuckled.','彼はくすくす笑った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['chuckle']),
('churn','チャーン','激しく動く','The water churns.','水が激しく動く。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['churn']),
('cider','サイダー','リンゴ酒','Drink some cider.','リンゴ酒を飲みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cider']),
('cigar','シガー','葉巻','He smokes a cigar.','彼は葉巻を吸う。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cigar']),
('cigarette','シガレット','たばこ','Stop smoking cigarettes.','たばこをやめなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cigarette']),
('cinema','シネマ','映画館','Go to the cinema.','映画館へ行きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cinema']),
('cipher','サイファー','暗号','Solve the cipher.','暗号を解きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cipher']),
('circuit','サーキット','回路、一周','The circuit is closed.','回路が閉じている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['circuit']),
('circular','サーキュラー','円形の','A circular table.','円形のテーブル。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['circular']),
('circulate','サーキュレイト','循環する','Blood circulates.','血液が循環する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['circulate']),
('circulation','サーキュレーション','循環、流通','Good circulation.','良い循環。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['circulation']),
('circumference','サーカムファレンス','円周','Measure the circumference.','円周を測りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['circumference']),
('circumstance','サーカムスタンス','状況、事情','In these circumstances.','このような状況では。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['circumstance']),
('cite','サイト','引用する','Cite the source.','出典を引用しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cite']),
('citizenship','シティズンシップ','市民権','Apply for citizenship.','市民権を申請しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['citizenship']),
('civic','シヴィック','市民の、都市の','Civic duties.','市民の義務。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['civic']),
('civil','シヴィル','市民の、国内の','Civil rights.','市民権。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['civil']),
('civilization','シヴィライゼーション','文明','Ancient civilization.','古代文明。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['civilization']),
('clad','クラッド','〜で覆われた','He is clad in black.','彼は黒い服を着ている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clad']),
('claim','クレイム','主張する、要求する','He claims it is true.','彼はそれが真実だと主張する。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['claim']),
('clamor','クラマー','騒音、叫び','The clamor of the crowd.','群衆の叫び。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clamor']),
('clamp','クランプ','固定する','Clamp the wood.','その木を固定しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clamp']),
('clan','クラン','氏族、一族','The whole clan met.','一族全員が集まった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clan']),
('clandestine','クランデスティン','内密の','A clandestine meeting.','内密の会合。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clandestine']),
('clap','クラップ','手をたたく','Clap your hands.','手をたたきなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['clap']),
('clarify','クラリファイ','明確にする','Clarify your point.','要点を明確にしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clarify']),
('clarity','クラリティ','明快さ','Write with clarity.','明快に書きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clarity']),
('clash','クラッシュ','衝突する','They clashed.','彼らは衝突した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clash']),
('clasp','クラスプ','握りしめる、留め金','Clasp my hand.','私の手を握りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clasp']),
('classic','クラシック','古典的な、一流の','It is a classic story.','それは古典的な話だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['classic']),
('classical','クラシカル','古典の','Classical music.','クラシック音楽。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['classical']),
('classification','クラシフィケーション','分類','Follow the classification.','分類に従いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['classification']),
('classify','クラシファイ','分類する','Classify these books.','これらの本を分類しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['classify']),
('clause','クローズ','節、条項','Read the clause.','その条項を読みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clause']),
('claw','クロー','かぎ爪','The cat has sharp claws.','その猫には鋭いかぎ爪がある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['claw']),
('clay','クレイ','粘土','Use some clay.','粘土を使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['clay']),
('clean','クリーン','きれいな、掃除する','Keep it clean.','きれいに保ちなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['clean']),
('cleanse','クレンズ','洗浄する','Cleanse your skin.','肌を洗浄しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cleanse']),
('clench','クレンチ','食いしばる','Clench your fists.','拳を握りしめなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clench']),
('clergyman','クレージマン','聖職者','The clergyman spoke.','聖職者が話した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clergyman']),
('click','クリック','カチッと鳴る、クリック','Click the mouse.','マウスをクリックしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['click']),
('client','クライアント','依頼人、顧客','Meet the client.','依頼人に会いなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['client']),
('cliff','クリフ','崖','The cliff is high.','その崖は高い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cliff']),
('climate','クライメイト','気候','The climate is mild.','気候が穏やかだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['climate']),
('climax','クライマックス','頂点、最高潮','The climax is near.','最高潮が近い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['climax']),
('climb','クライム','登る','Climb the mountain.','山に登りなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['climb']),
('clinch','クリンチ','決着をつける','Clinch the victory.','勝利を決定づけなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clinch']),
('cling','クリング','しがみつく','Cling to the rope.','ロープにしがみつきなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cling']),
('clinic','クリニック','診療所','Go to the clinic.','診療所へ行きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['clinic']),
('clip','クリップ','切り抜く、留める','Clip the paper.','紙を留めなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['clip']),
('cloak','クローク','マント、隠す','Wear a cloak.','マントを着なさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cloak']),
('clod','クロッド','土塊','Throw a clod.','土塊を投げなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clod']),
('clog','クロッグ','詰まらせる','Clog the pipe.','パイプを詰まらせなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clog']),
('clone','クローン','複製、クローン','Create a clone.','クローンを作りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clone']),
('closet','クローゼット','戸棚、押入れ','Put it in the closet.','戸棚に入れなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['closet']),
('cloth','クロス','布','Use a piece of cloth.','布を1枚使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cloth']),
('clothe','クローズ','服を着せる','Clothe the children.','子供たちに服を着せなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clothe']),
('clout','クラウト','影響力、一撃','He has political clout.','彼は政治的影響力がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clout']),
('clove','クローヴ','丁子、割れ目','Add a clove.','丁子を加えなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clove']),
('clown','クラウン','道化師','The clown is funny.','その道化師は面白い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['clown']),
('clue','クルー','手がかり','Found a clue.','手がかりを見つけた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['clue']),
('clump','クランプ','塊','A clump of trees.','木の塊。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clump']),
('clumsy','クラムジー','不器用な','He is clumsy.','彼は不器用だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clumsy']),
('cluster','クラスター','集団、房','A cluster of grapes.','ブドウの房。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cluster']),
('clutch','クラッチ','しっかりつかむ','Clutch the bag.','かばんをしっかりつかみなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['clutch']),
('coach','コーチ','指導者、客車','The coach is strict.','コーチは厳しい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['coach']),
('coagulate','コアギュレイト','凝固する','The blood coagulates.','血液が凝固する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['coagulate']),
('coal','コール','石炭','Burn coal.','石炭を燃やしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['coal']),
('coarse','コース','粗い','The fabric is coarse.','その布地は粗い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['coarse']),
('coax','コークス','なだめる','Coax the child.','その子供をなだめなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['coax']),
('cobalt','コバルト','コバルト','Cobalt is a metal.','コバルトは金属だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cobalt']),
('cobra','コブラ','コブラ','Beware of the cobra.','コブラに用心しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cobra']),
('cock','コック','雄鶏','The cock crows.','雄鶏が鳴く。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cock']),
('cockpit','コックピット','操縦席','Enter the cockpit.','操縦席に入りなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cockpit']),
('cockroach','コックローチ','ゴキブリ','Kill the cockroach.','ゴキブリを殺しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['cockroach']),
('cocktail','カクテル','カクテル','Drink a cocktail.','カクテルを飲みなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['cocktail']),
('cocoa','ココア','ココア','Drink cocoa.','ココアを飲みなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['cocoa']),
('coconut','ココナッツ','ココナッツ','I like coconuts.','ココナッツが好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['coconut']),
('cocoon','コクーン','まゆ','The moth is in the cocoon.','蛾がまゆの中にいる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cocoon']),
('cod','コッド','タラ','I eat cod.','タラを食べる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cod']),
('code','コード','符号、暗号','Crack the code.','暗号を解きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['code']),
('codify','コディファイ','法典化する','Codify the rules.','規則を法典化しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['codify']),
('coexist','コイグジスト','共存する','We must coexist.','私たちは共存しなければならない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['coexist']),
('coffin','コフィン','ひつぎ','Carry the coffin.','ひつぎを運びなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['coffin']),
('cogent','コージェント','説得力のある','A cogent argument.','説得力のある議論。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cogent']),
('cognition','コグニション','認識','The cognition is slow.','認識が遅い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cognition']),
('cognitive','コグニティヴ','認識の','Cognitive skills.','認識スキル。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['cognitive']),
('coherent','コヒーレント','一貫した','A coherent story.','一貫した話。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['coherent']),
('coil','コイル','巻く、コイル','Coil the rope.','ロープを巻きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['coil']),
('coincide','コインサイド','同時に起こる','Events coincide.','出来事が同時に起こる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['coincide']),
('coincidence','コインシデンス','偶然の一致','It is a coincidence.','それは偶然の一致だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['coincidence']),
('coke','コーク','コークス','Use coke as fuel.','コークスを燃料として使いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['coke']),
('collaborate','コラボレイト','協力する','Collaborate on this.','これについて協力しなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['collaborate','cooperate']),
('collaboration','コラボレーション','協力','A great collaboration.','素晴らしい協力。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['collaboration']),
('collaborator','コラボレーター','協力者','He is a collaborator.','彼は協力者だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['collaborator']),
('collapse','コラップス','崩壊する','The building collapsed.','建物が崩壊した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['collapse']),
('collar','カラー','襟','Fasten your collar.','襟を留めなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['collar']),
('collate','コレイト','照合する','Collate the data.','データを照合しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['collate']),
('collateral','コラテラル','担保、付随的な','Provide collateral.','担保を提供しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['collateral']),
('colleague','カリーグ','同僚','Meet my colleague.','私の同僚に会いなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['colleague']),
('collection','コレクション','収集、コレクション','His stamp collection.','彼の切手コレクション。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['collection']),
('collective','コレクティヴ','集団の','A collective effort.','集団の努力。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['collective']),
('collide','コライド','衝突する','The cars collided.','車が衝突した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['collide']),
('collision','コリジョン','衝突','A bad collision.','ひどい衝突。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['collision']),
('colloquial','コロクイアル','口語の','Colloquial speech.','口語体。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['colloquial']),
('colonel','カーネル','大佐','The colonel spoke.','大佐が話した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['colonel']),
('colonial','コロニアル','植民地の','Colonial period.','植民地時代。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['colonial']),
('colonize','コロナイズ','植民地化する','They colonized it.','彼らはそれを植民地化した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['colonize']),
('colony','コロニー','植民地','It was a colony.','それは植民地だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['colony']),
('colorful','カラフル','カラフルな','The flowers are colorful.','その花はカラフルだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['colorful']),
('column','コラム','円柱、コラム','Read the column.','コラムを読みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['column']),
('coma','コーマ','昏睡','He is in a coma.','彼は昏睡状態だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['coma']),
('combat','コンバット','戦闘','Engage in combat.','戦闘に参加しなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['combat','battle']),
('combination','コンビネーション','組み合わせ','A good combination.','良い組み合わせ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['combination']),
('combine','コンバイン','結合する','Combine the liquids.','液体を混ぜ合わせなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['combine']),
('combust','コンバスト','燃焼する','The gas combusts.','ガスが燃焼する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['combust']),
('combustion','コンバスチョン','燃焼','Complete combustion.','完全燃焼。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['combustion']),
('comedy','コメディ','喜劇','I love comedy movies.','喜劇映画が大好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['comedy']),
('comely','カムリー','愛らしい','A comely girl.','愛らしい少女。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['comely']),
('comet','コメット','彗星','The comet is bright.','その彗星は明るい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['comet']),
('comfort','コンフォート','快適さ、慰める','Bring comfort.','慰めをもたらしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['comfort']),
('comic','コミック','漫画の、喜劇の','A comic book.','漫画本。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['comic']),
('comma','コマ','コンマ','Add a comma.','コンマを加えなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['comma']),
('command','コマンド','命令、指揮','Follow the command.','命令に従いなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['command']),
('commander','コマンダー','司令官','He is the commander.','彼が司令官だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['commander']),
('commemorate','コメモレイト','記念する','Commemorate the event.','その出来事を記念しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['commemorate']),
('commence','コメンス','始める','Commence the work.','仕事を始めなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['commence','begin']),
('commend','コメンド','賞賛する、推薦する','I commend your action.','あなたの行動を賞賛する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['commend']),
('comment','コメント','論評、コメント','Add a comment.','コメントを加えなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['comment']),
('commentary','コメンタリー','論評、解説','Read the commentary.','解説を読みなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['commentary']),
('commerce','コマース','商業','International commerce.','国際商業。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['commerce']),
('commercial','コマーシャル','商業の、広告','A commercial success.','商業的な成功。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['commercial']),
('commission','コミッション','委員会、委託','The commission met.','委員会が会合した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['commission']),
('commit','コミット','犯す、委ねる','Don''t commit a crime.','罪を犯してはいけない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['commit']),
('commitment','コミットメント','約束、責務','Make a commitment.','約束しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['commitment']),
('committee','コミッティー','委員会','The committee decided.','委員会が決めた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['committee']),
('commodious','コモーディアス','広々とした','A commodious room.','広々とした部屋。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['commodious']),
('commodity','コモディティ','商品','A daily commodity.','日用品。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['commodity']),
('commonwealth','コモンウェルス','連邦、共同体','The commonwealth works.','その連邦が機能している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['commonwealth']),
('commotion','コモーション','騒動','What is the commotion?','この騒動は何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['commotion']),
('commute','コミューン','通勤する','I commute by bus.','バスで通勤している。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['commute']),
('compact','コンパクト','小型の、密集した','It is a compact car.','それは小型車だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['compact']),
('companion','コンパニオン','仲間','A good companion.','良い仲間。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['companion']),
('comparable','コンパラブル','比較できる','It is comparable to that.','それはあれと比較できる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['comparable']),
('comparative','コンパラティヴ','比較の','A comparative study.','比較研究。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['comparative']),
('comparison','コンパリゾン','比較','A fair comparison.','公平な比較。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['comparison']),
('compartment','コンパートメント','仕切り、区画','A train compartment.','列車の区画。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compartment']),
('compass','コンパス','方位磁石','Use a compass.','方位磁石を使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['compass']),
('compassion','コンパッション','同情、思いやり','Show compassion.','思いやりを見せなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compassion']),
('compatible','コンパティブル','両立できる','They are compatible.','それらは両立できる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compatible']),
('compel','コンペル','強制する','They compelled him.','彼らは彼を強制した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compel']),
('compelling','コンペリング','説得力のある','A compelling reason.','説得力のある理由。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compelling']),
('compensate','コンペンセイト','埋め合わせる、補償する','Compensate the loss.','その損失を補償しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compensate']),
('compete','コンピート','競う','Compete with others.','他人と競いなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['compete']),
('competence','コンピテンス','能力','Show your competence.','自分の能力を示しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['competence']),
('competent','コンピテント','有能な','He is a competent worker.','彼は有能な働き手だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['competent']),
('competition','コンペティション','競争、競技会','Win the competition.','競技会で勝ちなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['competition']),
('competitive','コンペティティヴ','競争の激しい','It is a competitive field.','それは競争の激しい分野だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['competitive']),
('compile','コンパイル','編集する、集める','Compile the report.','レポートを編集しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compile']),
('complaint','コンプレイント','不平、苦情','Make a complaint.','苦情を言いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['complaint']),
('complement','コンプリメント','補足する、補う','Complement the work.','その仕事を補いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['complement']),
('completely','コンプリートリー','完全に','It is completely gone.','それは完全に消えた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['completely']),
('complex','コンプレックス','複雑な','It is a complex issue.','それは複雑な問題だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['complex']),
('complexity','コンプレキシティ','複雑さ','The complexity is high.','その複雑さは高い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['complexity']),
('complicate','コンプリケイト','複雑にする','Don''t complicate it.','それを複雑にしないで。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['complicate']),
('complicated','コンプリケイテッド','複雑な','It is a complicated rule.','それは複雑なルールだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['complicated']),
('compliment','コンプリメント','ほめ言葉','Give a compliment.','ほめ言葉を言いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compliment']),
('comply','コンプライ','従う','Comply with the rules.','規則に従いなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['comply']),
('component','コンポーネント','構成要素','A key component.','主要な構成要素。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['component']),
('compose','コンポーズ','構成する、作曲する','Compose a song.','曲を作曲しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compose']),
('composite','コンポジット','合成の','A composite image.','合成画像。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['composite']),
('composition','コンポジション','構成、作文','Write a composition.','作文を書きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['composition']),
('compound','コンパウンド','混合物、合成する','A chemical compound.','化学合成物。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compound']),
('comprehend','コンプリヘンド','理解する','Can you comprehend it?','それを理解できますか。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['comprehend','understand']),
('comprehension','コンプリヘンション','理解力','Reading comprehension.','読解力。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['comprehension']),
('comprehensive','コンプリヘンシヴ','包括的な','A comprehensive report.','包括的なレポート。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['comprehensive']),
('compress','コンプレス','圧縮する','Compress the file.','ファイルを圧縮しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compress']),
('comprise','コンプライズ','構成される','Comprise many parts.','多くの部品で構成される。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['comprise']),
('compromise','コンプロマイズ','妥協','Reach a compromise.','妥協に達しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compromise']),
('compulsion','コンパルション','強迫、強制','Under compulsion.','強制されて。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compulsion']),
('compulsory','コンパルソリー','義務的な','It is compulsory education.','それは義務教育だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['compulsory']),
('compute','コンピュート','計算する','Compute the total.','合計を計算しなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['compute','calculate']),
('comrade','コムレイド','仲間','He is my comrade.','彼は私の仲間だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['comrade']),
('conceal','コンシール','隠す','Conceal the secret.','秘密を隠しなさい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['conceal','hide']),
('concede','コンシード','認める、譲歩する','Concede the game.','試合を譲歩（棄権）しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['concede']),
('conceit','コンシート','うぬぼれ','He is full of conceit.','彼はうぬぼれでいっぱいだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['conceit']),
('conceive','コンシーヴ','思いつく、想像する','Conceive a new plan.','新しい計画を思いつきなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['conceive']),
('concentrate','コンセントレイト','集中する','Concentrate on study.','勉強に集中しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['concentrate']),
('concentration','コンセントレーション','集中','Need deep concentration.','深い集中が必要だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['concentration']),
('concept','コンセプト','概念','Understand the concept.','概念を理解しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['concept']),
('conception','コンセプション','概念、受胎','A new conception.','新しい概念。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['conception']),
('concern','コンサーン','心配、関係、関心事','That is my concern.','それは私の関心事だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['concern']),
('concerned','コンサーンド','心配して、関係して','I am concerned about it.','そのことを心配している。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['concerned']),
('concession','コンセッション','譲歩','Make a concession.','妥協（譲歩）しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['concession']),
('concise','コンサイス','簡潔な','Make it concise.','それを簡潔にしなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['concise']),
('conclude','コンクルード','結論を下す','Conclude the report.','レポートを締めくくりなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['conclude']),
('conclusion','コンクルージョン','結論','What is the conclusion?','結論は何ですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['conclusion']),
('conclusive','コンクルーシヴ','決定的な','A conclusive proof.','決定的な証拠。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['conclusive']),
('concord','コンコード','調和、一致','Live in concord.','調和して生きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['concord']),
('concrete','コンクリート','コンクリート、具体的な','Give a concrete example.','具体的な例を挙げなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['concrete']),
('concur','コンカー','同意する','I concur with you.','あなたに同意します。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['concur','agree']),
('concurrence','コンカレンス','一致、同時発生','In concurrence with you.','あなたと一致して。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['concurrence']),
('concuss','コンカス','脳震盪を起こさせる','The blow concussed him.','その打撃が彼を脳震盪させた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['concuss']),
('condemn','コンデム','非難する、宣告する','Condemn the violence.','暴力を非難しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['condemn']),
('condense','コンデンス','濃縮する','Condense the milk.','ミルクを濃縮しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['condense']),
('condescend','コンディセンド','謙遜する、へりくだる','He condescended to help.','彼はへりくだって助けてくれた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['condescend']),
('condiment','コンディメント','調味料','Add a condiment.','調味料を加えなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['condiment']),
('conditional','コンディショナル','条件付きの','A conditional offer.','条件付きの提案。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['conditional']),
('condolence','コンドーレンス','哀悼','Offer my condolences.','哀悼の意を表します。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['condolence']),
('condone','コンドン','許す','Don''t condone it.','それを許してはいけない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['condone']),
('conduce','コンデュース','寄与する','Conduce to health.','健康に寄与しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['conduce']),
('conducive','コンデューシヴ','寄与する','It is conducive to study.','それは勉強に寄与する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['conducive'])
ON CONFLICT (word) DO NOTHING;
