-- seed: tuika2 (idioms & vocabulary, 487 net-new entries)
-- generated 2026-06-28
INSERT INTO words (word, meaning, grade, level, is_idiom, answers_en, tier)
VALUES
  ('agree with', '〜に同意する、〜に賛成する', '中3', '標準', true, ARRAY['agree with'], 'premium'),
  ('deal with', '〜を処理する、〜に対処する', '中3', '難関', true, ARRAY['deal with','handle'], 'premium'),
  ('suffer from', '〜に苦しむ、〜を患う', NULL, '難関', true, ARRAY['suffer from'], 'premium'),
  ('participate in', '〜に参加する', '中3', '難関', true, ARRAY['participate in','take part in'], 'premium'),
  ('focus on', '〜に集中する、〜に焦点を合わせる', '中3', '標準', true, ARRAY['focus on','concentrate on'], 'premium'),
  ('lead to', '〜につながる、〜を引き起こす', '中3', '標準', true, ARRAY['lead to','cause'], 'premium'),
  ('result in', '〜という結果になる、〜をもたらす', NULL, '難関', true, ARRAY['result in'], 'premium'),
  ('consist of', '〜から成り立っている、〜で構成される', NULL, '難関', true, ARRAY['consist of','be made up of'], 'premium'),
  ('object to', '〜に反対する', NULL, '難関', true, ARRAY['object to','oppose'], 'premium'),
  ('rely on', '〜に頼る、〜を信頼する', '中3', '標準', true, ARRAY['rely on','depend on'], 'premium'),
  ('worry about', '〜について心配する', '中2', '基礎', true, ARRAY['worry about'], 'premium'),
  ('care for', '〜の世話をする、〜を好む', '中2', '標準', true, ARRAY['care for','look after'], 'premium'),
  ('graduate from', '〜を卒業する', '中3', '標準', true, ARRAY['graduate from'], 'premium'),
  ('run for', '〜に立候補する、〜へ走る', '中3', '標準', true, ARRAY['run for'], 'premium'),
  ('concentrate on', '〜に集中する', NULL, '難関', true, ARRAY['concentrate on','focus on'], 'premium'),
  ('prepare for', '〜の準備をする、〜に備える', '中3', '標準', true, ARRAY['prepare for','get ready for'], 'premium'),
  ('search for', '〜を探し求める', '中3', '標準', true, ARRAY['search for','look for'], 'premium'),
  ('apologize for', '〜のことを謝る、〜について謝罪する', '中3', '標準', true, ARRAY['apologize for'], 'premium'),
  ('blame A for B', 'BのことでAを責める、BをAのせいにする', NULL, '難関', true, ARRAY['blame A for B'], 'premium'),
  ('thank A for B', 'BのことでAに感謝する', '中1', '基礎', true, ARRAY['thank A for B'], 'premium'),
  ('praise A for B', 'BのことでAを褒める', '中3', '標準', true, ARRAY['praise A for B'], 'premium'),
  ('criticize A for B', 'BのことでAを批判する', NULL, '難関', true, ARRAY['criticize A for B'], 'premium'),
  ('punish A for B', 'BのことでAを罰する', '中3', '標準', true, ARRAY['punish A for B'], 'premium'),
  ('provide A with B', 'AにBを供給する、AにBを提供する', '中3', '標準', true, ARRAY['provide A with B','supply A with B'], 'premium'),
  ('supply A with B', 'AにBを供給する', '中3', '標準', true, ARRAY['supply A with B','provide A with B'], 'premium'),
  ('present A with B', 'AにBを贈る、AにBを呈する', '中3', '標準', true, ARRAY['present A with B'], 'premium'),
  ('share A with B', 'AをBと共有する、AをBと分かち合う', '中2', '基礎', true, ARRAY['share A with B'], 'premium'),
  ('equip A with B', 'AにBを備え付ける', NULL, '難関', true, ARRAY['equip A with B'], 'premium'),
  ('compare A with B', 'AをBと比較する', '中3', '標準', true, ARRAY['compare A with B','compare A to B'], 'premium'),
  ('mix A with B', 'AをBと混ぜる', '中2', '基礎', true, ARRAY['mix A with B'], 'premium'),
  ('combine A with B', 'AをBと組み合わせる、AをBと結合する', NULL, '難関', true, ARRAY['combine A with B'], 'premium'),
  ('communicate with', '〜と意思疎通を図る、〜と連絡を取り合う', '中3', '標準', true, ARRAY['communicate with'], 'premium'),
  ('replace A with B', 'AをBに取り替える、AをBと交換する', '中3', '標準', true, ARRAY['replace A with B'], 'premium'),
  ('prevent A from B', 'AがBするのを妨げる、AにBをさせない', '中3', '難関', true, ARRAY['prevent A from B','stop A from B'], 'premium'),
  ('keep A from B', 'AにBをさせない、AをBから遠ざける', '中3', '標準', true, ARRAY['keep A from B','prevent A from B'], 'premium'),
  ('stop A from B', 'AがBするのを止める、AにBをさせない', '中2', '標準', true, ARRAY['stop A from B','prevent A from B'], 'premium'),
  ('protect A from B', 'AをBから守る、AをBから保護する', '中3', '標準', true, ARRAY['protect A from B','defend A from B'], 'premium'),
  ('distinguish A from B', 'AをBと区別する、AとBを見分ける', NULL, '難関', true, ARRAY['distinguish A from B','tell A from B'], 'premium'),
  ('tell A from B', 'AとBを見分ける、AをBと区別する', '中2', '標準', true, ARRAY['tell A from B','distinguish A from B'], 'premium'),
  ('separate A from B', 'AをBから離す、AをBから切り離す', '中3', '標準', true, ARRAY['separate A from B'], 'premium'),
  ('free A from B', 'AをBから解放する', '中3', '標準', true, ARRAY['free A from B'], 'premium'),
  ('borrow A from B', 'AをBから借りる', '中1', '基礎', true, ARRAY['borrow A from B'], 'premium'),
  ('receive A from B', 'AをBから受け取る', '中3', '基礎', true, ARRAY['receive A from B'], 'premium'),
  ('regard A as B', 'AをBとみなす、AをBと考える', NULL, '難関', true, ARRAY['regard A as B','think of A as B'], 'premium'),
  ('think of A as B', 'AをBとみなす、AをBと考える', '中2', '標準', true, ARRAY['think of A as B','regard A as B'], 'premium'),
  ('look on A as B', 'AをBとみなす、AをBの目で見る', '中3', '標準', true, ARRAY['look on A as B','regard A as B'], 'premium'),
  ('define A as B', 'AをBと定義する', NULL, '難関', true, ARRAY['define A as B'], 'premium'),
  ('accept A as B', 'AをBとして受け入れる', '中3', '標準', true, ARRAY['accept A as B'], 'premium'),
  ('remind A of B', 'AにBを思い出させる', '中3', '標準', true, ARRAY['remind A of B'], 'premium'),
  ('inform A of B', 'AにBを知らせる、AにBを通知する', NULL, '難関', true, ARRAY['inform A of B','tell A about B'], 'premium'),
  ('accuse A of B', 'AをBの罪で告発する、AをBの理由で責める', NULL, '難関', true, ARRAY['accuse A of B'], 'premium'),
  ('rob A of B', 'AからBを奪う、AからBを強奪する', '中3', '標準', true, ARRAY['rob A of B'], 'premium'),
  ('deprive A of B', 'AからBを剥奪する、AからBを奪う', NULL, '難関', true, ARRAY['deprive A of B'], 'premium'),
  ('cure A of B', 'AのB（病気・癖）を治す', '中3', '標準', true, ARRAY['cure A of B'], 'premium'),
  ('clear A of B', 'AからBを取り除く、AからBを一掃する', '中3', '標準', true, ARRAY['clear A of B'], 'premium'),
  ('prefer A to B', 'BよりAを好む', '中3', '標準', true, ARRAY['prefer A to B'], 'premium'),
  ('devote A to B', 'A（時間・人生）をBに捧げる', NULL, '難関', true, ARRAY['devote A to B'], 'premium'),
  ('attribute A to B', 'AをBのせいにする、AをBの帰結とする', NULL, '難関', true, ARRAY['attribute A to B'], 'premium'),
  ('leave A for B', 'Bに向けてAを出発する、Aを出てBへ向かう', '中2', '基礎', true, ARRAY['leave A for B'], 'premium'),
  ('exchange A for B', 'AをBと交換する', '中3', '標準', true, ARRAY['exchange A for B'], 'premium'),
  ('mistake A for B', 'AをBと間違える、AをBと誤認する', '中3', '標準', true, ARRAY['mistake A for B'], 'premium'),
  ('take A for granted', 'Aを当然のことと思う', NULL, '難関', true, ARRAY['take A for granted'], 'premium'),
  ('turn A into B', 'AをBに変える、AをBに変化させる', '中3', '標準', true, ARRAY['turn A into B','change A into B'], 'premium'),
  ('change A into B', 'AをBに変える', '中2', '基礎', true, ARRAY['change A into B','turn A into B'], 'premium'),
  ('translate A into B', 'AをBに翻訳する', '中3', '標準', true, ARRAY['translate A into B'], 'premium'),
  ('divide A into B', 'AをBに分ける、AをBに分割する', '中3', '標準', true, ARRAY['divide A into B'], 'premium'),
  ('put A into practice', 'Aを実行に移す、Aを実践する', NULL, '難関', true, ARRAY['put A into practice'], 'premium'),
  ('make a speech', 'スピーチをする、演説する', '中2', '基礎', true, ARRAY['make a speech','give a speech'], 'premium'),
  ('make an effort', '努力する', '中3', '標準', true, ARRAY['make an effort'], 'premium'),
  ('make a promise', '約束する', '中2', '基礎', true, ARRAY['make a promise'], 'premium'),
  ('make progress', '進歩する、上達する', '中3', '標準', true, ARRAY['make progress'], 'premium'),
  ('make a difference', '違いを生む、影響を与える', '中3', '標準', true, ARRAY['make a difference'], 'premium'),
  ('take a look', 'ちょっと見る、目を向ける', '中1', '基礎', true, ARRAY['take a look','have a look'], 'premium'),
  ('take an exam', '試験を受ける', '中3', '基礎', true, ARRAY['take an exam','take a test'], 'premium'),
  ('take a chance', '一か八かやってみる、危険を冒す', NULL, '難関', true, ARRAY['take a chance'], 'premium'),
  ('take action', '行動を起こす、処置をとる', '中3', '標準', true, ARRAY['take action'], 'premium'),
  ('take responsibility', '責任を取る', NULL, '難関', true, ARRAY['take responsibility'], 'premium'),
  ('give a lecture', '講義をする、講演を行う', '中3', '標準', true, ARRAY['give a lecture'], 'premium'),
  ('give a ride', '（車などに）乗せてあげる', '中2', '標準', true, ARRAY['give a ride','give a lift'], 'premium'),
  ('give thought to', '〜について考える、〜を考慮する', NULL, '難関', true, ARRAY['give thought to','think about'], 'premium'),
  ('have an effect on', '〜に影響を与える、〜に効果がある', '中3', '標準', true, ARRAY['have an effect on','influence'], 'premium'),
  ('have an argument', '言い争いをする、口論する', '中3', '標準', true, ARRAY['have an argument','argue'], 'premium'),
  ('keep a secret', '秘密を守る', '中2', '基礎', true, ARRAY['keep a secret'], 'premium'),
  ('pay a visit', '訪問する、お見舞いに行く', '中3', '標準', true, ARRAY['pay a visit','visit'], 'premium'),
  ('bring to an end', '〜を終わらせる', '中3', '標準', true, ARRAY['bring to an end','finish'], 'premium'),
  ('come to an end', '終わる、終わりを迎える', '中2', '基礎', true, ARRAY['come to an end','finish'], 'premium'),
  ('catch fire', '火がつく、燃え出す', '中2', '標準', true, ARRAY['catch fire'], 'premium'),
  ('lose one''s temper', '腹を立てる、勘気を起こす', NULL, '難関', true, ARRAY['lose one''s temper','get angry'], 'premium'),
  ('hold one''s breath', '息を止める、かたずをのむ', '中3', '標準', true, ARRAY['hold one''s breath'], 'premium'),
  ('break one''s heart', '（人）の心を深く傷つける、がっかりさせる', '中2', '基礎', true, ARRAY['break one''s heart'], 'premium'),
  ('keep one''s word', '約束を守る', '中2', '標準', true, ARRAY['keep one''s word','keep one''s promise'], 'premium'),
  ('break one''s promise', '約束を破る', '中2', '基礎', true, ARRAY['break one''s promise','break one''s word'], 'premium'),
  ('do harm to', '〜に害を与える、〜を傷つける', '中3', '難関', true, ARRAY['do harm to','harm'], 'premium'),
  ('do good to', '〜に利益をもたらす、〜の体によい', '中2', '標準', true, ARRAY['do good to'], 'premium'),
  ('do wonders', '驚くべき効果を表す、奇跡を起こす', NULL, '難関', true, ARRAY['do wonders'], 'premium'),
  ('as a result', '結果として', '中3', '標準', true, ARRAY['as a result','therefore'], 'premium'),
  ('as a matter of fact', '実は、実際のところ', NULL, '難関', true, ARRAY['as a matter of fact','in fact'], 'premium'),
  ('as a rule', '概して、普通は、原則として', '中3', '標準', true, ARRAY['as a rule','usually'], 'premium'),
  ('by chance', '偶然に、たまたま', '中3', '標準', true, ARRAY['by chance','accidentally'], 'premium'),
  ('by mistake', '誤って、間違えて', '中2', '基礎', true, ARRAY['by mistake'], 'premium'),
  ('by degrees', '徐々に、次第に', NULL, '難関', true, ARRAY['by degrees','gradually'], 'premium'),
  ('in advance', 'あらかじめ、前もって', NULL, '難関', true, ARRAY['in advance','beforehand'], 'premium'),
  ('in common', '共通の、共同の', '中3', '標準', true, ARRAY['in common'], 'premium'),
  ('in detail', '詳細に、くわしく', '中3', '標準', true, ARRAY['in detail'], 'premium'),
  ('in general', '一般に、大体において', '中3', '標準', true, ARRAY['in general','generally'], 'premium'),
  ('in private', '非公式に、誰もいないところで', NULL, '難関', true, ARRAY['in private','secretly'], 'premium'),
  ('in short', '要するに、手短に言えば', '中3', '標準', true, ARRAY['in short','briefly'], 'premium'),
  ('in addition', '加えて、その上', '中3', '標準', true, ARRAY['in addition','besides'], 'premium'),
  ('in conclusion', '結論として、終わりに臨んで', NULL, '難関', true, ARRAY['in conclusion','finally'], 'premium'),
  ('on purpose', 'わざと、故意に', '中3', '標準', true, ARRAY['on purpose','intentionally'], 'premium'),
  ('on sale', '売り出されて、バーゲンで', '中1', '基礎', true, ARRAY['on sale'], 'premium'),
  ('out of order', '故障して', '中2', '標準', true, ARRAY['out of order','broken'], 'premium'),
  ('out of date', '時代遅れの、旧式の', NULL, '難関', true, ARRAY['out of date','old-fashioned'], 'premium'),
  ('up to date', '最新の', NULL, '難関', true, ARRAY['up to date','modern'], 'premium'),
  ('for good', '永久に、これを最後に', NULL, '難関', true, ARRAY['for good','forever'], 'premium'),
  ('for certain', '確かに、はっきりと', '中3', '標準', true, ARRAY['for certain','surely'], 'premium'),
  ('to some extent', 'ある程度、いくぶん', NULL, '難関', true, ARRAY['to some extent'], 'premium'),
  ('next door', '隣の、隣室の', '中1', '基礎', true, ARRAY['next door'], 'premium'),
  ('all the time', 'いつも、終始', '中1', '基礎', true, ARRAY['all the time','always'], 'premium'),
  ('at the same time', '同時に', '中2', '基礎', true, ARRAY['at the same time'], 'premium'),
  ('right away', 'すぐに、ただちに', '中2', '基礎', true, ARRAY['right away','at once'], 'premium'),
  ('all at once', '突然、一斉に', '中3', '標準', true, ARRAY['all at once','suddenly'], 'premium'),
  ('once in a while', 'ときどき、たまに', '中2', '標準', true, ARRAY['once in a while','sometimes'], 'premium'),
  ('sooner or later', '遅かれ早かれ、いつかは', '中3', '標準', true, ARRAY['sooner or later'], 'premium'),
  ('before long', 'まもなく、やがて', '中2', '標準', true, ARRAY['before long','soon'], 'premium'),
  ('by the time', '〜する時間までに', '中3', '標準', true, ARRAY['by the time'], 'premium'),
  ('for the sake of', '〜のために、〜の目的で', NULL, '難関', true, ARRAY['for the sake of'], 'premium'),
  ('regardless of', '〜に関わらず、〜を無視して', NULL, '難関', true, ARRAY['regardless of'], 'premium'),
  ('by means of', '〜によって、〜を用いて', NULL, '難関', true, ARRAY['by means of','through'], 'premium'),
  ('in the middle of', '〜の真ん中に、〜の最中に', '中1', '基礎', true, ARRAY['in the middle of'], 'premium'),
  ('on behalf of', '〜を代表して、〜の代わりに', NULL, '難関', true, ARRAY['on behalf of'], 'premium'),
  ('in place of', '〜の代わりに', '中3', '標準', true, ARRAY['in place of','instead of'], 'premium'),
  ('apart from', '〜は別として、〜を除いて', NULL, '難関', true, ARRAY['apart from','except for'], 'premium'),
  ('along with', '〜と一緒に、〜に加えて', '中2', '標準', true, ARRAY['along with','together with'], 'premium'),
  ('close to', '〜の近くに、〜に近接して', '中1', '基礎', true, ARRAY['close to','near'], 'premium'),
  ('contrary to', '〜に反して', NULL, '難関', true, ARRAY['contrary to'], 'premium'),
  ('due to', '〜のために、〜が原因で', '中3', '難関', true, ARRAY['due to','because of'], 'premium'),
  ('prior to', '〜より前に、〜に先立って', NULL, '難関', true, ARRAY['prior to','before'], 'premium'),
  ('with respect to', '〜に関して、〜の点では', NULL, '難関', true, ARRAY['with respect to','regarding'], 'premium'),
  ('depend on A for B', 'BのことでAに頼る、BをAに依存する', '中3', '標準', true, ARRAY['depend on A for B'], 'premium'),
  ('congratulate A on B', 'BのことでAを祝う', NULL, '難関', true, ARRAY['congratulate A on B'], 'premium'),
  ('spend A on B', 'A（お金・時間）をBに費やす', '中3', '標準', true, ARRAY['spend A on B'], 'premium'),
  ('remind A to do', 'Aに〜することを思い出させる', '中3', '標準', true, ARRAY['remind A to do'], 'premium'),
  ('persuade A to do', 'Aを説得して〜させる', NULL, '難関', true, ARRAY['persuade A to do'], 'premium'),
  ('force A to do', 'Aに無理やり〜させる、Aを強いて〜させる', '中3', '難関', true, ARRAY['force A to do'], 'premium'),
  ('enable A to do', 'Aが〜することを可能にする', NULL, '難関', true, ARRAY['enable A to do'], 'premium'),
  ('encourage A to do', 'Aが〜するよう励ます、奨励する', '中3', '標準', true, ARRAY['encourage A to do'], 'premium'),
  ('invite A to do', 'Aを勧誘して〜させる、Aに〜するよう頼む', '中2', '標準', true, ARRAY['invite A to do'], 'premium'),
  ('cause A to do', 'Aが〜する原因となる、Aに〜させる', '中3', '難関', true, ARRAY['cause A to do'], 'premium'),
  ('warn A to do', 'Aに〜するよう警告する、注意する', '中3', '標準', true, ARRAY['warn A to do'], 'premium'),
  ('order A to do', 'Aに〜するよう命令する', '中3', '標準', true, ARRAY['order A to do'], 'premium'),
  ('advise A to do', 'Aに〜するよう助言する、勧める', '中3', '標準', true, ARRAY['advise A to do'], 'premium'),
  ('expect A to do', 'Aが〜することを期待する', '中3', '標準', true, ARRAY['expect A to do'], 'premium'),
  ('require A to do', 'Aに〜することを要求する', NULL, '難関', true, ARRAY['require A to do'], 'premium'),
  ('happen to do', 'たまたま〜する', '中3', '標準', true, ARRAY['happen to do'], 'premium'),
  ('fail to do', '〜し損ねる、〜できない', '中3', '標準', true, ARRAY['fail to do'], 'premium'),
  ('manage to do', '何とかやり遂げる、どうにか〜する', '中3', '難関', true, ARRAY['manage to do'], 'premium'),
  ('tend to do', '〜する傾向がある、〜しがちである', '中3', '標準', true, ARRAY['tend to do'], 'premium'),
  ('refuse to do', '〜することを拒む、〜するのを断る', '中3', '難関', true, ARRAY['refuse to do'], 'premium'),
  ('hesitate to do', '〜するのをためらう、遠慮する', NULL, '難関', true, ARRAY['hesitate to do'], 'premium'),
  ('afford to do', '〜する（経済的・時間的）余裕がある', NULL, '難関', true, ARRAY['afford to do'], 'premium'),
  ('pretend to do', '〜するふりをする', '中3', '標準', true, ARRAY['pretend to do'], 'premium'),
  ('promise to do', '〜することを約束する', '中2', '基礎', true, ARRAY['promise to do'], 'premium'),
  ('court', '裁判所、法廷、コート（競技場）', '中3', '難関', false, ARRAY['court'], 'premium'),
  ('mean', '意地悪な、手段、意味する', '中2', '基礎', false, ARRAY['mean','unkind'], 'premium'),
  ('matter', '物質、事柄、問題となる', '中3', '標準', false, ARRAY['matter','substance'], 'premium'),
  ('hometown', '故郷、生まれ故郷', '中2', '基礎', false, ARRAY['hometown'], 'premium'),
  ('classmate', '同級生、クラスメイト', '中1', '基礎', false, ARRAY['classmate'], 'premium'),
  ('sunrise', '日の出', '中2', '基礎', false, ARRAY['sunrise'], 'premium'),
  ('sunset', '日没、夕焼け', '中2', '基礎', false, ARRAY['sunset'], 'premium'),
  ('restroom', 'お手洗い、化粧室', '中1', '基礎', false, ARRAY['restroom','bathroom'], 'premium'),
  ('firework', '花火', '中2', '基礎', false, ARRAY['firework'], 'premium'),
  ('chopsticks', '箸、お箸', '中1', '基礎', false, ARRAY['chopsticks'], 'premium'),
  ('textbook', '教科書', '中1', '基礎', false, ARRAY['textbook'], 'premium'),
  ('whiteboard', 'ホワイトボード', '中1', '基礎', false, ARRAY['whiteboard'], 'premium'),
  ('postman', '郵便配達員', '中2', '基礎', false, ARRAY['postman','mail carrier'], 'premium'),
  ('gas station', 'ガソリンスタンド', '中2', '基礎', true, ARRAY['gas station'], 'premium'),
  ('police station', '警察署', '中1', '基礎', true, ARRAY['police station'], 'premium'),
  ('post office', '郵便局', '中1', '基礎', true, ARRAY['post office'], 'premium'),
  ('department store', 'デパート、百貨店', '中1', '基礎', true, ARRAY['department store'], 'premium'),
  ('convenience store', 'コンビニ', '中2', '基礎', true, ARRAY['convenience store'], 'premium'),
  ('amusement park', '遊園地', '中2', '基礎', true, ARRAY['amusement park'], 'premium'),
  ('elementary school', '小学校', '中1', '基礎', true, ARRAY['elementary school'], 'premium'),
  ('high school student', '高校生', '中1', '基礎', true, ARRAY['high school student'], 'premium'),
  ('junior high school', '中学校', '中1', '基礎', true, ARRAY['junior high school'], 'premium'),
  ('pet bottle', 'ペットボトル', '中2', '基礎', true, ARRAY['pet bottle','plastic bottle'], 'premium'),
  ('ice cream', 'アイスクリーム', '中1', '基礎', true, ARRAY['ice cream'], 'premium'),
  ('french fries', 'フライドポテト', '中2', '基礎', true, ARRAY['french fries'], 'premium'),
  ('soft drink', '清涼飲料水、ノンアルコール飲料', '中2', '基礎', true, ARRAY['soft drink'], 'premium'),
  ('alarm clock', '目覚まし時計', '中1', '基礎', true, ARRAY['alarm clock'], 'premium'),
  ('comic book', '漫画本、コミック', '中1', '基礎', true, ARRAY['comic book','manga'], 'premium'),
  ('credit card', 'クレジットカード', '中3', '基礎', true, ARRAY['credit card'], 'premium'),
  ('smart phone', 'スマートフォン、スマホ', '中1', '基礎', true, ARRAY['smart phone','smartphone'], 'premium'),
  ('personal computer', 'パソコン、個人用コンピューター', '中2', '基礎', true, ARRAY['personal computer','PC'], 'premium'),
  ('table tennis', '卓球', '中1', '基礎', true, ARRAY['table tennis','ping-pong'], 'premium'),
  ('green tea', '緑茶、お茶', '中1', '基礎', true, ARRAY['green tea'], 'premium'),
  ('black tea', '紅茶', '中1', '基礎', true, ARRAY['black tea'], 'premium'),
  ('sea ice', '海氷', '中3', '標準', true, ARRAY['sea ice'], 'premium'),
  ('rain forest', '熱帯雨林', '中3', '標準', true, ARRAY['rain forest','rainforest'], 'premium'),
  ('fossil fuel', '化石燃料', '中3', '標準', true, ARRAY['fossil fuel'], 'premium'),
  ('solar energy', '太陽エネルギー', '中3', '標準', true, ARRAY['solar energy'], 'premium'),
  ('wind power', '風力、風力発電', '中3', '標準', true, ARRAY['wind power'], 'premium'),
  ('global warming', '地球温暖化', '中3', '標準', true, ARRAY['global warming'], 'premium'),
  ('climate change', '気候変動', '中3', '標準', true, ARRAY['climate change'], 'premium'),
  ('air pollution', '大気汚染', '中3', '標準', true, ARRAY['air pollution'], 'premium'),
  ('water pollution', '水質汚染', '中3', '標準', true, ARRAY['water pollution'], 'premium'),
  ('plastic bag', 'レジ袋、ビニール袋', '中2', '基礎', true, ARRAY['plastic bag'], 'premium'),
  ('paper bag', '紙袋', '中2', '基礎', true, ARRAY['paper bag'], 'premium'),
  ('eco bag', 'エコバッグ、マイバッグ', '中2', '基礎', true, ARRAY['eco bag','reusable bag'], 'premium'),
  ('natural resource', '天然資源', '中3', '標準', true, ARRAY['natural resource'], 'premium'),
  ('wild animal', '野生動物', '中2', '基礎', true, ARRAY['wild animal'], 'premium'),
  ('sea animal', '海洋動物、海の生き物', '中2', '基礎', true, ARRAY['sea animal','marine animal'], 'premium'),
  ('endangered species', '絶滅危惧種', '中3', '標準', true, ARRAY['endangered species'], 'premium'),
  ('garbage can', 'ゴミ箱', '中1', '基礎', true, ARRAY['garbage can','trash can'], 'premium'),
  ('recycled paper', '再生紙', '中2', '標準', true, ARRAY['recycled paper'], 'premium'),
  ('environmental problem', '環境問題', '中3', '標準', true, ARRAY['environmental problem'], 'premium'),
  ('foreign country', '外国', '中2', '基礎', true, ARRAY['foreign country'], 'premium'),
  ('foreign language', '外国語', '中2', '基礎', true, ARRAY['foreign language'], 'premium'),
  ('native speaker', 'ネイティブスピーカー、母語話者', '中3', '標準', true, ARRAY['native speaker'], 'premium'),
  ('world peace', '世界平和', '中2', '基礎', true, ARRAY['world peace'], 'premium'),
  ('human rights', '人権', '中3', '標準', true, ARRAY['human rights'], 'premium'),
  ('international student', '留学生', '中3', '標準', true, ARRAY['international student','exchange student'], 'premium'),
  ('study abroad', '留学する', '中3', '標準', true, ARRAY['study abroad'], 'premium'),
  ('cultural difference', '文化の違い', '中3', '標準', true, ARRAY['cultural difference'], 'premium'),
  ('traditional culture', '伝統文化', '中3', '標準', true, ARRAY['traditional culture'], 'premium'),
  ('sister city', '姉妹都市', '中2', '標準', true, ARRAY['sister city'], 'premium'),
  ('volunteer activity', 'ボランティア活動', '中3', '標準', true, ARRAY['volunteer activity'], 'premium'),
  ('local community', '地域社会、地元コミュニティ', '中3', '標準', true, ARRAY['local community'], 'premium'),
  ('public transportation', '公共交通機関', '中3', '標準', true, ARRAY['public transportation'], 'premium'),
  ('social media', 'ソーシャルメディア、SNS', '中2', '基礎', true, ARRAY['social media','SNS'], 'premium'),
  ('online shopping', 'ネット通販、オンラインショッピング', '中2', '基礎', true, ARRAY['online shopping'], 'premium'),
  ('free time', '自由時間、暇な時間', '中1', '基礎', true, ARRAY['free time','spare time'], 'premium'),
  ('good time', '楽しい時間', '中1', '基礎', true, ARRAY['good time','fun time'], 'premium'),
  ('hard work', 'きつい仕事、猛勉強、努力', '中2', '基礎', true, ARRAY['hard work'], 'premium'),
  ('bad habit', '悪い癖、悪習慣', '中3', '標準', true, ARRAY['bad habit'], 'premium'),
  ('daily life', '日常生活、毎日の生活', '中2', '基礎', true, ARRAY['daily life','everyday life'], 'premium'),
  ('future dream', '将来の夢', '中1', '基礎', true, ARRAY['future dream'], 'premium'),
  ('school life', '学校生活', '中1', '基礎', true, ARRAY['school life'], 'premium'),
  ('school festival', '文化祭、学園祭', '中1', '基礎', true, ARRAY['school festival'], 'premium'),
  ('sports day', '運動会、体育祭', '中1', '基礎', true, ARRAY['sports day'], 'premium'),
  ('school trip', '修学旅行、遠足', '中2', '基礎', true, ARRAY['school trip'], 'premium'),
  ('summer vacation', '夏休み', '中1', '基礎', true, ARRAY['summer vacation'], 'premium'),
  ('winter vacation', '冬休み', '中1', '基礎', true, ARRAY['winter vacation'], 'premium'),
  ('opening ceremony', '始業式、開会式', '中2', '標準', true, ARRAY['opening ceremony'], 'premium'),
  ('closing ceremony', '終業式、閉会式', '中2', '標準', true, ARRAY['closing ceremony'], 'premium'),
  ('graduation ceremony', '卒業式', '中3', '標準', true, ARRAY['graduation ceremony'], 'premium'),
  ('entrance exam', '入学試験、入試', '中3', '標準', true, ARRAY['entrance exam'], 'premium'),
  ('test result', 'テストの結果、成績', '中2', '基礎', true, ARRAY['test result'], 'premium'),
  ('math problem', '数学の問題', '中1', '基礎', true, ARRAY['math problem'], 'premium'),
  ('history report', '歴史のレポート', '中2', '基礎', true, ARRAY['history report'], 'premium'),
  ('english teacher', '英語の先生', '中1', '基礎', true, ARRAY['english teacher'], 'premium'),
  ('homeroom teacher', '担任の先生', '中1', '基礎', true, ARRAY['homeroom teacher'], 'premium'),
  ('club activity', '部活動、部活', '中1', '基礎', true, ARRAY['club activity'], 'premium'),
  ('baseball team', '野球チーム、野球部', '中1', '基礎', true, ARRAY['baseball team'], 'premium'),
  ('soccer ball', 'サッカーボール', '中1', '基礎', true, ARRAY['soccer ball'], 'premium'),
  ('library card', '図書カード、利用証', '中1', '基礎', true, ARRAY['library card'], 'premium'),
  ('science room', '理科室', '中1', '基礎', true, ARRAY['science room','science lab'], 'premium'),
  ('music room', '音楽室', '中1', '基礎', true, ARRAY['music room'], 'premium'),
  ('computer room', 'コンピュータ室', '中1', '基礎', true, ARRAY['computer room'], 'premium'),
  ('school yard', '校庭、学校のグラウンド', '中1', '基礎', true, ARRAY['school yard','playground'], 'premium'),
  ('blackboard eraser', '黒板消し', '中1', '基礎', true, ARRAY['blackboard eraser'], 'premium'),
  ('station entrance', '駅の入り口', '中2', '基礎', true, ARRAY['station entrance'], 'premium'),
  ('bus stop', 'バス停', '中1', '基礎', true, ARRAY['bus stop'], 'premium'),
  ('train ticket', '電車の切符、乗車券', '中1', '基礎', true, ARRAY['train ticket'], 'premium'),
  ('ticket machine', '券売機、切符売り場', '中2', '基礎', true, ARRAY['ticket machine','ticket vending machine'], 'premium'),
  ('police officer', '警察官、おまわりさん', '中1', '基礎', true, ARRAY['police officer'], 'premium'),
  ('fire station', '消防署', '中2', '基礎', true, ARRAY['fire station'], 'premium'),
  ('shopping mall', 'ショッピングモール、大型商業施設', '中2', '基礎', true, ARRAY['shopping mall'], 'premium'),
  ('fast food', 'ファストフード', '中2', '基礎', true, ARRAY['fast food'], 'premium'),
  ('birthday party', '誕生日パーティー', '中1', '基礎', true, ARRAY['birthday party'], 'premium'),
  ('christmas tree', 'クリスマスツリー', '中1', '基礎', true, ARRAY['christmas tree'], 'premium'),
  ('new year', '新年、お正月', '中1', '基礎', true, ARRAY['new year'], 'premium'),
  ('pet dog', 'ペットの犬、愛犬', '中1', '基礎', true, ARRAY['pet dog'], 'premium'),
  ('stray cat', '野良猫', '中2', '基礎', true, ARRAY['stray cat'], 'premium'),
  ('flower garden', '花畑、フラワーガーデン', '中1', '基礎', true, ARRAY['flower garden'], 'premium'),
  ('apple tree', 'リンゴの木', '中1', '基礎', true, ARRAY['apple tree'], 'premium'),
  ('orange juice', 'オレンジジュース', '中1', '基礎', true, ARRAY['orange juice'], 'premium'),
  ('tomato soup', 'トマトスープ', '中1', '基礎', true, ARRAY['tomato soup'], 'premium'),
  ('coffee shop', '喫茶店、カフェ', '中1', '基礎', true, ARRAY['coffee shop','cafe'], 'premium'),
  ('book store', '本屋、書店', '中1', '基礎', true, ARRAY['book store','bookshop'], 'premium'),
  ('toy shop', 'おもちゃ屋', '中1', '基礎', true, ARRAY['toy shop','toy store'], 'premium'),
  ('shoe store', '靴屋', '中1', '基礎', true, ARRAY['shoe store','shoe shop'], 'premium'),
  ('pet shop', 'ペットショップ', '中1', '基礎', true, ARRAY['pet shop'], 'premium'),
  ('hair salon', '美容院、理髪店', '中2', '基礎', true, ARRAY['hair salon','barber shop'], 'premium'),
  ('sports club', 'スポーツクラブ、フィットネスクラブ', '中2', '基礎', true, ARRAY['sports club'], 'premium'),
  ('tennis court', 'テニスコート', '中1', '基礎', true, ARRAY['tennis court'], 'premium'),
  ('swimming pool', 'プール、水泳プール', '中1', '基礎', true, ARRAY['swimming pool'], 'premium'),
  ('sea water', '海水、海の水', '中2', '基礎', true, ARRAY['sea water'], 'premium'),
  ('river bank', '川の土手、川岸', '中2', '基礎', true, ARRAY['river bank','riverbank'], 'premium'),
  ('mountain path', '山道', '中2', '基礎', true, ARRAY['mountain path'], 'premium'),
  ('rainy season', '梅雨、雨季', '中2', '基礎', true, ARRAY['rainy season'], 'premium'),
  ('weather forecast', '天気予報', '中2', '基礎', true, ARRAY['weather forecast'], 'premium'),
  ('news program', 'ニュース番組', '中1', '基礎', true, ARRAY['news program'], 'premium'),
  ('tv star', 'テレビタレント、有名人', '中1', '基礎', true, ARRAY['tv star','celebrity'], 'premium'),
  ('movie theater', '映画館', '中1', '基礎', true, ARRAY['movie theater','cinema'], 'premium'),
  ('concert hall', 'コンサートホール、音楽堂', '中2', '基礎', true, ARRAY['concert hall'], 'premium'),
  ('art museum', '美術館', '中2', '基礎', true, ARRAY['art museum','art gallery'], 'premium'),
  ('science museum', '科学館', '中2', '基礎', true, ARRAY['science museum'], 'premium'),
  ('history museum', '歴史博物館', '中2', '基礎', true, ARRAY['history museum'], 'premium'),
  ('travel agency', '旅行代理店、旅行会社', '中3', '基礎', true, ARRAY['travel agency'], 'premium'),
  ('bus tour', 'バスツアー、バス旅行', '中1', '基礎', true, ARRAY['bus tour'], 'premium'),
  ('plane ticket', '飛行機の切符、航空券', '中2', '基礎', true, ARRAY['plane ticket'], 'premium'),
  ('passport control', '出入国審査、パスポートコントロール', '中3', '基礎', true, ARRAY['passport control'], 'premium'),
  ('hotel room', 'ホテルの部屋客室', '中1', '基礎', true, ARRAY['hotel room'], 'premium'),
  ('bed room', '寝室、ベッドルーム', '中1', '基礎', true, ARRAY['bed room','bedroom'], 'premium'),
  ('living room', '居間、リビング', '中1', '基礎', true, ARRAY['living room'], 'premium'),
  ('dining room', '食堂、ダイニングルーム', '中1', '基礎', true, ARRAY['dining room'], 'premium'),
  ('front door', '玄関のドア、正面玄関', '中1', '基礎', true, ARRAY['front door'], 'premium'),
  ('back yard', '裏庭', '中2', '基礎', true, ARRAY['back yard','backyard'], 'premium'),
  ('kitchen table', '台所のテーブル', '中1', '基礎', true, ARRAY['kitchen table'], 'premium'),
  ('bath towel', 'バスタオル', '中1', '基礎', true, ARRAY['bath towel'], 'premium'),
  ('gas stove', 'ガスコンロ、ガスストーブ', '中2', '基礎', true, ARRAY['gas stove'], 'premium'),
  ('electric light', '電灯、電気の明かり', '中2', '基礎', true, ARRAY['electric light'], 'premium'),
  ('telephone number', '電話番号', '中1', '基礎', true, ARRAY['telephone number','phone number'], 'premium'),
  ('pocket money', 'お小遣い', '中2', '基礎', true, ARRAY['pocket money','allowance'], 'premium'),
  ('paper money', '紙幣、お札', '中2', '基礎', true, ARRAY['paper money','bill'], 'premium'),
  ('gold medal', '金メダル', '中2', '基礎', true, ARRAY['gold medal'], 'premium'),
  ('silver medal', '銀メダル', '中2', '基礎', true, ARRAY['silver medal'], 'premium'),
  ('bronze medal', '銅メダル', '中2', '基礎', true, ARRAY['bronze medal'], 'premium'),
  ('sports fan', 'スポーツファン、大のスポーツ好き', '中1', '基礎', true, ARRAY['sports fan'], 'premium'),
  ('guitar player', 'ギタリスト、ギター奏者', '中1', '基礎', true, ARRAY['guitar player','guitarist'], 'premium'),
  ('piano lesson', 'ピアノのレッスン、ピアノの練習', '中1', '基礎', true, ARRAY['piano lesson'], 'premium'),
  ('pop music', 'ポップス、ポピュラー音楽', '中1', '基礎', true, ARRAY['pop music'], 'premium'),
  ('rock band', 'ロックバンド', '中2', '基礎', true, ARRAY['rock band'], 'premium'),
  ('dance club', 'ダンス部、ダンスクラブ', '中1', '基礎', true, ARRAY['dance club'], 'premium'),
  ('art club', '美術部', '中1', '基礎', true, ARRAY['art club'], 'premium'),
  ('science club', '科学部、理科部', '中1', '基礎', true, ARRAY['science club'], 'premium'),
  ('brass band', '吹奏楽部、ブラスバンド', '中2', '基礎', true, ARRAY['brass band'], 'premium'),
  ('english club', '英語部、英語クラブ', '中1', '基礎', true, ARRAY['english club'], 'premium'),
  ('tea ceremony', '茶道', '中3', '基礎', true, ARRAY['tea ceremony'], 'premium'),
  ('flower arrangement', '華道、生け花', '中3', '基礎', true, ARRAY['flower arrangement','ikebana'], 'premium'),
  ('cooking class', '料理教室', '中2', '基礎', true, ARRAY['cooking class'], 'premium'),
  ('driving license', '運転免許証、運転免許', '中3', '標準', true, ARRAY['driving license','driver''s license'], 'premium'),
  ('birth place', '出生地、生まれた場所', '中2', '基礎', true, ARRAY['birth place','birthplace'], 'premium'),
  ('wedding party', '結婚披露宴、結婚パーティー', '中3', '基礎', true, ARRAY['wedding party'], 'premium'),
  ('dinner time', '夕食の時間', '中1', '基礎', true, ARRAY['dinner time'], 'premium'),
  ('lunch box', 'お弁当箱、お弁当', '中1', '基礎', true, ARRAY['lunch box','bento'], 'premium'),
  ('breakfast time', '朝食の時間', '中1', '基礎', true, ARRAY['breakfast time'], 'premium'),
  ('pet cat', 'ペットの猫、愛猫', '中1', '基礎', true, ARRAY['pet cat'], 'premium'),
  ('guide book', 'ガイドブック、旅行案内書', '中2', '基礎', true, ARRAY['guide book','guidebook'], 'premium'),
  ('notebook PC', 'ノートパソコン', '中2', '基礎', true, ARRAY['notebook PC','laptop'], 'premium'),
  ('web site', 'ウェブサイト、ホームページ', '中2', '基礎', true, ARRAY['web site','website'], 'premium'),
  ('e-mail address', 'メールアドレス', '中2', '基礎', true, ARRAY['e-mail address','email address'], 'premium'),
  ('video game', 'テレビゲーム、ビデオゲーム', '中1', '基礎', true, ARRAY['video game'], 'premium'),
  ('card game', 'トランプ、カードゲーム', '中1', '基礎', true, ARRAY['card game'], 'premium'),
  ('ice hockey', 'アイスホッケー', '中2', '基礎', true, ARRAY['ice hockey'], 'premium'),
  ('field trip', '校外学習、遠足', '中2', '基礎', true, ARRAY['field trip'], 'premium'),
  ('day trip', '日帰り旅行', '中2', '基礎', true, ARRAY['day trip'], 'premium'),
  ('world record', '世界記録', '中3', '標準', true, ARRAY['world record'], 'premium'),
  ('national treasure', '国宝、国家の宝', '中3', '標準', true, ARRAY['national treasure'], 'premium'),
  ('public park', '公立公園、公共の公園', '中1', '基礎', true, ARRAY['public park'], 'premium'),
  ('city hall', '市役所', '中2', '基礎', true, ARRAY['city hall'], 'premium'),
  ('town hall', '町役場、公会堂', '中2', '基礎', true, ARRAY['town hall'], 'premium'),
  ('central station', '中央駅、ターミナル駅', '中2', '基礎', true, ARRAY['central station'], 'premium'),
  ('subway station', '地下鉄の駅', '中2', '基礎', true, ARRAY['subway station'], 'premium'),
  ('railway station', '鉄道駅、駅', '中2', '基礎', true, ARRAY['railway station','train station'], 'premium'),
  ('bus terminal', 'バスターミナル', '中2', '基礎', true, ARRAY['bus terminal'], 'premium'),
  ('taxi stand', 'タクシー乗り場', '中2', '基礎', true, ARRAY['taxi stand'], 'premium'),
  ('police car', 'パトカー', '中1', '基礎', true, ARRAY['police car','patrol car'], 'premium'),
  ('fire engine', '消防車', '中2', '基礎', true, ARRAY['fire engine','fire truck'], 'premium'),
  ('sports car', 'スポーツカー', '中1', '基礎', true, ARRAY['sports car'], 'premium'),
  ('used car', '中古車', '中3', '基礎', true, ARRAY['used car','second-hand car'], 'premium'),
  ('traffic light', '信号、信号機', '中2', '基礎', true, ARRAY['traffic light'], 'premium'),
  ('traffic jam', '交通渋滞、渋滞', '中3', '標準', true, ARRAY['traffic jam'], 'premium'),
  ('road map', '道路地図、ロードマップ', '中2', '基礎', true, ARRAY['road map','roadmap'], 'premium'),
  ('street lamp', '街灯', '中2', '基礎', true, ARRAY['street lamp','street light'], 'premium'),
  ('sea shore', '海岸、海辺', '中2', '基礎', true, ARRAY['sea shore','seashore','coast'], 'premium'),
  ('river side', '川沿い、川辺', '中2', '基礎', true, ARRAY['river side','riverside'], 'premium'),
  ('lake side', '湖畔、湖のほとり', '中2', '基礎', true, ARRAY['lake side','lakeside'], 'premium'),
  ('mountain top', '山頂、山の頂上', '中2', '基礎', true, ARRAY['mountain top','mountaintop'], 'premium'),
  ('forest fire', '山火事、森林火災', '中2', '標準', true, ARRAY['forest fire'], 'premium'),
  ('hot spring', '温泉', '中2', '基礎', true, ARRAY['hot spring'], 'premium'),
  ('waterfall', '滝', '中2', '基礎', false, ARRAY['waterfall'], 'premium'),
  ('sunlight', '日光、太陽の光', '中2', '基礎', false, ARRAY['sunlight'], 'premium'),
  ('moonlight', '月光、月の光', '中2', '基礎', false, ARRAY['moonlight'], 'premium'),
  ('starry sky', '星空、満天の星', '中2', '基礎', true, ARRAY['starry sky'], 'premium'),
  ('blue sky', '青空', '中1', '基礎', true, ARRAY['blue sky'], 'premium'),
  ('rain coat', 'レインコート、合羽', '中1', '基礎', true, ARRAY['rain coat','raincoat'], 'premium'),
  ('winter clothes', '冬服、防寒着', '中1', '基礎', true, ARRAY['winter clothes'], 'premium'),
  ('summer clothes', '夏服', '中1', '基礎', true, ARRAY['summer clothes'], 'premium'),
  ('school uniform', '制服、学生服', '中1', '基礎', true, ARRAY['school uniform'], 'premium'),
  ('sports shoes', '運動靴、スニーカー', '中1', '基礎', true, ARRAY['sports shoes','sneakers'], 'premium'),
  ('leather shoes', '革靴', '中2', '基礎', true, ARRAY['leather shoes'], 'premium'),
  ('bath room', 'お風呂場、浴室', '中1', '基礎', true, ARRAY['bath room','bathroom'], 'premium'),
  ('guest room', '客室、ゲストルーム', '中2', '基礎', true, ARRAY['guest room'], 'premium'),
  ('class room', '教室', '中1', '基礎', true, ARRAY['class room','classroom'], 'premium'),
  ('reading room', '読書室、図書閲覧室', '中2', '基礎', true, ARRAY['reading room'], 'premium'),
  ('meeting room', '会議室', '中2', '基礎', true, ARRAY['meeting room','conference room'], 'premium'),
  ('waiting room', '待合室', '中2', '基礎', true, ARRAY['waiting room'], 'premium'),
  ('tea cup', 'ティーカップ、茶碗', '中1', '基礎', true, ARRAY['tea cup','teacup'], 'premium'),
  ('coffee cup', 'コーヒーカップ', '中1', '基礎', true, ARRAY['coffee cup','coffeecup'], 'premium'),
  ('wine glass', 'ワイングラス', '中2', '基礎', true, ARRAY['wine glass'], 'premium'),
  ('water glass', 'コップ、水コップ', '中1', '基礎', true, ARRAY['water glass','tumbler'], 'premium'),
  ('fountain pen', '万年筆', '中3', '標準', true, ARRAY['fountain pen'], 'premium'),
  ('pencil case', '筆箱、ペンケース', '中1', '基礎', true, ARRAY['pencil case'], 'premium'),
  ('pencil sharpener', '鉛筆削り', '中1', '基礎', true, ARRAY['pencil sharpener'], 'premium'),
  ('color pencil', '色鉛筆', '中1', '基礎', true, ARRAY['color pencil','colored pencil'], 'premium'),
  ('ballpoint pen', 'ボールペン', '中1', '基礎', true, ARRAY['ballpoint pen'], 'premium'),
  ('scrap book', 'スクラップブック、切り抜き帳', '中2', '基礎', true, ARRAY['scrap book','scrapbook'], 'premium'),
  ('picture book', '絵本', '中1', '基礎', true, ARRAY['picture book'], 'premium'),
  ('history book', '歴史書、歴史の本', '中2', '基礎', true, ARRAY['history book'], 'premium'),
  ('science book', '科学の本、科学書', '中2', '基礎', true, ARRAY['science book'], 'premium'),
  ('english dictionary', '英語の辞書、英和辞典', '中1', '基礎', true, ARRAY['english dictionary'], 'premium'),
  ('cooking recipe', '料理のレシピ', '中2', '基礎', true, ARRAY['cooking recipe'], 'premium'),
  ('sports field', '運動場、競技場', '中2', '基礎', true, ARRAY['sports field'], 'premium'),
  ('soccer field', 'サッカー場、サッカーのグラウンド', '中2', '基礎', true, ARRAY['soccer field','soccer pitch'], 'premium'),
  ('baseball field', '野球場、野球のグラウンド', '中2', '基礎', true, ARRAY['baseball field'], 'premium'),
  ('track and field', '陸上競技', '中2', '標準', true, ARRAY['track and field'], 'premium'),
  ('high jump', '走り高跳び、高跳び', '中2', '基礎', true, ARRAY['high jump'], 'premium'),
  ('long jump', '走り幅跳び、幅跳び', '中2', '基礎', true, ARRAY['long jump'], 'premium'),
  ('sports meet', '運動会、スポーツ大会', '中1', '基礎', true, ARRAY['sports meet','sports day'], 'premium'),
  ('acid rain', '酸性雨', '中3', '難関', true, ARRAY['acid rain'], 'premium'),
  ('sea level', '海面、海水面', '中3', '標準', true, ARRAY['sea level'], 'premium'),
  ('extinct', '絶滅した', '中3', '難関', false, ARRAY['extinct'], 'premium'),
  ('solar power', '太陽光発電、太陽エネルギー', '中3', '標準', true, ARRAY['solar power'], 'premium'),
  ('food loss', '食品ロス、食べ残し', '中3', '標準', true, ARRAY['food loss'], 'premium'),
  ('organic', '有機栽培の、オーガニックの', '中3', '標準', false, ARRAY['organic'], 'premium'),
  ('reuse', '〜を再利用する', '中2', '基礎', false, ARRAY['reuse'], 'premium'),
  ('global citizens', '地球市民、国際社会の一員', '中3', '難関', true, ARRAY['global citizens','global citizen'], 'premium'),
  ('developing country', '開発途上国', '中3', '標準', true, ARRAY['developing country'], 'premium'),
  ('developed country', '先進国', '中3', '標準', true, ARRAY['developed country'], 'premium'),
  ('immigrant', '（外国からの）移民', '中3', '難関', false, ARRAY['immigrant'], 'premium'),
  ('discrimination', '差別', '中3', '難関', false, ARRAY['discrimination'], 'premium'),
  ('conflict', '紛争、対立', '中3', '難関', false, ARRAY['conflict'], 'premium'),
  ('global economy', '世界経済', '中3', '難関', true, ARRAY['global economy'], 'premium'),
  ('ngo', '非政府組織、NGO', '中3', '標準', false, ARRAY['ngo','NGO'], 'premium'),
  ('unicef', '国連児童基金、ユニセフ', '中3', '標準', false, ARRAY['unicef','UNICEF'], 'premium'),
  ('cross-cultural', '異文化間の', '中3', '難関', false, ARRAY['cross-cultural'], 'premium'),
  ('online security', 'ネットの安全、オンラインセキュリティ', '中3', '標準', true, ARRAY['online security'], 'premium'),
  ('privacy', 'プライバシー', '中3', '標準', false, ARRAY['privacy'], 'premium'),
  ('fake news', '偽ニュース、フェイクニュース', '中3', '標準', true, ARRAY['fake news'], 'premium'),
  ('search engine', '検索エンジン', '中2', '基礎', true, ARRAY['search engine'], 'premium'),
  ('data', 'データ、資料', '中2', '基礎', false, ARRAY['data'], 'premium'),
  ('digitalization', 'デジタル化', '中3', '難関', false, ARRAY['digitalization'], 'premium'),
  ('smart device', 'スマート機器', '中3', '標準', true, ARRAY['smart device'], 'premium'),
  ('virtual reality', '仮想現実、VR', '中3', '難関', true, ARRAY['virtual reality','vr','VR'], 'premium'),
  ('convenience', '便利さ、利便性', '中3', '標準', false, ARRAY['convenience'], 'premium'),
  ('diversity', '多様性', '中3', '難関', false, ARRAY['diversity'], 'premium'),
  ('birthrate', '出生率', '中3', '難関', false, ARRAY['birthrate'], 'premium'),
  ('elderly people', '高齢者、お年寄り', '中3', '標準', true, ARRAY['elderly people'], 'premium'),
  ('barrier-free', 'バリアフリーの、障壁のない', '中3', '標準', false, ARRAY['barrier-free'], 'premium'),
  ('disaster prevention', '防災', '中3', '難関', true, ARRAY['disaster prevention'], 'premium'),
  ('evacuation center', '避難所', '中3', '難関', true, ARRAY['evacuation center','shelter'], 'premium'),
  ('infectious disease', '感染症', '中3', '難関', true, ARRAY['infectious disease'], 'premium'),
  ('mental health', '心の健康、メンタルヘルス', '中3', '標準', true, ARRAY['mental health'], 'premium'),
  ('lifelong learning', '生涯学習', '中3', '難関', true, ARRAY['lifelong learning'], 'premium'),
  ('work-life balance', '仕事と生活の調和、ワークライフバランス', '中3', '難関', true, ARRAY['work-life balance'], 'premium'),
  ('consumer', '消費者', '中3', '標準', false, ARRAY['consumer'], 'premium'),
  ('economy', '経済', '中3', '標準', false, ARRAY['economy'], 'premium'),
  ('issue', '問題、課題', '中3', '標準', false, ARRAY['issue'], 'premium'),
  ('sustainable society', '持続可能な社会', '中3', '標準', true, ARRAY['sustainable society'], 'premium'),
  ('market', '市場（しじょう・いちば）', '中2', '基礎', false, ARRAY['market'], 'premium'),
  ('labor shortage', '労働力不足、人手不足', '中3', '難関', true, ARRAY['labor shortage'], 'premium'),
  ('foreign worker', '外国人労働者', '中3', '標準', true, ARRAY['foreign worker'], 'premium'),
  ('free trade', '自由貿易', '中3', '難関', true, ARRAY['free trade'], 'premium'),
  ('economic growth', '経済成長', '中3', '難関', true, ARRAY['economic growth'], 'premium'),
  ('diplomacy', '外交', '中3', '難関', false, ARRAY['diplomacy'], 'premium'),
  ('agreement', '合意、協定', '中3', '難関', false, ARRAY['agreement'], 'premium'),
  ('summit', '首脳会談、サミット、頂上', '中3', '標準', false, ARRAY['summit'], 'premium'),
  ('international law', '国際法', '中3', '難関', true, ARRAY['international law'], 'premium'),
  ('treaty', '条約', '中3', '難関', false, ARRAY['treaty'], 'premium'),
  ('united nations', '国際連合、国連', '中3', '標準', true, ARRAY['united nations','UN'], 'premium'),
  ('official visit', '公式訪問', '中3', '難関', true, ARRAY['official visit'], 'premium'),
  ('security', '安全、安全保障、防犯', '中3', '標準', false, ARRAY['security'], 'premium'),
  ('peacekeeping', '平和維持（活動）', '中3', '難関', false, ARRAY['peacekeeping'], 'premium'),
  ('defense', '防衛、防御', '中3', '標準', false, ARRAY['defense'], 'premium'),
  ('weapon', '武器、兵器', '中3', '難関', false, ARRAY['weapon'], 'premium'),
  ('protect against', '〜から（身を）守る、防御する', '中3', '標準', true, ARRAY['protect against'], 'premium'),
  ('alliance', '同盟、提携', '中3', '難関', false, ARRAY['alliance'], 'premium'),
  ('emergency', '緊急事態、非常事態', '中2', '基礎', false, ARRAY['emergency'], 'premium'),
  ('safety measure', '安全対策', '中3', '難関', true, ARRAY['safety measure'], 'premium'),
  ('finance', '金融、財政', '中3', '難関', false, ARRAY['finance'], 'premium'),
  ('bank account', '銀行口座', '中2', '基礎', true, ARRAY['bank account'], 'premium'),
  ('investment', '投資', '中3', '難関', false, ARRAY['investment'], 'premium'),
  ('currency', '通貨、貨幣', '中3', '難関', false, ARRAY['currency'], 'premium'),
  ('exchange rate', '為替レート、交換レート', '中3', '難関', true, ARRAY['exchange rate'], 'premium'),
  ('digital money', '電子マネー、デジタル通貨', '中2', '基礎', true, ARRAY['digital money','electronic money'], 'premium'),
  ('cashless', 'キャッシュレスの、現金を必要としない', '中3', '標準', false, ARRAY['cashless'], 'premium'),
  ('loan', 'ローン、貸付金、借入金', '中3', '難関', false, ARRAY['loan'], 'premium'),
  ('income', '収入、所得', '中3', '難関', false, ARRAY['income'], 'premium'),
  ('save money', '貯金する、お金を節約する', '中1', '基礎', true, ARRAY['save money'], 'premium'),
  ('economic gap', '経済格差', '中3', '難関', true, ARRAY['economic gap'], 'premium'),
  ('inflation', 'インフレ、物価上昇', '中3', '難関', false, ARRAY['inflation'], 'premium'),
  ('interest rate', '金利、利子率', '中3', '難関', true, ARRAY['interest rate'], 'premium'),
  ('global asset', '世界的な資産、地球の財産', '中3', '難関', true, ARRAY['global asset'], 'premium'),
  ('financial crisis', '金融危機', '中3', '難関', true, ARRAY['financial crisis'], 'premium'),
  ('cooperate globally', '世界規模で協力する', '中3', '標準', true, ARRAY['cooperate globally'], 'premium')
ON CONFLICT (word) DO NOTHING;