-- seed: tuika3 (d-z vocabulary + idioms, 339 net-new entries)
-- generated 2026-06-28
INSERT INTO words (word, meaning, grade, level, is_idiom, answers_en, tier)
VALUES
  ('education', '教育', '中3', '標準', false, ARRAY['education'], 'premium'),
  ('elderly', '年配の、高齢の', '中3', '標準', false, ARRAY['elderly'], 'premium'),
  ('elementary', '初歩の、小学校の', '中1', '基礎', false, ARRAY['elementary'], 'premium'),
  ('encourage', '〜を勇気づける、励ます', '中3', '標準', false, ARRAY['encourage'], 'premium'),
  ('damage', '〜に損害を与える、被害', '中3', '標準', false, ARRAY['damage'], 'premium'),
  ('debate', '討論、ディベート', '中3', '標準', false, ARRAY['debate'], 'premium'),
  ('debt', '借金、負債', '中3', '難関', false, ARRAY['debt'], 'premium'),
  ('decade', '10年間', '中3', '難関', false, ARRAY['decade'], 'premium'),
  ('declare', '〜を宣言する', '中3', '難関', false, ARRAY['declare'], 'premium'),
  ('decline', '減少する、低下する', '中3', '難関', false, ARRAY['decline'], 'premium'),
  ('declining birthrate', '少子化', '中3', '難関', true, ARRAY['declining birthrate'], 'premium'),
  ('decrease', '減少する、〜を減らす', '中3', '標準', false, ARRAY['decrease'], 'premium'),
  ('defend', '〜を守る、防衛する', '中3', '標準', false, ARRAY['defend'], 'premium'),
  ('deficit', '赤字、不足額', '中3', '難関', false, ARRAY['deficit'], 'premium'),
  ('deforestation', '森林破壊', '中3', '難関', false, ARRAY['deforestation'], 'premium'),
  ('delivery', '配達、配送', '中2', '基礎', false, ARRAY['delivery'], 'premium'),
  ('demand', '需要、要求', '中3', '難関', false, ARRAY['demand'], 'premium'),
  ('democracy', '民主主義', '中3', '難関', false, ARRAY['democracy'], 'premium'),
  ('deposit', '預金する、預金、手付金', '中3', '難関', false, ARRAY['deposit'], 'premium'),
  ('depression', '不景気、うつ病', '中3', '難関', false, ARRAY['depression'], 'premium'),
  ('desert', '砂漠', '中2', '基礎', false, ARRAY['desert'], 'premium'),
  ('detect', '〜を検出する、感知する', '中3', '難関', false, ARRAY['detect'], 'premium'),
  ('device', '機器、装置', '中3', '難関', false, ARRAY['device'], 'premium'),
  ('dialogue', '対話、話し合い', '中3', '難関', false, ARRAY['dialogue'], 'premium'),
  ('digital divide', '情報格差、デジタルデバイド', '中3', '難関', true, ARRAY['digital divide'], 'premium'),
  ('diplomat', '外交官', '中3', '難関', false, ARRAY['diplomat'], 'premium'),
  ('direct', '直接的な、〜を指揮する', '中3', '標準', false, ARRAY['direct'], 'premium'),
  ('disadvantage', 'デメリット、不利な点', '中3', '難関', false, ARRAY['disadvantage'], 'premium'),
  ('disaster', '災害、惨事', '中3', '標準', false, ARRAY['disaster'], 'premium'),
  ('discount', '割引、〜を割引する', '中2', '基礎', false, ARRAY['discount'], 'premium'),
  ('dispute', '紛争、論争', '中3', '難関', false, ARRAY['dispute'], 'premium'),
  ('distribution', '流通、分配', '中3', '難関', false, ARRAY['distribution'], 'premium'),
  ('diverse', '多様な', '中3', '難関', false, ARRAY['diverse'], 'premium'),
  ('domestic', '国内の、家庭の', '中3', '難関', false, ARRAY['domestic'], 'premium'),
  ('donation', '寄付', '中3', '難関', false, ARRAY['donation'], 'premium'),
  ('gain', '〜を得る、増す', '中3', '難関', false, ARRAY['gain'], 'premium'),
  ('gap', 'すき間、格差、隔たり', '中3', '難関', false, ARRAY['gap'], 'premium'),
  ('gasoline', 'ガソリン', '中2', '標準', false, ARRAY['gasoline'], 'premium'),
  ('gender', '社会的・文化的な性別', '中3', '標準', false, ARRAY['gender'], 'premium'),
  ('gentle', '優しい、穏やかな', '中2', '標準', false, ARRAY['gentle'], 'premium'),
  ('get better', '（体調などが）良くなる、好転する', '中2', '基礎', true, ARRAY['get better'], 'premium'),
  ('get lost', '道に迷う', '中2', '基礎', true, ARRAY['get lost'], 'premium'),
  ('get ready', '準備をする', '中2', '基礎', true, ARRAY['get ready'], 'premium'),
  ('get tired of', '〜に飽きる、うんざりする', '中2', '標準', true, ARRAY['get tired of'], 'premium'),
  ('gifted', '才能のある', '中3', '難関', false, ARRAY['gifted'], 'premium'),
  ('give a talk', '話をする、講演をする', '中3', '標準', true, ARRAY['give a talk'], 'premium'),
  ('give up on', '〜をあきらめる、見限る', '中2', '標準', true, ARRAY['give up on'], 'premium'),
  ('globalization', 'グローバル化、国際化', '中3', '標準', false, ARRAY['globalization'], 'premium'),
  ('go broken', '壊れる', '中2', '標準', true, ARRAY['go broken'], 'premium'),
  ('go for a walk', '散歩に出かける', '中2', '基礎', true, ARRAY['go for a walk'], 'premium'),
  ('go shopping', '買い物に行く', '中1', '基礎', true, ARRAY['go shopping'], 'premium'),
  ('god', '神', '中2', '標準', false, ARRAY['god'], 'premium'),
  ('greet', '〜に挨拶する、迎える', '中3', '標準', false, ARRAY['greet'], 'premium'),
  ('greenhouse', '温室', '中3', '標準', false, ARRAY['greenhouse'], 'premium'),
  ('grocery', '食料雑貨店、食料雑貨類', '中2', '標準', false, ARRAY['grocery'], 'premium'),
  ('groundwater', '地下水', '中3', '難関', false, ARRAY['groundwater'], 'premium'),
  ('handicap', '不利な条件、障害', '中3', '難関', false, ARRAY['handicap'], 'premium'),
  ('handshake', '握手', '中2', '標準', false, ARRAY['handshake'], 'premium'),
  ('hardware', '（コンピュータの）機械本体、金物類', '中3', '難関', false, ARRAY['hardware'], 'premium'),
  ('harm', '害、〜を傷つける', '中3', '標準', false, ARRAY['harm'], 'premium'),
  ('harvest', '収穫、〜を収穫する', '中3', '標準', false, ARRAY['harvest'], 'premium'),
  ('have a look at', '〜を見る、〜に目を向ける', '中2', '基礎', true, ARRAY['have a look at'], 'premium'),
  ('headache', '頭痛', '中2', '標準', false, ARRAY['headache'], 'premium'),
  ('headline', '（新聞などの）見出し', '中3', '標準', false, ARRAY['headline'], 'premium'),
  ('hospitality', 'おもてなし、手厚いもてなし', '中3', '難関', false, ARRAY['hospitality'], 'premium'),
  ('household', '世帯、家庭の', '中3', '難関', false, ARRAY['household'], 'premium'),
  ('housework', '家事', '中2', '標準', false, ARRAY['housework'], 'premium'),
  ('huge', '巨大な、莫大な', '中3', '標準', false, ARRAY['huge'], 'premium'),
  ('humanity', '人類、人間性', '中3', '難関', false, ARRAY['humanity'], 'premium'),
  ('ideal', '理想的な、理想', '中3', '標準', false, ARRAY['ideal'], 'premium'),
  ('identify', '〜を特定する、確認する', '中3', '難関', false, ARRAY['identify'], 'premium'),
  ('identity', 'アイデンティティ、身元、独自性', '中3', '難関', false, ARRAY['identity'], 'premium'),
  ('ignore', '〜を無視する', '中3', '標準', false, ARRAY['ignore'], 'premium'),
  ('illness', '病気', '中3', '標準', false, ARRAY['illness'], 'premium'),
  ('image', '画像、映像、イメージ', '中2', '標準', false, ARRAY['image'], 'premium'),
  ('imagination', '想像力', '中3', '標準', false, ARRAY['imagination'], 'premium'),
  ('immediate', '即座の、直接の', '中3', '難関', false, ARRAY['immediate'], 'premium'),
  ('import', '〜を輸入する、輸入', '中3', '標準', false, ARRAY['import'], 'premium'),
  ('importance', '重要性', '中3', '標準', false, ARRAY['importance'], 'premium'),
  ('indeed', '本当に、実際に', '中3', '標準', false, ARRAY['indeed'], 'premium'),
  ('individual', '個人の、個々の、個人', '中3', '難関', false, ARRAY['individual'], 'premium'),
  ('industrial', '産業の、工業の', '中3', '標準', false, ARRAY['industrial'], 'premium'),
  ('innovation', '技術革新、革新', '中3', '標準', false, ARRAY['innovation'], 'premium'),
  ('inspire', '〜にひらめきを与える、奮い立たせる', '中3', '難関', false, ARRAY['inspire'], 'premium'),
  ('institution', '機関、施設、制度', '中3', '難関', false, ARRAY['institution'], 'premium'),
  ('intelligent', '知能の高い、賢い', '中3', '標準', false, ARRAY['intelligent'], 'premium'),
  ('jail', '刑務所、拘置所', '中3', '難関', false, ARRAY['jail','prison'], 'premium'),
  ('jealous', '嫉妬深い、うらやんで', '中3', '標準', false, ARRAY['jealous'], 'premium'),
  ('jewelry', '宝石類、宝飾品', '中3', '標準', false, ARRAY['jewelry'], 'premium'),
  ('join hands', '手を取り合う、協力する', '中2', '標準', true, ARRAY['join hands'], 'premium'),
  ('judgment', '判断、裁判', '中3', '難関', false, ARRAY['judgment'], 'premium'),
  ('just in case', '念のため、万が一に備えて', '中2', '標準', true, ARRAY['just in case'], 'premium'),
  ('keen', '鋭い、熱心な', '中3', '難関', false, ARRAY['keen'], 'premium'),
  ('keep in touch', '連絡を取り合う', '中2', '標準', true, ARRAY['keep in touch'], 'premium'),
  ('keep quiet', '静かにしている', '中1', '基礎', true, ARRAY['keep quiet'], 'premium'),
  ('key factor', '鍵となる要因、重要な要素', '中3', '難関', true, ARRAY['key factor'], 'premium'),
  ('kindness', '親切、優しさ', '中2', '基礎', false, ARRAY['kindness'], 'premium'),
  ('kingdom', '王国', '中2', '標準', false, ARRAY['kingdom'], 'premium'),
  ('knit', '〜を編む', '中2', '標準', false, ARRAY['knit'], 'premium'),
  ('knot', '（ひもなどの）結び目', '中3', '難関', false, ARRAY['knot'], 'premium'),
  ('labor', '労働、労働力', '中3', '標準', false, ARRAY['labor'], 'premium'),
  ('landscape', '風景、景色', '中3', '標準', false, ARRAY['landscape'], 'premium'),
  ('laughter', '笑い、笑い声', '中3', '標準', false, ARRAY['laughter'], 'premium'),
  ('launch', '（ロケットを）打ち上げる、（事業を）立ち上げる', '中3', '難関', false, ARRAY['launch'], 'premium'),
  ('lay off', '〜を一時解雇する、やめる', '中3', '難関', true, ARRAY['lay off'], 'premium'),
  ('lead a life', '生活を送る', '中3', '標準', true, ARRAY['lead a life'], 'premium'),
  ('leadership', '指導力、リーダーシップ', '中3', '標準', false, ARRAY['leadership'], 'premium'),
  ('leaflet', 'ちらし、パンフレット', '中3', '難関', false, ARRAY['leaflet','pamphlet'], 'premium'),
  ('lean', '傾く、もたれかかる', '中3', '難関', false, ARRAY['lean'], 'premium'),
  ('learn by heart', '〜を暗記する', '中2', '標準', true, ARRAY['learn by heart','memorize'], 'premium'),
  ('leave behind', '〜を置き忘れる、後に残す', '中2', '標準', true, ARRAY['leave behind'], 'premium'),
  ('leave out', '〜を省く、除外する', '中3', '難関', true, ARRAY['leave out'], 'premium'),
  ('legal', '法律上の、合法の', '中3', '難関', false, ARRAY['legal'], 'premium'),
  ('legend', '伝説', '中2', '標準', false, ARRAY['legend'], 'premium'),
  ('lend a hand', '手を貸す、助ける', '中2', '基礎', true, ARRAY['lend a hand','help'], 'premium'),
  ('less', 'より少ない、より少なく', '中3', '標準', false, ARRAY['less'], 'premium'),
  ('let down', '〜をがっかりさせる、失望させる', '中3', '難関', true, ARRAY['let down','disappoint'], 'premium'),
  ('let in', '〜を中に入れる、通す', '中2', '基礎', true, ARRAY['let in'], 'premium'),
  ('librarian', '司書、図書館員', '中3', '難関', false, ARRAY['librarian'], 'premium'),
  ('license', '免許、認可', '中3', '標準', false, ARRAY['license'], 'premium'),
  ('lifespan', '寿命、耐用年数', '中3', '難関', false, ARRAY['lifespan'], 'premium'),
  ('lifestyle', 'ライフスタイル、生活様式', '中2', '標準', false, ARRAY['lifestyle'], 'premium'),
  ('lift', '〜を持ち上げる、エレベーター', '中2', '標準', false, ARRAY['lift'], 'premium'),
  ('lighten', '〜を軽くする、明るくする', '中3', '難関', false, ARRAY['lighten'], 'premium'),
  ('likely', '〜しそうな、おそらく', '中3', '難関', false, ARRAY['likely'], 'premium'),
  ('lineup', '顔ぶれ、ラインナップ', '中3', '難関', false, ARRAY['lineup'], 'premium'),
  ('link', '〜をつなぐ、関連性、リンク', '中3', '標準', false, ARRAY['link'], 'premium'),
  ('liquid', '液体、液体の', '中3', '標準', false, ARRAY['liquid'], 'premium'),
  ('litter', '（公共の場所の）ごみ、〜にごみを投げ捨てる', '中3', '難関', false, ARRAY['litter','trash','garbage'], 'premium'),
  ('lively', '元気な、活気のある', '中3', '標準', false, ARRAY['lively'], 'premium'),
  ('load', '（重い）荷物、〜に荷を積む', '中3', '標準', false, ARRAY['load'], 'premium'),
  ('local government', '地方自治体', '中3', '標準', true, ARRAY['local government'], 'premium'),
  ('log in', 'ログインする', '中2', '基礎', true, ARRAY['log in','log on'], 'premium'),
  ('long-term', '長期的な、長期の', '中3', '難関', true, ARRAY['long-term'], 'premium'),
  ('magnificent', '壮大で美しい、見事な', '中3', '難関', false, ARRAY['magnificent'], 'premium'),
  ('maintain', '〜を維持する、保つ', '中3', '難関', false, ARRAY['maintain'], 'premium'),
  ('make public', '〜を公表する、明らかにする', '中3', '標準', true, ARRAY['make public'], 'premium'),
  ('make use of', '〜を利用する、活用する', '中3', '標準', true, ARRAY['make use of','use'], 'premium'),
  ('manufacturer', '製造業者、メーカー', '中3', '難関', false, ARRAY['manufacturer','maker'], 'premium'),
  ('marriage', '結婚', '中3', '標準', false, ARRAY['marriage'], 'premium'),
  ('massive', '巨大な、大量の', '中3', '難関', false, ARRAY['massive'], 'premium'),
  ('masterpiece', '傑作、名作', '中3', '標準', false, ARRAY['masterpiece'], 'premium'),
  ('mayor', '市長、町長', '中3', '標準', false, ARRAY['mayor'], 'premium'),
  ('meaningful', '意味のある、有意義な', '中3', '標準', false, ARRAY['meaningful'], 'premium'),
  ('means', '手段、方法', '中3', '難関', false, ARRAY['means'], 'premium'),
  ('measure', '〜を測定する、対策', '中3', '標準', false, ARRAY['measure'], 'premium'),
  ('measurement', '測定、寸法', '中3', '難関', false, ARRAY['measurement'], 'premium'),
  ('mechanism', '仕組み、メカニズム', '中3', '難関', false, ARRAY['mechanism'], 'premium'),
  ('media', 'メディア、媒体', '中3', '標準', false, ARRAY['media'], 'premium'),
  ('migration', '移住、移動', '中3', '難関', false, ARRAY['migration'], 'premium'),
  ('misunderstanding', '誤解', '中3', '標準', false, ARRAY['misunderstanding'], 'premium'),
  ('monument', '記念碑、遺跡', '中3', '標準', false, ARRAY['monument'], 'premium'),
  ('mostly', '大部分は、たいてい', '中3', '標準', false, ARRAY['mostly'], 'premium'),
  ('national border', '国境', '中2', '標準', true, ARRAY['national border'], 'premium'),
  ('native country', '祖国、母国', '中3', '標準', true, ARRAY['native country','motherland'], 'premium'),
  ('natural disaster', '自然災害', '中3', '基礎', true, ARRAY['natural disaster'], 'premium'),
  ('natural talent', '生まれつきの才能', '中3', '標準', true, ARRAY['natural talent'], 'premium'),
  ('navigation', '航海、ナビゲーション', '中3', '難関', false, ARRAY['navigation'], 'premium'),
  ('negotiate', '〜を交渉する、話し合う', '中3', '難関', false, ARRAY['negotiate'], 'premium'),
  ('negotiation', '交渉、話し合い', '中3', '難関', false, ARRAY['negotiation'], 'premium'),
  ('nevertheless', 'それにもかかわらず', '中3', '難関', false, ARRAY['nevertheless'], 'premium'),
  ('no doubt', '疑いなく、確かに', '中3', '標準', true, ARRAY['no doubt'], 'premium'),
  ('nonsense', '無意味な言葉、ナンセンス', '中3', '標準', false, ARRAY['nonsense'], 'premium'),
  ('not always', 'いつも〜とは限らない（部分否定）', '中3', '標準', true, ARRAY['not always'], 'premium'),
  ('not at all', '少しも〜ない、どういたしまして', '中2', '基礎', true, ARRAY['not at all'], 'premium'),
  ('notable', '注目に値する、著名な', '中3', '難関', false, ARRAY['notable'], 'premium'),
  ('note down', '〜を書き留める、メモする', '中2', '基礎', true, ARRAY['note down','write down'], 'premium'),
  ('notion', '概念、考え、意見', '中3', '難関', false, ARRAY['notion','idea','concept'], 'premium'),
  ('nuclear energy', '原子力エネルギー', '中3', '標準', true, ARRAY['nuclear energy'], 'premium'),
  ('nuclear weapon', '核兵器', '中3', '標準', true, ARRAY['nuclear weapon'], 'premium'),
  ('nutrient', '栄養素、栄養分', '中3', '難関', false, ARRAY['nutrient'], 'premium'),
  ('nutrition', '栄養、栄養摂取', '中3', '難関', false, ARRAY['nutrition'], 'premium'),
  ('obligation', '義務、責務', '中3', '難関', false, ARRAY['obligation','duty'], 'premium'),
  ('obstacle', '障害（物）、邪魔', '中3', '難関', false, ARRAY['obstacle'], 'premium'),
  ('obviously', '明らかに、言うまでもなく', '中3', '難関', false, ARRAY['obviously'], 'premium'),
  ('on a large scale', '大規模に', '中3', '標準', true, ARRAY['on a large scale'], 'premium'),
  ('on a regular basis', '定期的に、日常的に', '中3', '難関', true, ARRAY['on a regular basis','regularly'], 'premium'),
  ('on the increase', '増加中で、増加傾向にある', '中3', '標準', true, ARRAY['on the increase'], 'premium'),
  ('one after another', '次から次へと、続々と', '中3', '標準', true, ARRAY['one after another'], 'premium'),
  ('online class', 'オンライン授業', '中2', '基礎', true, ARRAY['online class'], 'premium'),
  ('openly', '公然と、率直に', '中3', '標準', false, ARRAY['openly'], 'premium'),
  ('opponent', '（試合や議論の）相手、敵', '中3', '難関', false, ARRAY['opponent'], 'premium'),
  ('oppose', '〜に反対する', '中3', '難関', false, ARRAY['oppose'], 'premium'),
  ('opposed', '反対されて、対立して', '中3', '難関', false, ARRAY['opposed'], 'premium'),
  ('opposition', '反対、対立', '中3', '難関', false, ARRAY['opposition'], 'premium'),
  ('optimistic', '楽観的な、前向きな', '中3', '標準', false, ARRAY['optimistic'], 'premium'),
  ('oral', '口頭の、口頭での', '中3', '標準', false, ARRAY['oral'], 'premium'),
  ('organism', '生物、有機体', '中3', '難関', false, ARRAY['organism'], 'premium'),
  ('organization', '組織、団体', '中3', '標準', false, ARRAY['organization'], 'premium'),
  ('package tour', 'パック旅行、パッケージツアー', '中2', '標準', true, ARRAY['package tour'], 'premium'),
  ('painful', '痛い、つらい', '中3', '標準', false, ARRAY['painful'], 'premium'),
  ('parliament', '議会、国会', '中3', '難関', false, ARRAY['parliament','diet'], 'premium'),
  ('part-time job', 'アルバイト', '中2', '標準', true, ARRAY['part-time job'], 'premium'),
  ('partially', '部分的に、一部は', '中3', '難関', false, ARRAY['partially'], 'premium'),
  ('partly', '一部分は、ある程度は', '中3', '標準', false, ARRAY['partly'], 'premium'),
  ('passby', '通り過ぎる', '中2', '基礎', true, ARRAY['passby'], 'premium'),
  ('passenger train', '旅客列車', '中2', '標準', true, ARRAY['passenger train'], 'premium'),
  ('passionate', '情熱的な、熱烈な', '中3', '難関', false, ARRAY['passionate'], 'premium'),
  ('pay attention', '注意を払う、注目する', '中2', '基礎', true, ARRAY['pay attention'], 'premium'),
  ('pay back', '（借りた金を）返す、報復する', '中2', '基礎', true, ARRAY['pay back'], 'premium'),
  ('payment', '支払い、納付', '中3', '標準', false, ARRAY['payment'], 'premium'),
  ('penalty', '刑罰、罰金、ペナルティ', '中3', '難関', false, ARRAY['penalty'], 'premium'),
  ('pension', '年金', '中3', '難関', false, ARRAY['pension'], 'premium'),
  ('personally', '個人的に、自分としては', '中3', '標準', false, ARRAY['personally'], 'premium'),
  ('qualification', '資格、免許', '中3', '難関', false, ARRAY['qualification'], 'premium'),
  ('qualify', '資格を得る、〜に資格を与える', '中3', '難関', false, ARRAY['qualify'], 'premium'),
  ('quality of life', '生活の質、QOL', '中3', '難関', true, ARRAY['quality of life'], 'premium'),
  ('quarrel', '口論、口論する', '中3', '標準', false, ARRAY['quarrel','argument'], 'premium'),
  ('quarter', '4分の1、15分', '中2', '標準', false, ARRAY['quarter'], 'premium'),
  ('questionnaire', 'アンケート、質問票', '中3', '難関', false, ARRAY['questionnaire'], 'premium'),
  ('quick decision', '即断、素早い決定', '中3', '標準', true, ARRAY['quick decision'], 'premium'),
  ('quietly', '静かに', '中1', '基礎', false, ARRAY['quietly'], 'premium'),
  ('quit', '〜をやめる', '中3', '標準', false, ARRAY['quit','stop'], 'premium'),
  ('quite a few', 'かなり多くの、かなりの数の', '中2', '標準', true, ARRAY['quite a few','many'], 'premium'),
  ('quiz', '小テスト、クイズ', '中1', '基礎', false, ARRAY['quiz'], 'premium'),
  ('quote', '〜を引用する、引用文', '中3', '難関', false, ARRAY['quote'], 'premium'),
  ('racial', '人種の、人種的な', '中3', '難関', false, ARRAY['racial'], 'premium'),
  ('rainy day', '雨の日、万が一の時', '中1', '基礎', true, ARRAY['rainy day'], 'premium'),
  ('range of', '〜の範囲、多様な〜', '中3', '標準', true, ARRAY['range of'], 'premium'),
  ('rapidly', '急速に、速く', '中3', '標準', false, ARRAY['rapidly'], 'premium'),
  ('rarely', 'めったに〜ない', '中3', '難関', false, ARRAY['rarely','seldom'], 'premium'),
  ('reach a conclusion', '結論に達する', '中3', '標準', true, ARRAY['reach a conclusion'], 'premium'),
  ('reach out to', '〜に援助の手を差し伸べる、連絡を取る', '中3', '難関', true, ARRAY['reach out to'], 'premium'),
  ('react', '反応する、反発する', '中3', '難関', false, ARRAY['react'], 'premium'),
  ('reaction', '反応、反発', '中3', '難関', false, ARRAY['reaction'], 'premium'),
  ('readily', '快く、容易に、すぐに', '中3', '難関', false, ARRAY['readily'], 'premium'),
  ('readiness', '準備ができていること、覚悟', '中3', '難関', false, ARRAY['readiness'], 'premium'),
  ('real estate', '不動産、土地や建物', '中3', '難関', true, ARRAY['real estate'], 'premium'),
  ('realistic', '現実的な、実用的な', '中3', '標準', false, ARRAY['realistic'], 'premium'),
  ('reality', '現実、現実性', '中3', '難関', false, ARRAY['reality'], 'premium'),
  ('rebuild', '〜を再建する、建て直す', '中3', '標準', false, ARRAY['rebuild'], 'premium'),
  ('recognition', '認識、承認、見覚え', '中3', '難関', false, ARRAY['recognition'], 'premium'),
  ('recommendation', '推薦、勧告', '中3', '難関', false, ARRAY['recommendation'], 'premium'),
  ('recovery', '回復、復旧', '中3', '難関', false, ARRAY['recovery'], 'premium'),
  ('recreation', '気晴らし、レクリエーション', '中2', '標準', false, ARRAY['recreation'], 'premium'),
  ('reduce waste', 'ごみを減らす', '中3', '標準', true, ARRAY['reduce waste'], 'premium'),
  ('reduction', '減少、削減', '中3', '難関', false, ARRAY['reduction'], 'premium'),
  ('reform', '改革、〜を改革する', '中3', '難関', false, ARRAY['reform'], 'premium'),
  ('refugee camp', '難民キャンプ', '中3', '標準', true, ARRAY['refugee camp'], 'premium'),
  ('refusal', '拒絶、拒否', '中3', '難関', false, ARRAY['refusal'], 'premium'),
  ('regional', '地域の、地方の', '中3', '標準', false, ARRAY['regional'], 'premium'),
  ('safely', '安全に、無事に', '中2', '基礎', false, ARRAY['safely'], 'premium'),
  ('safety drill', '安全訓練、避難訓練', '中2', '標準', true, ARRAY['safety drill','evacuation drill'], 'premium'),
  ('save energy', '省エネする、エネルギーを節約する', '中2', '基礎', true, ARRAY['save energy'], 'premium'),
  ('scenery', '風景、景色', '中3', '標準', false, ARRAY['scenery','landscape'], 'premium'),
  ('scholarship', '奨学金', '中3', '難関', false, ARRAY['scholarship'], 'premium'),
  ('scientific', '科学的な、科学の', '中3', '標準', false, ARRAY['scientific'], 'premium'),
  ('seafood', 'シーフード、海産物', '中2', '基礎', false, ARRAY['seafood'], 'premium'),
  ('seasonal', '季節の、季節的な', '中3', '標準', false, ARRAY['seasonal'], 'premium'),
  ('secondary school', '中等学校（中学校・高校）', '中3', '難関', true, ARRAY['secondary school'], 'premium'),
  ('see a doctor', '医者に診てもらう', '中2', '基礎', true, ARRAY['see a doctor','go to the hospital'], 'premium'),
  ('seek', '〜を探し求める、求める', '中3', '難関', false, ARRAY['seek','look for'], 'premium'),
  ('seem to do', '〜するようだ、〜と思われる', '中2', '標準', true, ARRAY['seem to do'], 'premium'),
  ('set a rule', '規則を定める、ルールを作る', '中2', '基礎', true, ARRAY['set a rule','make a rule'], 'premium'),
  ('setting', '設定、背景、環境', '中2', '標準', false, ARRAY['setting'], 'premium'),
  ('shake hands', '握手する', '中2', '基礎', true, ARRAY['shake hands'], 'premium'),
  ('shortage', '不足', '中3', '難関', false, ARRAY['shortage'], 'premium'),
  ('sign up', '登録する、申し込む', '中2', '標準', true, ARRAY['sign up'], 'premium'),
  ('solar panel', 'ソーラーパネル、太陽光パネル', '中3', '標準', true, ARRAY['solar panel'], 'premium'),
  ('target', '標的、目標、〜を目標にする', '中3', '標準', false, ARRAY['target','goal'], 'premium'),
  ('taxpayer', '納税者', '中3', '難関', false, ARRAY['taxpayer'], 'premium'),
  ('teamwork', 'チームワーク、共同作業', '中2', '基礎', false, ARRAY['teamwork'], 'premium'),
  ('technical term', '専門用語', '中3', '難関', true, ARRAY['technical term'], 'premium'),
  ('tell a lie', '嘘をつく', '中2', '基礎', true, ARRAY['tell a lie'], 'premium'),
  ('text message', '（携帯電話の）ショートメッセージ、メール', '中2', '基礎', true, ARRAY['text message'], 'premium'),
  ('thankful', '感謝している、ありがたく思う', '中3', '標準', false, ARRAY['thankful','grateful'], 'premium'),
  ('throughout', '〜の至る所に、〜の間ずっと', '中3', '標準', false, ARRAY['throughout'], 'premium'),
  ('tight schedule', 'きつい予定、過密スケジュール', '中3', '標準', true, ARRAY['tight schedule'], 'premium'),
  ('time limit', '期限、時間制限', '中2', '基礎', true, ARRAY['time limit'], 'premium'),
  ('tourist attraction', '観光名所、観光スポット', '中3', '標準', true, ARRAY['tourist attraction'], 'premium'),
  ('traffic rules', '交通規則、交通ルール', '中2', '基礎', true, ARRAY['traffic rules','traffic rule'], 'premium'),
  ('transportation cost', '輸送費、交通費', '中3', '標準', true, ARRAY['transportation cost'], 'premium'),
  ('trash can', 'ごみ箱', '中1', '基礎', true, ARRAY['trash can','garbage can'], 'premium'),
  ('trustworthy', '信頼できる、頼りになる', '中3', '難関', false, ARRAY['trustworthy','reliable'], 'premium'),
  ('ultimately', '結局、最終的に', '中3', '難関', false, ARRAY['ultimately','finally'], 'premium'),
  ('unable to do', '〜することができない', '中3', '難関', true, ARRAY['unable to do'], 'premium'),
  ('uncomfortable', '不快な、居心地の悪い', '中3', '標準', false, ARRAY['uncomfortable'], 'premium'),
  ('unconscious', '意識を失った、無意識の', '中3', '難関', false, ARRAY['unconscious'], 'premium'),
  ('under control', '制御されて、管理されて', '中3', '標準', true, ARRAY['under control'], 'premium'),
  ('underground', '地下の、地下に', '中2', '標準', false, ARRAY['underground'], 'premium'),
  ('unemployment', '失業、失業率', '中3', '難関', false, ARRAY['unemployment'], 'premium'),
  ('unexpected', '思いがけない、不意の', '中3', '標準', false, ARRAY['unexpected'], 'premium'),
  ('unfortunate', '不運な、残念な', '中3', '標準', false, ARRAY['unfortunate'], 'premium'),
  ('unfortunately', 'あいにく、不運にも', '中3', '標準', false, ARRAY['unfortunately'], 'premium'),
  ('unique culture', '独特な文化、独自の文化', '中3', '標準', true, ARRAY['unique culture'], 'premium'),
  ('unit price', '単価', '中3', '難関', true, ARRAY['unit price'], 'premium'),
  ('unite nations', '国々を団結させる、統合する', '中3', '標準', true, ARRAY['unite nations'], 'premium'),
  ('universal', '普遍的な、世界共通の', '中3', '難関', false, ARRAY['universal'], 'premium'),
  ('university student', '大学生', '中2', '基礎', true, ARRAY['university student','college student'], 'premium'),
  ('unknown', '未知の、知られていない', '中3', '標準', false, ARRAY['unknown'], 'premium'),
  ('unlikely', '〜しそうにない、起こりそうにない', '中3', '難関', false, ARRAY['unlikely'], 'premium'),
  ('unnecessary', '不必要な、無用な', '中3', '標準', false, ARRAY['unnecessary'], 'premium'),
  ('unusual', '珍しい、普通でない', '中2', '標準', false, ARRAY['unusual'], 'premium'),
  ('valuable experience', '貴重な経験', '中3', '標準', true, ARRAY['valuable experience'], 'premium'),
  ('variety of', 'さまざまな〜、多種多様な〜', '中3', '標準', true, ARRAY['variety of'], 'premium'),
  ('various cultures', 'さまざまな文化', '中3', '標準', true, ARRAY['various cultures'], 'premium'),
  ('video class', '動画授業、ビデオ講義', '中2', '基礎', true, ARRAY['video class'], 'premium'),
  ('viewpoint', '観点、見地、見方', '中3', '標準', false, ARRAY['viewpoint','point of view'], 'premium'),
  ('vision', '視覚、未来像、ビジョン', '中3', '標準', false, ARRAY['vision'], 'premium'),
  ('visit abroad', '海外を訪問する', '中2', '標準', true, ARRAY['visit abroad'], 'premium'),
  ('visual', '視覚の、目に見える', '中3', '標準', false, ARRAY['visual'], 'premium'),
  ('vital role', '極めて重要な役割', '中3', '難関', true, ARRAY['vital role'], 'premium'),
  ('voice message', '音声メッセージ、留守電', '中2', '基礎', true, ARRAY['voice message'], 'premium'),
  ('vote for', '〜に投票する', '中3', '難関', true, ARRAY['vote for'], 'premium'),
  ('wage', '賃金、給料', '中3', '難関', false, ARRAY['wage','salary'], 'premium'),
  ('wait in line', '列に並んで待つ', '中2', '基礎', true, ARRAY['wait in line'], 'premium'),
  ('wake up early', '早く目が覚める、早起きする', '中1', '基礎', true, ARRAY['wake up early'], 'premium'),
  ('walk dog', '犬を散歩させる', '中1', '基礎', true, ARRAY['walk dog','walk the dog'], 'premium'),
  ('warning sign', '警告サイン、前兆、標識', '中3', '標準', true, ARRAY['warning sign'], 'premium'),
  ('waste money', 'お金を無駄遣いする', '中2', '標準', true, ARRAY['waste money'], 'premium'),
  ('waste time', '時間を無駄にする', '中2', '標準', true, ARRAY['waste time'], 'premium'),
  ('water resource', '水資源', '中3', '標準', true, ARRAY['water resource','water resources'], 'premium'),
  ('weak point', '弱点、欠点', '中2', '基礎', true, ARRAY['weak point','weakness'], 'premium'),
  ('wealthy citizen', '裕福な市民、富裕層', '中3', '標準', true, ARRAY['wealthy citizen'], 'premium'),
  ('web browser', 'ウェブブラウザ', '中2', '基礎', true, ARRAY['web browser'], 'premium'),
  ('weekly report', '週報、週次報告書', '中3', '標準', true, ARRAY['weekly report'], 'premium'),
  ('welfare', '福祉、幸福', '中3', '難関', false, ARRAY['welfare'], 'premium'),
  ('well-known', 'よく知られている、有名な', '中3', '標準', true, ARRAY['well-known','famous'], 'premium'),
  ('wheelchair', '車椅子', '中3', '標準', false, ARRAY['wheelchair'], 'premium'),
  ('whole world', '全世界、世界中', '中3', '標準', true, ARRAY['whole world'], 'premium'),
  ('wide range', '広範囲、幅広い', '中3', '標準', true, ARRAY['wide range'], 'premium'),
  ('widespread', '広範囲に及ぶ、蔓延している', '中3', '難関', false, ARRAY['widespread'], 'premium'),
  ('wildlife', '野生生物', '中3', '標準', false, ARRAY['wildlife'], 'premium'),
  ('willing to do', '喜んで〜する、〜するのをいとわない', '中3', '難関', true, ARRAY['willing to do'], 'premium'),
  ('wisdom', '知恵、賢さ', '中3', '標準', false, ARRAY['wisdom'], 'premium'),
  ('wise choice', '賢い選択', '中3', '標準', true, ARRAY['wise choice'], 'premium'),
  ('withdraw', '（お金を）引き出す、撤退する', '中3', '難関', false, ARRAY['withdraw'], 'premium'),
  ('workload', '仕事量、作業負荷', '中3', '難関', false, ARRAY['workload'], 'premium'),
  ('worldwide', '世界的な、世界中に', '中3', '標準', false, ARRAY['worldwide'], 'premium'),
  ('worth visiting', '訪れる価値がある', '中3', '標準', true, ARRAY['worth visiting'], 'premium'),
  ('worthwhile', '時間をかける価値がある、やりがいのある', '中3', '難関', false, ARRAY['worthwhile'], 'premium'),
  ('yearly', '年1回の、毎年の', '中3', '標準', false, ARRAY['yearly','annual'], 'premium'),
  ('yield', '（農作物などを）産出する、もたらす', '中3', '難関', false, ARRAY['yield'], 'premium'),
  ('youngster', '若者、子供', '中3', '標準', false, ARRAY['youngster','youth','teenager'], 'premium'),
  ('youth culture', '若者文化', '中3', '標準', true, ARRAY['youth culture'], 'premium'),
  ('zeal', '熱意、熱心さ', '中3', '難関', false, ARRAY['zeal','passion'], 'premium'),
  ('zero emission', '排出ゼロ、ゼロエミッション', '中3', '標準', true, ARRAY['zero emission'], 'premium'),
  ('zero waste', 'ごみゼロ、ゼロ・ウェイスト', '中3', '標準', true, ARRAY['zero waste'], 'premium')
ON CONFLICT (word) DO NOTHING;