-- 高校受験語彙（自動生成・冪等・既存は保護）part 2
INSERT INTO words (word, reading, meaning, example_en, example_ja, grade, level, tier, is_idiom, tags, answers_en) VALUES
('garden','ガーデン','庭','They have a beautiful garden.','彼らは美しい庭を持っている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['garden']),
('gas','ガス','ガス、気体','Turn off the gas.','ガスを止めなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['gas']),
('gate','ゲート','門','Meet me at the school gate.','校門で会いましょう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['gate']),
('gather','ギャザー','集める、集まる','People gathered in the park.','人々が公園に集まった。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['gather','collect']),
('general','ジェネラル','一般的な、全体的な','This is a general rule.','これは一般的な規則だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['general']),
('generation','ジェネレーション','世代','We are the new generation.','私たちは新しい世代だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['generation']),
('gentleman','ジェントルマン','紳士','He is a true gentleman.','彼は真の紳士だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['gentleman']),
('geography','ジオグラフィー','地理','I study geography.','私は地理を勉強している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['geography']),
('ghost','ゴースト','幽霊','Do you believe in ghosts?','幽霊を信じますか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['ghost']),
('gift','ギフト','贈り物','This is a gift for you.','これはあなたへの贈り物です。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['gift','present']),
('glad','グラッド','うれしい','I am glad to see you.','あなたに会えてうれしいです。','中2','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['glad','happy']),
('glass','グラス','ガラス、コップ','Bring me a glass of water.','水をグラス1杯持ってきて。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['glass']),
('global','グローバル','地球規模の、世界的な','We must solve global warming.','私たちは地球温暖化を解決しなければならない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['global']),
('glove','グローブ','手袋','I bought a pair of gloves.','手袋を1双買った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['glove']),
('goal','ゴール','目標、得点','What is your final goal?','あなたの最終的な目標は何ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['goal']),
('gold','ゴールド','金、黄金','This ring is made of gold.','この指輪は金でできている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['gold']),
('golf','ゴルフ','ゴルフ','My father plays golf on Sundays.','父は日曜日にゴルフをする。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['golf']),
('government','ガバメント','政府','The government made a new law.','政府は新しい法律を作った。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['government']),
('grade','グレイド','学年、成績','I am in the third grade.','私は3年生です。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['grade']),
('graduate','グラジュエイト','卒業する','He graduated from high school.','彼は高校を卒業した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['graduate']),
('grammar','グラマー','文法','English grammar is difficult.','英語の文法は難しい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['grammar']),
('grand','グランド','壮大な、雄大な','The view was grand.','その景色は壮大だった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['grand']),
('grass','グラス','草、芝生','Don''t walk on the grass.','芝生を歩かないで。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['grass']),
('great','グレイト','偉大な、素晴らしい','You did a great job.','素晴らしい仕事をしたね。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['great','wonderful']),
('green','グリーン','緑色、緑の','I like your green shirt.','あなたの緑のシャツが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['green']),
('ground','グラウンド','地面、運動場','Leaves fell to the ground.','葉が地面に落ちた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['ground']),
('group','グループ','集団、グループ','We worked in groups of four.','私たちは4人のグループで作業した。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['group']),
('grow','グロウ','成長する、育てる','Rice grows in warm places.','米は暖かい場所で育つ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['grow']),
('guess','ゲス','推測する','Can you guess my age?','私の年齢を推測できますか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['guess']),
('guest','ゲスト','客','We have a special guest today.','今日は特別な客がいます。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['guest']),
('guide','ガイド','案内する、案内人','He guided us around the city.','彼は私たちを市内のあちこちへ案内した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['guide']),
('guitar','ギター','ギター','She plays the guitar well.','彼女はギターを弾くのが上手だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['guitar']),
('gun','ガン','銃','He pointed a gun at me.','彼は私に銃を向けた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['gun']),
('guy','ガイ','男、やつ','He is a nice guy.','彼はいいやつだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['guy']),
('habit','ハビット','習慣','Reading is a good habit.','読書は良い習慣だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['habit']),
('hair','ヘア','髪の毛','She has long black hair.','彼女は黒い長髪だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['hair']),
('half','ハーフ','半分、半分の','Cut the apple in half.','リンゴを半分に切りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['half']),
('hall','ホール','会館、廊下','Let''s meet at the city hall.','市役所で会いましょう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hall']),
('happen','ハプン','起こる','What happened to you?','あなたに何が起きたのですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['happen']),
('hard','ハード','一生懸命に、難しい、固い','He studied very hard.','彼はとても一生懸命勉強した。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['hard','difficult']),
('hardly','ハードリー','ほとんど〜ない','I can hardly hear you.','あなたの声がほとんど聞こえない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['hardly']),
('hat','ハット','帽子','Take off your hat.','帽子を脱ぎなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['hat']),
('hate','ヘイト','憎む、ひどく嫌う','I hate washing dishes.','皿洗いが大嫌いだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hate']),
('health','ヘルス','健康','Smoking is bad for your health.','喫煙は健康に悪い。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['health']),
('healthy','ヘルシー','健康な','She is a healthy girl.','彼女は健康な少女だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['healthy']),
('hear','ヒア','聞こえる、聞く','Can you hear the music?','その音楽が聞こえますか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['hear']),
('heart','ハート','心臓、心','My heart is beating fast.','心臓がドキドキしている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['heart']),
('heat','ヒート','熱、暑さ','I can''t stand the heat.','この暑さには耐えられない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['heat']),
('heavy','ヘビー','重い、激しい','This box is too heavy.','この箱は重すぎる。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['heavy']),
('height','ハイト','高さ、身長','What is your height?','あなたの身長はどれくらいですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['height']),
('hero','ヒーロー','英雄、主人公','He is my hero.','彼は私のヒーローだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hero']),
('hide','ハイド','隠す、隠れる','She hid behind the door.','彼女はドアの後ろに隠れた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['hide']),
('high','ハイ','高い','Look at that high building.','あの高い建物を見なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['high']),
('hill','ヒル','丘','The house is on a hill.','その家は丘の上にある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hill']),
('history','ヒストリー','歴史','I am interested in Japanese history.','日本の歴史に興味がある。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['history']),
('hit','ヒット','打つ、当たる','The ball hit my head.','ボールが私の頭に当たった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hit']),
('hold','ホールド','持つ、開催する','She held my hand.','彼女は私の手を握った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hold']),
('hole','ホール','穴','There is a hole in my sock.','靴下に穴が空いている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hole']),
('holiday','ホリデー','休日、祝日','Tomorrow is a national holiday.','明日は国民の祝日だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['holiday']),
('honest','オネスト','正直な','To be honest, I don''t know.','正直に言うと、私は知らない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['honest']),
('honor','オナー','名誉、敬意','It is a great honor.','それは大変な名誉です。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['honor']),
('hope','ホープ','希望する、望む','I hope to see you again.','また会えることを望みます。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hope']),
('horror','ホラー','恐怖','I don''t like horror movies.','ホラー映画は好きではない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['horror']),
('hospital','ホスピタル','病院','He is in the hospital now.','彼は今入院している。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['hospital']),
('host','ホスト','主催者、主人','Japan was the host country.','日本が開催国だった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['host']),
('hotel','ホテル','ホテル','We stayed at a nice hotel.','私たちは素敵なホテルに泊まった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hotel']),
('hour','アワー','時間、1時間','I studied for three hours.','私は3時間勉強した。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['hour']),
('human','ヒューマン','人間の、人類','This is human nature.','これが人間の本性だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['human']),
('humor','ユーモア','ユーモア','He has a good sense of humor.','彼はユーモアのセンスがいい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['humor']),
('hundred','ハンドレッド','100','It costs a hundred dollars.','それは100ドルかかる。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['hundred']),
('hungry','ハングリー','空腹の','I am very hungry.','私はとてもお腹が空いている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['hungry']),
('hunt','ハント','狩る、狩り','They hunt animals for food.','彼らは食料のために動物を狩る。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['hunt']),
('hurry','ハリー','急ぐ','We have to hurry.','私たちは急がなければならない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hurry']),
('hurt','ハート','傷つける、痛む','My back hurts.','背中が痛い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['hurt']),
('husband','ハズバンド','夫','Her husband is a doctor.','彼女の夫は医者だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['husband']),
('ice','アイス','氷','I want some ice in my water.','水に氷を入れてほしい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['ice']),
('idea','アイディア','考え、思いつき','I have a good idea.','私に良い考えがある。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['idea']),
('ill','イル','病気の','He was ill in bed.','彼は病気で寝ていた。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['ill','sick']),
('imagine','イマジン','想像する','Imagine a peaceful world.','平和な世界を想像しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['imagine']),
('impact','インパクト','影響、衝撃','The news had a big impact.','その知らせは大きな衝撃を与えた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['impact']),
('important','インポータント','重要な','This is an important meeting.','これは重要な会議だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['important']),
('impossible','インポッシブル','不可能な','It is impossible for me.','それは私には不可能だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['impossible']),
('improve','インプルーブ','向上させる、改善する','I want to improve my English.','私は英語を向上させたい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['improve']),
('include','インクルード','含む','The price includes tax.','価格には税金が含まれている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['include']),
('increase','インクリース','増える、増やす','The population is increasing.','人口が増加している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['increase']),
('independent','インディペンデント','独立した','India became an independent country.','インドは独立国になった。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['independent']),
('industry','インダストリー','産業、工業','The car industry is growing.','自動車産業は成長している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['industry']),
('influence','インフルエンス','影響、影響を与える','He had a bad influence on me.','彼は私に悪影響を与えた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['influence']),
('information','インフォメーション','情報','I need more information.','もっと情報が必要だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['information']),
('injure','インジャー','傷つける、怪我をさせる','He injured his right leg.','彼は右脚を怪我した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['injure']),
('ink','インク','インク','Write in black ink.','黒のインクで書きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['ink']),
('insect','インセクト','昆虫','I like collecting insects.','私は昆虫採集が好きだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['insect']),
('inside','インサイド','内側、中に','Let''s go inside.','中に入ろう。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['inside']),
('interest','インタレスト','興味、関心','She showed an interest in art.','彼女は芸術に興味を示した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['interest']),
('international','インターナショナル','国際的な','It is an international airport.','それは国際空港だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['international']),
('internet','インターネット','インターネット','I bought it on the Internet.','インターネットでそれを買った。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['internet']),
('interview','インタビュー','面接、インタビュー','I have a job interview tomorrow.','明日は仕事の面接がある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['interview']),
('introduce','イントロデュース','紹介する','Let me introduce my friend.','私の友達を紹介させてください。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['introduce']),
('invent','インベント','発明する','Edison invented the light bulb.','エジソンは電球を発明した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['invent']),
('invite','インバイト','招待する','I invited him to the party.','彼をパーティーに招待した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['invite']),
('island','アイランド','島','Japan is an island country.','日本は島国だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['island']),
('item','アイテム','品目、項目','This item is sold out.','この品目は売り切れだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['item']),
('give back','ギブバック','〜を返す','Give it back to me.','それを私に返しなさい。','中2','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['give back','return']),
('go out','ゴーアウト','外出する','Let''s go out for dinner.','夕食に外出しよう。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['go out']),
('go through','ゴースルー','〜を通り抜ける、経験する','The train went through a tunnel.','電車はトンネルを通り抜けた。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['go through']),
('had better','ハドベター','〜したほうがよい','You had better go now.','あなたはもう行った方がよい。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['had better']),
('hold on','ホールドオン','待つ、電話を切らずにおく','Please hold on a second.','少しお待ちください。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['hold on']),
('hurry up','ハリーアップ','急ぐ','Hurry up, or you''ll be late.','急ぎなさい、さもないと遅れるよ。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['hurry up']),
('in fact','インファクト','実は、実際は','In fact, I don''t like it.','実は、それが好きではない。','中3','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['in fact','actually']),
('in order to','インオーダートゥ','〜するために','He studied hard in order to pass.','彼は合格するために一生懸命勉強した。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['in order to']),
('in time','インタイム','間に合って','We arrived in time.','私たちは間に合って到着した。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['in time']),
('keep in mind','キープインマインド','心に留める、覚えておく','Please keep this in mind.','これを覚えておいてください。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['keep in mind']),
('keep in touch with','キープインタッチウィズ','〜と連絡を取り合う','Let''s keep in touch with each other.','お互いに連絡を取り合おう。','中3','難関','premium',true,ARRAY['高校受験','熟語'],ARRAY['keep in touch with']),
('listen to','リスントゥ','〜を聞く','Listen to me carefully.','私の話を注意深く聞きなさい。','中1','基礎','premium',true,ARRAY['高校受験','熟語'],ARRAY['listen to']),
('look around','ルックアラウンド','見回す','He looked around the room.','彼は部屋を見回した。','中2','標準','premium',true,ARRAY['高校受験','熟語'],ARRAY['look around']),
('lose one''s way','ルーズワンズウェイ','道に迷う','I lost my way in the forest.','私は森の中で道に迷った。','中2','標準','premium',true,ARRAY['高校受験','熟語','同義語'],ARRAY['lose one''s way','lose my way']),
('keep','キープ','保つ、持ち続ける','Keep the room clean.','部屋をきれいに保ちなさい。','中2','基礎','premium',false,ARRAY['高校受験'],ARRAY['keep']),
('key','キー','鍵、重要なもの','Where is the key to the door?','ドアの鍵はどこ？','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['key']),
('keyboard','キーボード','キーボード','He has a new keyboard.','彼は新しいキーボードを持っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['keyboard']),
('kick','キック','ける','Kick the ball.','ボールをけりなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['kick']),
('kid','キッド','子ども、冗談を言う','Are you kidding?','冗談でしょう？','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['kid','child']),
('kill','キル','殺す','The accident killed him.','その事故で彼は死んだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['kill']),
('kilogram','キログラム','キログラム','It weighs one kilogram.','重さは1キログラムだ。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['kilogram','kg']),
('kilometer','キロメーター','キロメートル','It is five kilometers away.','5キロメートル先だ。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['kilometer','km']),
('kind','カインド','親切な、種類','Thank you for being so kind.','親切にしてくれてありがとう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['kind']),
('king','キング','王','He is the king of the country.','彼はその国の王だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['king']),
('kiss','キス','キスする','She kissed her mother.','彼女は母親にキスをした。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['kiss']),
('kitchen','キッチン','台所','My mother is in the kitchen.','母は台所にいます。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['kitchen']),
('knee','ニー','ひざ','I hurt my knee.','ひざを痛めた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['knee']),
('knife','ナイフ','ナイフ、包丁','Use a knife to cut it.','それを切るためにナイフを使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['knife']),
('knock','ノック','ノックする','Knock on the door first.','まずドアをノックしなさい。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['knock']),
('know','ノウ','知っている','Do you know his name?','彼の名前を知っていますか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['know']),
('knowledge','ナレッジ','知識','He has a lot of knowledge.','彼は多くの知識を持っている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['knowledge']),
('label','ラベル','ラベル、札','Read the label carefully.','ラベルを注意深く読みなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['label']),
('laboratory','ラボラトリー','実験室、研究所','He works in a laboratory.','彼は研究所で働いている。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['laboratory','lab']),
('lack','ラック','不足','A lack of sleep is bad.','睡眠不足は体に悪い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['lack']),
('lady','レディ','婦人','Who is that lady?','あの女性は誰ですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['lady']),
('lake','レイク','湖','They swim in the lake.','彼らは湖で泳ぐ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['lake']),
('lamp','ランプ','ランプ、照明','Turn on the desk lamp.','デスクライトをつけなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['lamp']),
('land','ランド','土地、陸地','We saw land at last.','ついに陸地が見えた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['land']),
('language','ランゲージ','言語','What language do they speak?','彼らは何語を話しますか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['language']),
('large','ラージ','大きい','He lives in a large house.','彼は大きな家に住んでいる。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['large','big']),
('last','ラスト','最後の、この前の','This is my last chance.','これが最後のチャンスだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['last']),
('late','レイト','遅れた、遅い','I am sorry I am late.','遅れてすみません。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['late']),
('lately','レイトリー','最近','I have been busy lately.','最近忙しい。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['lately','recently']),
('later','レイター','あとで','See you later.','あとでね。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['later']),
('laugh','ラフ','笑う','Why are you laughing?','なぜ笑っているのですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['laugh']),
('law','ロー','法律','You must follow the law.','法律に従わなければならない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['law']),
('lawyer','ロイヤー','弁護士','He wants to be a lawyer.','彼は弁護士になりたい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['lawyer']),
('lay','レイ','置く、横たえる','Lay the book on the table.','テーブルに本を置きなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['lay']),
('lazy','レイジー','怠惰な、なまけ者の','Don''t be so lazy.','そんなになまけてはいけない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['lazy']),
('lead','リード','導く、先頭に立つ','She led us to the park.','彼女は私たちを公園へ導いた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['lead']),
('leader','リーダー','指導者、リーダー','He is a good leader.','彼は良いリーダーだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['leader']),
('leaf','リーフ','葉','The leaves are turning red.','葉が赤く色づいている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['leaf']),
('learn','ラーン','学ぶ','I want to learn Japanese.','日本語を学びたい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['learn']),
('least','リースト','最小の、少なくとも','At least, try it.','少なくとも、試してみて。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['least']),
('leather','レザー','革、レザー','This bag is made of leather.','このかばんは革製だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['leather']),
('leave','リーヴ','去る、出発する、残す','He left for Tokyo.','彼は東京へ向けて出発した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['leave']),
('lecture','レクチャー','講義','I attended a long lecture.','長い講義に出席した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['lecture']),
('left','レフト','左、左の','Turn left at the corner.','その角を左に曲がりなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['left']),
('leg','レッグ','脚','He hurt his right leg.','彼は右脚を怪我した。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['leg']),
('lend','レンド','貸す','Can you lend me a pen?','ペンを貸してくれますか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['lend']),
('length','レングス','長さ','What is the length of it?','その長さはどれくらいですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['length']),
('lesson','レッスン','授業、教訓','I have a piano lesson.','ピアノのレッスンがある。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['lesson']),
('let','レット','〜させる、〜させてあげる','Let me help you.','手伝わせて。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['let']),
('letter','レター','手紙、文字','I received a letter from him.','彼から手紙を受け取った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['letter']),
('medical','メディカル','医学の、医療の','He needs medical care.','彼は医療的なケアが必要だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['medical']),
('medicine','メディシン','薬、医学','Take this medicine.','この薬を飲みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['medicine']),
('medium','ミディアム','中間の、媒体','I want a medium pizza.','Mサイズのピザがほしい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['medium']),
('meet','ミート','会う、待ち合わせる','Let''s meet at the station.','駅で会いましょう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['meet']),
('meeting','ミーティング','会議、打ち合わせ','We have a meeting now.','今、会議がある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['meeting']),
('melt','メルト','溶ける','The snow is melting.','雪が溶けている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['melt']),
('member','メンバー','一員、会員','He is a member of our team.','彼は私たちのチームの一員だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['member']),
('memory','メモリー','記憶、思い出','I have good memories of it.','それについて良い思い出がある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['memory']),
('men','メン','男たち（manの複数形）','Three men are working.','3人の男が働いている。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['men']),
('mention','メンション','述べる、言及する','Don''t mention it.','どういたしまして（礼には及びません）。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['mention']),
('menu','メニュー','メニュー','Can I see the menu?','メニューを見てもいいですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['menu']),
('message','メッセージ','伝言、メッセージ','Please leave a message.','伝言を残してください。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['message']),
('metal','メタル','金属','This is made of metal.','これは金属製だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['metal']),
('method','メソッド','方法','This is a new method.','これは新しい方法だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['method']),
('middle','ミドル','中央、中間','He is in the middle of talking.','彼は話の最中だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['middle']),
('midnight','ミッドナイト','真夜中','I woke up at midnight.','真夜中に目が覚めた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['midnight']),
('might','マイト','〜かもしれない','It might rain later.','あとで雨が降るかもしれない。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['might']),
('mild','マイルド','穏やかな','The weather is mild today.','今日は穏やかな天気だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['mild']),
('mile','マイル','マイル（距離の単位）','It is two miles away.','2マイル先だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['mile']),
('military','ミリタリー','軍の','He joined the military.','彼は軍に入隊した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['military']),
('milk','ミルク','牛乳','I drink milk every day.','毎日牛乳を飲む。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['milk']),
('mill','ミル','工場、製粉所','He works in the paper mill.','彼は製紙工場で働いている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['mill']),
('million','ミリオン','100万','It costs a million yen.','それは100万円かかる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['million']),
('mind','マインド','精神、嫌がる','Do you mind if I open it?','開けてもいいですか（嫌ですか）。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['mind']),
('mine','マイン','私のもの','This pen is mine.','このペンは私のものだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['mine']),
('mineral','ミネラル','鉱物、ミネラル','Water contains minerals.','水にはミネラルが含まれている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['mineral']),
('minimum','ミニマム','最小の','The minimum cost is low.','最低費用は低い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['minimum']),
('minister','ミニスター','大臣、牧師','He is the foreign minister.','彼は外務大臣だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['minister']),
('minor','マイナー','小さい、重要でない','It is a minor problem.','それは小さな問題だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['minor']),
('minority','マイノリティ','少数派','They are a minority here.','彼らはここでは少数派だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['minority']),
('minute','ミニット','分、少しの間','Wait a minute.','1分待って。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['minute']),
('mirror','ミラー','鏡','Look at yourself in the mirror.','鏡で自分を見なさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['mirror']),
('miss','ミス','逃す、乗り遅れる、懐かしく思う','I missed the last train.','終電に乗り遅れた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['miss']),
('missing','ミッシング','行方不明の、欠けている','The boy is missing.','その少年が行方不明だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['missing']),
('mistake','ミステイク','間違い','I made a mistake.','間違いをした。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['mistake','error']),
('mix','ミックス','混ぜる','Mix the eggs and flour.','卵と小麦粉を混ぜなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['mix']),
('model','モデル','模型、モデル','He built a car model.','彼は車の模型を作った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['model']),
('modern','モダン','現代の','I like modern art.','現代美術が好きだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['modern']),
('moment','モーメント','瞬間','Wait for a moment.','少しの間待ってください。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['moment']),
('money','マネー','お金','I don''t have much money.','あまりお金を持っていない。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['money']),
('monitor','モニター','監視する、モニター','Monitor the progress.','進み具合を監視しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['monitor']),
('monkey','モンキー','サル','Look at the monkey.','サルを見なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['monkey']),
('month','マンス','月（1ヶ月）','I will leave next month.','来月出発する。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['month']),
('mood','ムード','気分、雰囲気','I am in a good mood.','気分が良い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['mood']),
('moon','ムーン','月','The moon is bright tonight.','今夜は月が明るい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['moon']),
('more','モア','より多くの','I want more water.','もっと水がほしい。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['more']),
('morning','モーニング','朝','I study in the morning.','朝に勉強する。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['morning']),
('most','モスト','ほとんどの、最も','Most people like it.','ほとんどの人がそれを好む。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['most']),
('mother','マザー','母','My mother is a teacher.','私の母は先生だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['mother']),
('motion','モーション','動き','She made a motion.','彼女は合図をした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['motion']),
('mountain','マウンテン','山','We climbed the mountain.','私たちは山に登った。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['mountain']),
('mouse','マウス','ネズミ','I saw a mouse.','ネズミを見た。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['mouse']),
('mouth','マウス','口','Open your mouth.','口を開けなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['mouth']),
('move','ムーブ','動く、引っ越す','Don''t move.','動かないで。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['move']),
('movement','ムーブメント','動き、運動','The movement is slow.','その動きは遅い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['movement']),
('movie','ムービー','映画','Let''s see a movie.','映画を見よう。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['movie','film']),
('much','マッチ','多くの','I don''t have much time.','あまり時間がない。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['much']),
('mud','マッド','泥','My shoes are full of mud.','靴が泥だらけだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['mud']),
('multiply','マルチプライ','掛ける、増やす','Multiply 2 by 3.','2に3を掛けなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['multiply']),
('muscle','マッスル','筋肉','Exercise builds muscle.','運動は筋肉を作る。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['muscle']),
('museum','ミュージアム','博物館、美術館','We visited a museum.','博物館を訪れた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['museum']),
('music','ミュージック','音楽','I like listening to music.','音楽を聞くのが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['music']),
('must','マスト','〜しなければならない','You must do your homework.','宿題をしなければならない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['must']),
('my','マイ','私の','This is my book.','これは私の本だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['my']),
('myself','マイセルフ','私自身','I did it by myself.','自分でやった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['myself']),
('mystery','ミステリー','謎、ミステリー','It is a great mystery.','それは大きな謎だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['mystery']),
('name','ネーム','名前','What is your name?','名前は何ですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['name']),
('narrow','ナロウ','狭い','The street is very narrow.','その通りはとても狭い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['narrow']),
('nation','ネイション','国家、国民','The nation is in peace.','その国は平和だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['nation']),
('national','ナショナル','国家の、全国的な','It is a national holiday.','それは国民の祝日だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['national']),
('native','ネイティブ','母国の、その土地の','He is a native speaker.','彼はネイティブスピーカーだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['native']),
('nature','ネイチャー','自然','I like nature.','自然が好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['nature']),
('near','ニア','近くの','Do you live near here?','この近くに住んでいますか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['near']),
('nearly','ニアリー','ほとんど','It is nearly eight o''clock.','ほとんど8時だ。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['nearly','almost']),
('necessary','ネセサリー','必要な','It is necessary to study.','勉強することが必要だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['necessary']),
('neck','ネック','首','He wore a tie around his neck.','彼は首にネクタイをしていた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['neck']),
('need','ニード','必要とする','I need some help.','助けが必要です。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['need']),
('negative','ネガティブ','否定的な、消極的な','Don''t be so negative.','そんなに消極的にならないで。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['negative']),
('neighbor','ネイバー','隣人、近所の人','My neighbors are kind.','隣人は親切だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['neighbor']),
('neighborhood','ネイバーフッド','近所','He lives in this neighborhood.','彼はこの近所に住んでいる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['neighborhood']),
('neither','ナイザー','どちらも〜ない','Neither of them is right.','彼らのどちらも正しくない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['neither']),
('nervous','ナーバス','緊張して、神経質な','I am nervous about the test.','試験のことで緊張している。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['nervous']),
('nest','ネスト','巣','The bird built a nest.','鳥が巣を作った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['nest']),
('net','ネット','網、インターネット','The ball hit the net.','ボールがネットに当たった。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['net']),
('never','ネバー','決して〜ない','I have never been there.','そこへは一度も行ったことがない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['never']),
('new','ニュー','新しい','This is a new computer.','これは新しいコンピュータだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['new']),
('news','ニュース','ニュース、知らせ','Did you hear the news?','そのニュースを聞いた？','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['news']),
('newspaper','ニュースペーパー','新聞','I read the newspaper every day.','毎日新聞を読む。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['newspaper']),
('next','ネクスト','次の','See you next week.','また来週。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['next']),
('nice','ナイス','すてきな、親切な','Have a nice day.','良い一日を。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['nice']),
('night','ナイト','夜','Good night.','おやすみなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['night']),
('no','ノー','いいえ、一つも〜ない','No, thank you.','いいえ、結構です。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['no']),
('nobody','ノーバディ','誰も〜ない','Nobody knows the truth.','真実を知る人は誰もいない。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['nobody','no one']),
('noise','ノイズ','騒音、音','Don''t make noise.','騒音を立てないで。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['noise']),
('none','ノン','だれも〜ない、どれも〜ない','None of them are here.','彼らの誰一人としてここにいない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['none']),
('noon','ヌーン','正午','I had lunch at noon.','正午に昼食を食べた。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['noon']),
('nor','ノー','〜もまた〜ない','He is neither rich nor poor.','彼は金持ちでも貧しくもない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['nor']),
('normal','ノーマル','標準の、正常な','It is a normal day.','いつも通りの一日だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['normal']),
('north','ノース','北、北の','Go north from here.','ここから北へ行きなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['north']),
('nose','ノーズ','鼻','He has a long nose.','彼は鼻が高い（長い）。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['nose']),
('not','ノット','〜ではない','I am not a doctor.','私は医者ではない。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['not']),
('note','ノート','メモ、記録','Take a note.','メモを取りなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['note']),
('notebook','ノートブック','ノート','Write in your notebook.','ノートに書きなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['notebook']),
('nothing','ナッシング','何も〜ない','I have nothing to do.','することはない。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['nothing']),
('notice','ノーティス','気づく、お知らせ','I noticed a mistake.','間違いに気づいた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['notice']),
('noun','ナウン','名詞','Apple is a noun.','「Apple」は名詞だ。','中2','難関','premium',false,ARRAY['高校受験'],ARRAY['noun']),
('now','ナウ','今','I am busy now.','今忙しい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['now']),
('nowhere','ノーウェア','どこにも〜ない','I have nowhere to go.','どこにも行くところがない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['nowhere']),
('number','ナンバー','数、番号','What is your phone number?','電話番号は何ですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['number']),
('nurse','ナース','看護師','She is a kind nurse.','彼女は親切な看護師だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['nurse']),
('nut','ナット','木の実、ナッツ','Squirrels like nuts.','リスは木の実が好きだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['nut']),
('object','オブジェクト','物体、対象、目的','What is that object?','あの物体は何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['object']),
('objective','オブジェクティブ','目的、目標','Our objective is to win.','私たちの目標は勝つことだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['objective']),
('observe','オブザーヴ','観察する、守る','Observe the stars.','星を観察しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['observe']),
('obtain','オブテイン','手に入れる','How can I obtain it?','どうすればそれを手に入れられますか。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['obtain','get']),
('obvious','オブヴィアス','明白な','It is an obvious fact.','それは明白な事実だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['obvious']),
('occasion','オケイジョン','機会、場合','On some occasions, I walk.','時々、歩くことがある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['occasion']),
('ocean','オーシャン','海洋','The Pacific Ocean is large.','太平洋は大きい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['ocean']),
('odd','オッド','奇妙な、奇数の','That is very odd.','それはとても奇妙だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['odd']),
('of','オブ','〜の','A cup of tea.','1杯のお茶。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['of']),
('off','オフ','離れて、休みで','Turn the light off.','電気を消しなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['off']),
('offer','オファー','申し出る、提供する','He offered me help.','彼は助けを申し出てくれた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['offer']),
('office','オフィス','オフィス、事務所','He is in his office.','彼は事務所にいる。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['office']),
('officer','オフィサー','警官、役人','Ask the police officer.','警察官に尋ねなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['officer']),
('official','オフィシャル','公式の','It is an official visit.','それは公式訪問だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['official']),
('often','オフトゥン','しばしば','I often go there.','よくそこへ行く。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['often']),
('oil','オイル','油、石油','Use some olive oil.','オリーブオイルを使いなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['oil']),
('old','オールド','古い、年をとった','This book is old.','この本は古い。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['old']),
('once','ワンス','一度、かつて','I went there once.','一度そこへ行った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['once']),
('one','ワン','1、一つ','I have one sister.','姉（妹）が1人います。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['one']),
('only','オンリー','唯一の、たった〜だけ','You are my only friend.','君が唯一の友達だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['only']),
('onto','オントゥ','〜の上に','He jumped onto the box.','彼は箱の上に飛び乗った。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['onto']),
('open','オープン','開く','Please open the window.','窓を開けてください。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['open']),
('operate','オペレート','操作する、手術する','How do you operate this?','これはどうやって操作しますか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['operate']),
('opinion','オピニオン','意見','What is your opinion?','あなたの意見は何ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['opinion']),
('opportunity','オポチュニティ','機会','I had a good opportunity.','良い機会を得た。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['opportunity','chance']),
('opposite','オポジット','反対の','We live on opposite sides.','私たちは反対側に住んでいる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['opposite']),
('option','オプション','選択肢','I have two options.','2つの選択肢がある。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['option','choice']),
('or','オア','または、さもなければ','Coffee or tea?','コーヒーか紅茶は？','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['or']),
('orange','オレンジ','オレンジ、オレンジ色','I like orange juice.','オレンジジュースが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['orange']),
('order','オーダー','命令、注文','May I take your order?','ご注文を伺いましょうか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['order']),
('organize','オーガナイズ','組織する、整理する','Organize your desk.','机を整理しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['organize']),
('other','アザー','他の','Do you have other ideas?','他に考えはありますか。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['other']),
('otherwise','アザーワイズ','さもなければ','Hurry, otherwise you''ll be late.','急げ、さもなければ遅れるぞ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['otherwise']),
('ought','オート','〜すべきである','You ought to study hard.','一生懸命勉強すべきだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['ought']),
('our','アワー','私たちの','This is our house.','これは私たちの家だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['our']),
('ours','アワーズ','私たちのもの','That house is ours.','あの家は私たちのものだ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['ours']),
('ourselves','アワーセルヴズ','私たち自身','We enjoyed ourselves.','私たちは楽しんだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['ourselves']),
('out','アウト','外へ、外に','Let''s go out.','外出しよう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['out']),
('outcome','アウトカム','結果','What was the outcome?','結果はどうだった？','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['outcome','result']),
('outdoor','アウトドア','屋外の','We love outdoor activities.','私たちは屋外活動が好きだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['outdoor']),
('outside','アウトサイド','外側、外に','Wait outside.','外で待ちなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['outside']),
('outstanding','アウトスタンディング','傑出した、目立った','He did an outstanding job.','彼は傑出した仕事をした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['outstanding']),
('over','オーバー','〜の上に、終わって','The game is over.','試合は終わりだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['over']),
('overall','オーバーオール','全体的な','The overall result is good.','全体的な結果は良い。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['overall']),
('overcome','オーバーカム','克服する','Overcome your fears.','恐怖心を克服しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['overcome']),
('overseas','オーバーシーズ','海外へ','I want to go overseas.','海外へ行きたい。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['overseas','abroad']),
('own','オウン','自分自身の、所有する','I have my own room.','自分自身の部屋がある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['own']),
('owner','オーナー','所有者、飼い主','Who is the owner?','所有者は誰ですか。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['owner']),
('oxygen','オキシジェン','酸素','We need oxygen to live.','生きるために酸素が必要だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['oxygen']),
('pace','ペース','歩調、歩く速さ','Keep your own pace.','自分のペースを守りなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pace']),
('pack','パック','荷造りする、詰める','Pack your bags.','荷造りしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pack']),
('package','パッケージ','小包、パッケージ','I received a package.','小包を受け取った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['package']),
('page','ページ','ページ','Turn to page ten.','10ページを開きなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['page']),
('pain','ペイン','痛み','I feel a sharp pain.','激しい痛みを感じる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pain']),
('paint','ペイント','塗る、絵の具、絵','He is painting the wall.','彼は壁を塗っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['paint']),
('painter','ペインター','画家、ペンキ屋','He is a famous painter.','彼は有名な画家だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['painter']),
('pair','ペアー','一組、ペア','A pair of shoes.','靴1足。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pair']),
('palace','パレス','宮殿','We visited the palace.','私たちは宮殿を訪れた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['palace']),
('pan','パン','鍋','Put it in a pan.','鍋に入れなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['pan']),
('panic','パニック','パニック、恐慌','Don''t panic.','パニックにならないで。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['panic']),
('paper','ペーパー','紙、新聞','Use a piece of paper.','紙を1枚使いなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['paper']),
('paragraph','パラグラフ','段落','Read this paragraph.','この段落を読みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['paragraph']),
('parent','ペアレント','親','His parents are kind.','彼の両親は親切だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['parent']),
('park','パーク','公園、駐車する','Let''s go to the park.','公園に行こう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['park']),
('part','パート','部分、役割','This is a part of the plan.','これは計画の一部だ。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['part']),
('participate','パーティシペイト','参加する','I want to participate.','参加したいです。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['participate','take part in']),
('particular','パーティキュラー','特定の、特有の','Is there a particular reason?','特定の理由がありますか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['particular']),
('party','パーティ','パーティー、政党','We had a great party.','素晴らしいパーティーを開いた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['party']),
('pass','パス','通過する、合格する','I passed the test.','試験に合格した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pass']),
('passage','パッセージ','一節、通路','Read the passage aloud.','その一節を音読しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['passage']),
('passenger','パッセンジャー','乗客','The passengers are waiting.','乗客たちが待っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['passenger']),
('passion','パッション','情熱','He has a passion for music.','彼は音楽に情熱を燃やしている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['passion']),
('passive','パッシヴ','受動的な、消極的な','He is too passive.','彼は消極的すぎる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['passive']),
('past','パスト','過去、過去の','Forget the past.','過去を忘れなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['past']),
('path','パス','小道','Walk along the path.','その小道を歩きなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['path']),
('patience','ペイシェンス','忍耐','Have some patience.','少し辛抱しなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['patience']),
('patient','ペイシェント','患者、忍耐強い','The patient is sleeping.','患者は眠っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['patient']),
('pattern','パターン','型、模様','I like this pattern.','この模様が好きだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pattern']),
('pause','ポーズ','一時停止する','Pause the video.','ビデオを一時停止しなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pause']),
('pay','ペイ','払う','I paid for the meal.','食事代を払った。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pay']),
('peace','ピース','平和','We want world peace.','私たちは世界平和を望む。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['peace']),
('peaceful','ピースフル','平和な','It is a peaceful village.','それは平和な村だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['peaceful']),
('pen','ペン','ペン','Can I use your pen?','ペンを使ってもいいですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['pen']),
('pencil','ペンシル','鉛筆','I need a pencil.','鉛筆が必要です。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['pencil']),
('people','ピープル','人々','Many people were there.','多くの人々がそこにいた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['people']),
('per','パー','〜につき','50 dollars per person.','1人につき50ドル。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['per']),
('perfect','パーフェクト','完璧な','The plan is perfect.','その計画は完璧だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['perfect']),
('perform','パフォーム','実行する、演じる','They performed well.','彼らはうまく実行した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['perform']),
('performance','パフォーマンス','公演、性能','It was a great performance.','素晴らしい公演だった。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['performance']),
('perhaps','パハプス','たぶん','Perhaps he is busy.','たぶん彼は忙しい。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['perhaps','maybe']),
('period','ピリオド','期間、時代','It is a short period.','それは短い期間だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['period']),
('permanent','パーマネント','永久の','It is not a permanent solution.','それは恒久的な解決策ではない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['permanent']),
('permission','パーミッション','許可','Do I have your permission?','許可をいただけますか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['permission']),
('permit','パーミット','許可する','They don''t permit smoking.','喫煙は許可されていない。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['permit','allow']),
('person','パーソン','人','She is a kind person.','彼女は親切な人だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['person']),
('personal','パーソナル','個人的な','That is a personal question.','それは個人的な質問だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['personal']),
('personality','パーソナリティ','性格、個性','She has a bright personality.','彼女は明るい性格だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['personality']),
('persuade','パースウェイディ','説得する','I persuaded him to go.','行くように彼を説得した。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['persuade']),
('phone','フォン','電話','Can I use your phone?','電話を借りていいですか。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['phone','telephone']),
('photo','フォト','写真','Take a photo of me.','私の写真を撮って。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['photo','photograph']),
('phrase','フレーズ','句、言い回し','I learned a new phrase.','新しい言い回しを学んだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['phrase']),
('physical','フィジカル','身体の、物理的な','He has physical strength.','彼は身体的な力がある。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['physical']),
('physics','フィジックス','物理学','I study physics at school.','学校で物理学を学んでいる。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['physics']),
('piano','ピアノ','ピアノ','She plays the piano.','彼女はピアノを弾く。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['piano']),
('pick','ピック','摘む、選ぶ','Pick some flowers.','花を摘みなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pick']),
('picture','ピクチャー','絵、写真','Look at the picture.','その絵（写真）を見なさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['picture']),
('piece','ピース','一枚、破片','Give me a piece of paper.','紙を1枚ちょうだい。','中1','標準','premium',false,ARRAY['高校受験'],ARRAY['piece']),
('pile','パイル','積み重ね、山','A pile of books.','本山。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['pile']),
('pilot','パイロット','操縦士','He is an airline pilot.','彼は航空機の操縦士だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pilot']),
('pin','ピン','ピン、留める','Pin it to the board.','それをボードにピンで留めなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pin']),
('pink','ピンク','ピンク色','She likes pink.','彼女はピンク色が好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['pink']),
('pipe','パイプ','管、パイプ','The pipe is broken.','パイプが壊れている。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pipe']),
('place','プレイス','場所','This is a quiet place.','ここは静かな場所だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['place']),
('plain','プレイン','明白な、平易な','The meaning is plain.','その意味は明白だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['plain']),
('plan','プラン','計画、計画する','What is your plan?','あなたの計画は何ですか。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['plan']),
('plane','プレイン','飛行機','We traveled by plane.','私たちは飛行機で旅行した。','中1','基礎','premium',false,ARRAY['高校受験','同義語'],ARRAY['plane','airplane']),
('planet','プラネット','惑星','Earth is a planet.','地球は惑星だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['planet']),
('plant','プラント','植物、植える','Water the plants.','植物に水をやりなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['plant']),
('plastic','プラスティック','プラスチック','It is made of plastic.','それはプラスチック製だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['plastic']),
('plate','プレート','皿','Put it on the plate.','それを皿に乗せなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['plate']),
('play','プレイ','遊ぶ、演奏する','Let''s play soccer.','サッカーをしよう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['play']),
('player','プレイヤー','選手、演奏者','He is a good player.','彼は良い選手だ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['player']),
('pleasant','プレザント','快適な、心地よい','Have a pleasant day.','良い一日を。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pleasant']),
('please','プリーズ','喜ばせる、〜してください','Please help me.','手伝ってください。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['please']),
('pleased','プリーズド','喜んで','I am pleased to meet you.','お会いできてうれしいです。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pleased']),
('pleasure','プレジャー','喜び、楽しみ','It is a great pleasure.','それは大きな喜びです。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pleasure']),
('plenty','プレンティ','豊富な','We have plenty of food.','食べ物はたくさんある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['plenty']),
('plus','プラス','〜を足した、プラス','Two plus two is four.','2足す2は4だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['plus']),
('pocket','ポケット','ポケット','I have a key in my pocket.','ポケットに鍵が入っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pocket']),
('poem','ポエム','詩','He wrote a beautiful poem.','彼は美しい詩を書いた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['poem']),
('poet','ポエット','詩人','He is a famous poet.','彼は有名な詩人だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['poet']),
('point','ポイント','点、要点、指す','What is your point?','あなたの言いたいことは何ですか。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['point']),
('poison','ポイズン','毒','It is dangerous poison.','それは危険な毒だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['poison']),
('police','ポリス','警察','Call the police.','警察を呼びなさい。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['police']),
('policy','ポリシー','政策、方針','It is our policy.','それが我々の方針だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['policy']),
('polite','ポライト','礼儀正しい','He is very polite.','彼はとても礼儀正しい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['polite']),
('political','ポリティカル','政治の','It is a political issue.','それは政治的問題だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['political']),
('politics','ポリティクス','政治','He is interested in politics.','彼は政治に興味がある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['politics']),
('pollute','ポリュート','汚染する','Cars pollute the air.','車は空気を汚染する。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['pollute']),
('pollution','ポリューション','汚染','Air pollution is a problem.','大気汚染は問題だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pollution']),
('pool','プール','プール','Let''s swim in the pool.','プールで泳ごう。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['pool']),
('poor','プア','貧しい、下手な','He was a poor boy.','彼は貧しい少年だった。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['poor']),
('pop','ポップ','ポップ音楽','I like pop music.','ポップ音楽が好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['pop']),
('popular','ポピュラー','人気のある','He is a popular teacher.','彼は人気のある先生だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['popular']),
('population','ポピュレーション','人口','The population is large.','人口が多い。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['population']),
('port','ポート','港','The ship reached the port.','その船は港に着いた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['port']),
('pose','ポーズ','姿勢、ポーズ','Hold that pose.','そのポーズを保ちなさい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['pose']),
('position','ポジション','位置、立場','Change your position.','位置を変えなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['position']),
('positive','ポジティブ','肯定的な、積極的な','Be positive.','積極的になりなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['positive']),
('possess','ポゼス','所有する','He possesses many books.','彼は多くの本を所有している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['possess']),
('possession','ポゼッション','所有物','These are my possessions.','これらは私の所有物だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['possession']),
('possible','ポッシブル','可能な','Come as soon as possible.','できるだけ早く来なさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['possible']),
('post','ポスト','郵便、掲示する','Post this letter.','この手紙を出しなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['post']),
('pot','ポット','つぼ、鍋','The pot is on the fire.','鍋が火にかかっている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['pot']),
('potato','ポテト','ジャガイモ','I like fried potatoes.','フライドポテトが好きだ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['potato']),
('potential','ポテンシャル','潜在的な、可能性','He has great potential.','彼は大きな可能性を秘めている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['potential']),
('pour','ポア','注ぐ','Pour some water.','水を注ぎなさい。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['pour']),
('poverty','ポヴァティ','貧困','We must fight poverty.','貧困と戦わねばならない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['poverty']),
('powder','パウダー','粉','It is a white powder.','それは白い粉だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['powder']),
('power','パワー','力、権力','He has a lot of power.','彼は多くの権力を持っている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['power']),
('powerful','パワフル','強力な','He is a powerful man.','彼は強力な男だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['powerful']),
('practical','プラクティカル','実際的な、実用的な','It is a practical idea.','それは実用的な考えだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['practical']),
('practice','プラクティス','練習する、実行する','Practice makes perfect.','習うより慣れよ。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['practice']),
('praise','プレイズ','称賛する、ほめる','He praised her work.','彼は彼女の仕事をほめた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['praise']),
('pray','プレイ','祈る','They pray for peace.','彼らは平和のために祈る。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['pray']),
('precious','プレシャス','貴重な','Time is precious.','時間は貴重だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['precious']),
('predict','プリディクト','予言する、予測する','I cannot predict it.','それを予測できない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['predict']),
('prefer','プリファー','〜を好む','I prefer tea to coffee.','コーヒーより紅茶が好きだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['prefer']),
('preference','プリファレンス','好み、優先','What is your preference?','あなたの好みは何ですか。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['preference']),
('pregnant','プレグナント','妊娠した','She is pregnant.','彼女は妊娠している。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['pregnant']),
('prepare','プリペア','準備する','Prepare for the test.','試験の準備をしなさい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['prepare']),
('presence','プレゼンス','存在、出席','I felt his presence.','彼の存在を感じた。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['presence']),
('present','プレゼント','現在の、贈り物、出席している','He gave me a present.','彼が私にプレゼントをくれた。','中1','基礎','premium',false,ARRAY['高校受験'],ARRAY['present'])
ON CONFLICT (word) DO NOTHING;
