-- 有料版＝高校受験対応。同義語（複数正解）・熟語を含む。tier='premium'（冪等 upsert）。
INSERT INTO words (word, reading, meaning, example_en, example_ja, grade, level, tier, is_idiom, tags, answers_en) VALUES
-- === 同義語グループ（複数正解）===
('many','メニー','たくさんの、多くの','I have many books.','私はたくさんの本を持っています。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['many','a lot of']),
('begin','ビギン','始める、始まる','The class begins at nine.','授業は9時に始まります。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['begin','start']),
('large','ラージ','大きい、広い','He lives in a large house.','彼は大きな家に住んでいます。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['large','big']),
('purchase','パーチェス','購入する、買う','She wants to purchase a car.','彼女は車を買いたい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['purchase','buy']),
('quick','クイック','速い','He gave a quick answer.','彼は素早く答えた。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['quick','fast']),
('kind','カインド','親切な、優しい','She is kind to everyone.','彼女は誰にでも親切です。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['kind','gentle']),
('smart','スマート','賢い','He is a smart student.','彼は賢い生徒です。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['smart','clever','wise']),
('glad','グラッド','うれしい','I am glad to see you.','あなたに会えてうれしいです。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['glad','happy']),
('sick','シック','病気の','He is sick in bed.','彼は病気で寝ています。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['sick','ill']),
('difficult','ディフィカルト','難しい','This question is difficult.','この問題は難しい。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['difficult','hard']),
('present','プレゼント','贈り物','I got a birthday present.','誕生日の贈り物をもらった。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['present','gift']),
('ocean','オーシャン','海、大洋','The ocean is deep.','海は深い。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['ocean','sea']),
('almost','オールモスト','ほとんど','It is almost noon.','もうすぐ正午です。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['almost','nearly']),
('choose','チューズ','選ぶ','Choose your favorite color.','好きな色を選んで。','中3','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['choose','select']),
('answer','アンサー','答える、答え','Please answer the question.','質問に答えてください。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['answer','reply']),
('end','エンド','終わる、終わり','The movie ends at ten.','映画は10時に終わる。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['end','finish']),
-- === 熟語（is_idiom）===
('a lot of','ア ロット オブ','たくさんの','There are a lot of people here.','ここにはたくさんの人がいます。','中2','標準','premium',true,ARRAY['熟語'],ARRAY['a lot of','lots of']),
('look forward to','ルック フォワード トゥ','〜を楽しみに待つ','I look forward to seeing you.','お会いするのを楽しみにしています。','中3','難関','premium',true,ARRAY['熟語'],ARRAY['look forward to']),
('be good at','ビー グッド アット','〜が得意である','She is good at math.','彼女は数学が得意です。','中2','標準','premium',true,ARRAY['熟語'],ARRAY['be good at','good at']),
('be interested in','ビー インタレステッド イン','〜に興味がある','I am interested in science.','私は科学に興味があります。','中2','標準','premium',true,ARRAY['熟語'],ARRAY['be interested in','interested in']),
('get up','ゲット アップ','起きる','I get up at six every day.','毎日6時に起きます。','中1','基礎','premium',true,ARRAY['熟語'],ARRAY['get up']),
('look for','ルック フォー','〜を探す','I am looking for my key.','鍵を探しています。','中2','標準','premium',true,ARRAY['熟語'],ARRAY['look for','search for']),
('take care of','テイク ケア オブ','〜の世話をする','She takes care of her cat.','彼女は猫の世話をします。','中3','標準','premium',true,ARRAY['熟語'],ARRAY['take care of','care for']),
('for example','フォー イグザンプル','例えば','I like fruit, for example apples.','果物が好きです、例えばリンゴ。','中2','標準','premium',true,ARRAY['熟語'],ARRAY['for example','for instance']),
('be able to','ビー エイブル トゥ','〜できる','He is able to swim well.','彼は上手に泳げます。','中3','標準','premium',true,ARRAY['熟語'],ARRAY['be able to']),
('would like to','ウッド ライク トゥ','〜したい','I would like to go home.','家に帰りたいです。','中3','標準','premium',true,ARRAY['熟語'],ARRAY['would like to']),
('have to','ハフ トゥ','〜しなければならない','I have to study tonight.','今夜は勉強しなければならない。','中2','標準','premium',true,ARRAY['熟語'],ARRAY['have to','must']),
('a lot','ア ロット','たくさん、とても','Thank you a lot.','本当にありがとう。','中2','標準','premium',true,ARRAY['熟語'],ARRAY['a lot']),
('listen to','リッスン トゥ','〜を聞く','I listen to music every day.','毎日音楽を聞きます。','中1','基礎','premium',true,ARRAY['熟語'],ARRAY['listen to']),
('arrive at','アライブ アット','〜に着く','We arrived at the station.','私たちは駅に着いた。','中3','標準','premium',true,ARRAY['熟語'],ARRAY['arrive at','get to','reach']),
('be proud of','ビー プラウド オブ','〜を誇りに思う','I am proud of my team.','私はチームを誇りに思う。','中3','難関','premium',true,ARRAY['熟語'],ARRAY['be proud of','proud of']),
('give up','ギブ アップ','あきらめる','Don''t give up your dream.','夢をあきらめないで。','中3','標準','premium',true,ARRAY['熟語'],ARRAY['give up']),
('come true','カム トゥルー','実現する','My dream came true.','私の夢が実現した。','中3','標準','premium',true,ARRAY['熟語'],ARRAY['come true']),
('be afraid of','ビー アフレイド オブ','〜を恐れる','She is afraid of dogs.','彼女は犬を恐れている。','中3','標準','premium',true,ARRAY['熟語'],ARRAY['be afraid of','afraid of']),
('think of','シンク オブ','〜を思いつく、考える','I can''t think of his name.','彼の名前が思い出せない。','中3','標準','premium',true,ARRAY['熟語'],ARRAY['think of']),
('be famous for','ビー フェイマス フォー','〜で有名である','Kyoto is famous for temples.','京都は寺で有名です。','中3','難関','premium',true,ARRAY['熟語'],ARRAY['be famous for','famous for']),
('on time','オン タイム','時間通りに','The train came on time.','電車は時間通りに来た。','中3','標準','premium',true,ARRAY['熟語'],ARRAY['on time']),
('right now','ライト ナウ','今すぐ','Do it right now.','今すぐやって。','中2','標準','premium',true,ARRAY['熟語'],ARRAY['right now']),
-- === 高校受験レベル単語 ===
('important','インポータント','重要な','Health is important.','健康は重要です。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['important']),
('decide','ディサイド','決める','I decided to study abroad.','留学することを決めた。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['decide']),
('environment','エンバイロンメント','環境','We must protect the environment.','環境を守らねばならない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['environment']),
('experience','エクスペリエンス','経験','It was a good experience.','それは良い経験でした。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['experience']),
('improve','インプルーブ','改善する、上達する','I want to improve my English.','英語を上達させたい。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['improve']),
('introduce','イントロデュース','紹介する','Let me introduce myself.','自己紹介させてください。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['introduce']),
('necessary','ネセサリー','必要な','Sleep is necessary for health.','睡眠は健康に必要です。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['necessary']),
('opinion','オピニオン','意見','Tell me your opinion.','あなたの意見を教えて。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['opinion']),
('perhaps','パハップス','たぶん、もしかすると','Perhaps he is right.','たぶん彼は正しい。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['perhaps','maybe']),
('reason','リーズン','理由','Tell me the reason.','理由を教えて。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['reason']),
('remember','リメンバー','覚えている、思い出す','I remember her face.','彼女の顔を覚えている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['remember']),
('understand','アンダースタンド','理解する','I understand your feelings.','あなたの気持ちが分かります。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['understand']),
('among','アマング','〜の間で','He is popular among students.','彼は生徒の間で人気だ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['among']),
('character','キャラクター','性格、登場人物','He has a good character.','彼は良い性格をしている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['character']),
('communicate','コミュニケート','意思を伝え合う','We communicate by email.','私たちはメールで連絡を取り合う。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['communicate']),
('culture','カルチャー','文化','I am interested in Japanese culture.','私は日本文化に興味がある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['culture']),
('difference','ディファレンス','違い','There is a big difference.','大きな違いがある。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['difference']),
('especially','エスペシャリー','特に','I like fruit, especially peaches.','果物、特に桃が好きだ。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['especially']),
('future','フューチャー','未来、将来','Think about your future.','将来について考えて。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['future']),
('health','ヘルス','健康','Health is more important than money.','健康はお金より大切だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['health']),
('information','インフォメーション','情報','I need more information.','もっと情報が必要だ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['information']),
('language','ランゲージ','言語','English is a useful language.','英語は役立つ言語だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['language']),
('nature','ネイチャー','自然','I love nature.','私は自然が大好きだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['nature']),
('peace','ピース','平和','We all want peace.','私たちは皆平和を望む。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['peace']),
('problem','プロブレム','問題','We solved the problem.','私たちは問題を解決した。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['problem']),
('protect','プロテクト','守る','We must protect animals.','動物を守らねばならない。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['protect']),
('research','リサーチ','研究、調査','She does research on plants.','彼女は植物の研究をしている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['research']),
('society','ソサエティ','社会','We live in a busy society.','私たちは忙しい社会に生きている。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['society']),
('special','スペシャル','特別な','Today is a special day.','今日は特別な日だ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['special']),
('success','サクセス','成功','Hard work leads to success.','努力は成功につながる。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['success']),
('though','ゾウ','〜だけれども','Though it was cold, we went out.','寒かったけれど出かけた。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['though','although']),
('useful','ユースフル','役に立つ','This book is very useful.','この本はとても役立つ。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['useful']),
('voice','ボイス','声','She has a beautiful voice.','彼女は美しい声をしている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['voice']),
('weather','ウェザー','天気','How is the weather today?','今日の天気はどう？','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['weather']),
('wonderful','ワンダフル','すばらしい','We had a wonderful time.','私たちはすばらしい時を過ごした。','中2','標準','premium',false,ARRAY['高校受験','同義語'],ARRAY['wonderful','great']),
('worry','ワリー','心配する','Don''t worry about it.','それについて心配しないで。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['worry']),
('agree','アグリー','賛成する','I agree with you.','あなたに賛成です。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['agree']),
('break','ブレイク','壊す、休憩','Don''t break the window.','窓を割らないで。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['break']),
('bring','ブリング','持ってくる','Bring your umbrella.','傘を持ってきて。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['bring']),
('carry','キャリー','運ぶ','He carried the heavy box.','彼は重い箱を運んだ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['carry']),
('catch','キャッチ','つかまえる','Catch the ball!','ボールをつかまえて！','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['catch']),
('change','チェンジ','変える、変化','We need to change our plan.','計画を変える必要がある。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['change']),
('continue','コンティニュー','続ける','Continue your work.','仕事を続けて。','中3','難関','premium',false,ARRAY['高校受験'],ARRAY['continue']),
('explain','エクスプレイン','説明する','Please explain the rule.','ルールを説明してください。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['explain']),
('invite','インバイト','招待する','I invited her to the party.','彼女をパーティーに招待した。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['invite']),
('receive','レシーブ','受け取る','I received your letter.','あなたの手紙を受け取った。','中3','難関','premium',false,ARRAY['高校受験','同義語'],ARRAY['receive','get']),
('return','リターン','帰る、返す','Return the book by Monday.','月曜までに本を返して。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['return']),
('share','シェア','共有する、分け合う','Let''s share the pizza.','ピザを分け合おう。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['share']),
('teach','ティーチ','教える','She teaches English.','彼女は英語を教えている。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['teach']),
('travel','トラベル','旅行する','I want to travel abroad.','海外旅行をしたい。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['travel']),
('visit','ビジット','訪れる','We visited our grandmother.','私たちは祖母を訪ねた。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['visit']),
('grow','グロウ','育つ、育てる','Plants grow in spring.','植物は春に育つ。','中3','標準','premium',false,ARRAY['高校受験'],ARRAY['grow']),
('hope','ホープ','望む、希望','I hope you get well soon.','早く良くなることを願っています。','中2','標準','premium',false,ARRAY['高校受験'],ARRAY['hope'])
ON CONFLICT (word) DO UPDATE SET
  reading = EXCLUDED.reading,
  meaning = EXCLUDED.meaning,
  example_en = EXCLUDED.example_en,
  example_ja = EXCLUDED.example_ja,
  grade = EXCLUDED.grade,
  level = EXCLUDED.level,
  tier = 'premium',
  is_idiom = EXCLUDED.is_idiom,
  tags = EXCLUDED.tags,
  answers_en = EXCLUDED.answers_en;
